### ISSUE TITLE
Change MaxParallelism after start

### ISSUE THREAD

**Issue by magnusanderholm** [rebus-org/Rebus#1023]
Hi
I've been using rebus for a while (great project btw). I'm using it with the PostgresSQL transport. As I understand you normally configure rebus by doing something like this 

```
Configure.With(...)
    .(...)
    .Options(o => {
        o.SetNumberOfWorkers(1);
        o.SetMaxParallelism(2);
    })
    .Start();
```

So we set the options before we start handling messages. However is it possible to change options afterwards? In particular I need to change `MaxParallelism` when we handle arriving messages. 

The reason being is that we have multiple queues and if one of them gets a message it checks if another queue is processing. If not then we want to increase `MaxParallelism` to ensure that the current queue can handle more messages temporarily. Otherwise we scale it back by setting `MaxParallelism`  to 1. When messages arrive on a queue we do some pretty expensive processing of data (both in terms of CPU, RAM and I/O). Therefore we want to maximize processing throughput by temporarily increasing `MaxParallelism` for a queue when no other queues are processing. Not sure if my explanation makes sense?
We are not talking high frequency messaging here either. Messages do arrive in bursts though and most of the time only on one of the queues.

**Comment by mookid8000** [comment]
I think I understand your sentiment, but I think it might not be necessary to change max parallelism after the fact.

Having a high max parallelism doesn't really cost you anything in terms of CPU and memory usage (unless of course each task allocates a significant amount of memory).

So one would usually be fine setting the max parallelism to a slightly high setting (e.g. 10, 20, 50 or something like that), depending on the available capacity "downstream"(*)

It makes more sense to vary the number of workers, especially if the transport is actually synchronous in the way it receives messages (e.g. like MSMQ and RabbitMQ). A "worker" in Rebus terminology is a dedicated thread that works as a message pump, receiving a message and dispatching it to the incoming pipeline, and so it comes with a cost in terms of CPU and memory usage. You can read more about it on the wiki here: 👉 https://github.com/rebus-org/Rebus/wiki/Workers-and-parallelism

Because of this, I once created the [Rebus.AutoScaling](https://github.com/rebus-org/Rebus.AutoScaling) extension, which will vary the number of workers automatically depending on whether threads are running idle.

So maybe it would make sense to do something like this:
```csharp
services.AddRebus(
	configure => configure
		.(...)
		.Options(o => {
			o.EnableAutoScaling(maxNumberOfWorkers: 5, maxParallelism: 20)
		})
);
```
to automatically run with a high number of workers when there's work to do and a lower number (as low as 1) when running idle?

I hope that makes sense 🙂 

---
(*) It's super-easy to flood a web application or a database with requests if said web app or DB does some significant work by setting max parallelism e.g. to 1000 or something like that. There's almost always a limit to how many concurrent operations it makes sense to initiate, and with C#'s `async` / `await` functionality it can sometimes be too easy to just pass the pressure downstream.
