### ISSUE TITLE
Expose read only interface to read saga data 

### ISSUE THREAD

**Issue by sabbadino** [rebus-org/Rebus#1037]
I am currently using an hack that I found in another post.
In my scenario I need to expand with saga data the info shown of an entity that is bound to a saga .. i don't need particular search capability , so having registered in IOC an interface that replicate the read only part of the existing private interface named isagastorage (if i remember well) would do.

**Comment by mookid8000** [comment]
It's possible to do what you request by "cheating" Rebus' decorator API, thus snatching its `ISagaStorage` instance.

Check out this test where I've demonstrated how to do it: https://github.com/rebus-org/Rebus.ServiceProvider/blob/master/Rebus.ServiceProvider.Tests/Hacks/ExposeRebusServiceViaServiceProvider.cs

Please note that this is not a supported scenario, so please ensure that your code is backed up by relevant integration tests to verify that your code will continue working as it should 😉

**Comment by sabbadino** [comment]
We are currently using a trick i found in a post in this repo .. i am interested to know why u think that having a read only interface on saga data is a bad pattern

**Comment by mookid8000** [comment]
> (...)  i am interested to know why u think that having a read only interface on saga data is a bad pattern

Dude, I didn't say that at all!

I said that it was not supported.

`ISagaStorage` is not public(*), mainly because I deliberately limit the size of the API surface that Rebus exposes. I do this, so people do not take hard dependencies on lots of stuff that might change over time.

You could argue that the saga storage would be a good candidate to be made public - and I'd probably agree with you a little bit there - but then what about `ISubscriptionStorage`, `ITimeoutStorage`, `IDatabusStorage`, `ITopicNameConvention`, `IRebusTime`, `IPipelineInvoker`, etc? Where's the line?

In this case (and in all of the cases mentioned above) I'd opt for NOT making it part of the API surface exposed to the developer when operating the bus, because I believe it will benefit all developers in the long run.

Does that make sense to you?


---

(*) ....and by "public" here we are talking about being public in the sense that a fully configured `IBus` and the container it lives in provides no way of obtaining `ISagaStorage` - technically, it IS public, as it's a [fully documented extension poin](https://github.com/rebus-org/Rebus/wiki/ISagaStorage)t in Rebus, e.g. so you can implement it yourself and provide whichever additional query methods you'd like to it.

**Comment by sabbadino** [comment]
I don't ask for isagastorage to be  public , i ask for an ioc available read only interface exposing 
Task<ISagaData> Find(Type sagaDataType, string propertyName, object propertyValue);

**Comment by sabbadino** [comment]
The general idea is that in some scenario saga data are linked to an entity search such as "employee" , and we offload to a saga its related workflow such as "interviewed" , hired, fired...
I would like to show the employee record augmented with this info
