### ISSUE TITLE
Question: Read Pending messages in order at startup

### ISSUE THREAD

**Issue by mohdali** [rebus-org/Rebus#1042]
Hi,

I'm using Rebus (With SQL Server Transport) to send messages to a consumer server which then triggers certain tasks. The order of the messages is important for task execution.

If the consumer server was offline and restarted, it will read all the pending messages during startup and probably not in the same order they were queued, which results in failed task execution.

Is it possible to resolve this by:

1- Ensure the messages are processed in the correct order when the consumer starts?
2- Put some delay in processing messages (only during startup) to allow the task execution to proceed?

Appreciate if you can guide me how to achieve this with Rebus.

**Comment by mookid8000** [comment]
> (..) The order of the messages is important for task execution.

Then message queueing might not be the best fit for your task, as message queues (even though they're almost always strictly FIFO) tend to experience reordering once they're running in the real world.

Reordering can happend because of competing consumers (either distributed, or because of in-process concurrent message processing), or because of failed messages returned to the queue after having spent a while in a dead-letter queue.

IOW to have strictly ordered processing of messages with message queues, you'll need to ensure that only one single consumer is running and that the consumer is processing a single message at a time.

> If the consumer server was offline and restarted, it will read all the pending messages during startup  (...)

I have no idea why you think it'll do this.

With Rebus and the SQL transport you can have strictly ordered processing of messages by configuring it like this:

```csharp
services.AddRebus(
	configure => configure
		.Transport(t => t.UseSqlServer(...))
		.Options(o => {
			// disable concurrent processing of messages
			o.SetMaxParallelism(1);
		})
);
```

and then ensuring that all of your message handlers will never let any exceptions escape, e.g. by using [Polly](https://github.com/App-vNext/Polly) for infinite retries (including proper cancellation support, so your app can shut down):

```csharp
public class ExampleMessageHandler : IHandleMessages<ExampleMessage>
{
	static readonly AsyncPolicy RetryPolicy = Policy.Handle<Exception>().RetryForeverAsync();

	readonly IMessageContext _messageContext;

	public ExampleMessageHandler(IMessageContext messageContext) => _messageContext = messageContext;

	public Task Handle(ExampleMessage message) => RetryPolicy.ExecuteAsync(token => ProcessMessage(message, token), _messageContext.GetCancellationToken());
	
	async Task ProcessMessage(ExampleMessage message, CancellationToken cancellationToken)
	{
		// ... process message here
	}
}
```

If you do this, you can start and stop your consumer whenever you want and be sure that messages are processed in order.

Just be sure to never start two instances of the same consumer. To be absolutely sure that that will never happen (in the face of overlapping instances during deployment, etc), I can recommend using a [distributed lock](https://github.com/madelson/DistributedLock) to be held for the entire lifetime of the application.

I hope that made sense 🙂

**Comment by mohdali** [comment]
Thank you for the detailed response and guideline. Will try following your example and make it work.
