### ISSUE TITLE
How to configure and use 2 buses with different transport in the same MessageHandler?

### ISSUE THREAD

**Issue by rasmuschristensen** [rebus-org/Rebus#1049]
Hey

We have a solution where 2 applications exchange messages using rebus with a SQL transport layer.
Within the application that receives messages we want to send new messages to a third application also using Rebus.
Now the issue is that the third application already have an input queue of MSMQ. 

Now the issue is how to configure a second bus with msmq and register it in the application that already have the rebus/sql setup.
As I can see from #791 though old, best practics is to have a single bus registration per container.....🤔

**Comment by mookid8000** [comment]
Rebus has always encouraged the "one bus per container"-approach, because it leaves much less room for mistakes - e.g. which bus instance should be injected when injecting `IBus`? - plus other similar and related questions.

This, combined with the fact the Rebus uses only one transport, implies that there is a default transport for your app.

In cases where you want to communicate with some other kind of transport, I recommend you implement it like you would in any other situation where you need to e.g. make HTTP calls and whatnot, which is usually by stashing the concrete details of making the communication happen away in a class somewhere, and then make use of it via a nice and slim interface, e.g. like this:

```csharp
public interface IMessageSender
{
	Task SendMessage(object message);
}
```

The implementation could be something like this (written from memory, might not compile):

```csharp
class MsmqMessageSender : IDisposable
{
	readonly Lazy<IBus> _bus = new(() => 
		Configure.OneWayClient()
			.Transport(t => t.UseMsmqAsOneWayClient())
			.Routing(r => r.TypeBased()
				.Map<SomeKindOfMessage>("some-kind-of-destination"))
			.Start()
	);

	public Task SendMessage(object message) => _bus.Value.Send(message);

	public void Dispose()
	{
		if (!_bus.IsValueCreated) return;

		_bus.Value.Dispose();
	}
}
```

The trick is of course to promote relevant parameters etc. and design the interface so it makes sense, and then push everything that your app doesn't care about into the implementation (`MsmqMessageSender` in this case).

I hope it makes sense 🙂
