### ISSUE TITLE
Time to receive.

### ISSUE THREAD

**Issue by k-best** [rebus-org/Rebus#1052]
Is there any way to set up time to receive for a message (and especially for a databus attachment)? This time can be used as cleanup policy for Databus storage and is useful help to avoid situation when consumer died and haven't unsubscribe (was terminated).

**Comment by mookid8000** [comment]
Rebus has the `rbs2-time-to-be-received` header (can be found as `Headers.TimeToBeReceived`), which you can set to a timespan - e.g. like so:

```csharp
var headers = new Dictionary<string, string> { [Headers.TimeToBeReceived] = "01:00:00" };
await bus.Send(message, headers);
```

which some transports (e.g. Azure Service Bus, MSMQ, ...) will detect and convert into an appropriate setting on the message, causing the transport layer to delete messages as they expire. Other transports (e.g. RabbitMQ and AmazonSQS) do not support message expiration natively, and so best thing Rebus can do in these cases is to detect expired messages when received and simply ignore them.

Regarding the data bus storage: Because of the very different nature of the types of storage, there's no built-in mechanism to clean up orphaned attachments. I recommend you e.g. configure your Azure Blob Storage to have a lifecycle management policy that will remove blobs older than, say, 3 months, or something similar.
