### ISSUE TITLE
How use Rebus with different projects languages (forming message)?

### ISSUE THREAD

**Issue by actorius** [rebus-org/Rebus#1055]
Hello!
I'm beginning view Rebus, and have a question about using in microservice architecture. As all know, different services can be written on different languages. It's fine if all use .net stack, but that if one service written on PHP should communicate with .net service where used Rebus? 
I'm tried use this case. Rebus use some headers to determine message type, for example `"ClassLibrary1.SendNotificationMessage, ClassLibrary1" "`. How PHP service should form message to this queue, manual write all needed headers for Rebus?

Previously i'm working with queues directly. In simple, create json Body for message and send it to target queue. On another side, consumer receive message, deserialize to DTO class and process.

What is practice use this scenario with Rebus?

**Comment by mookid8000** [comment]
Hi @actorius   – somehow I missed that you've asked this question, so sorry for being so slow to reply!

When Rebus sendsa and receives messages, it uses its [serializer](https://github.com/rebus-org/Rebus/wiki/Serialization) to map to/from "transport messages" (which is just string headers and a payload of bytes), so to be able to e.g. SEND from a PHP-based system to a .NET based Rebus endpoint you would need to make your chosen serializer happy.

As you have probably already figured out, the default serializer uses JSON as its format, in a way that requires that the `rbs2-msg-type` header contains a simple assembly-qualified type name that can be found at deserialization time.

Rebus does provide a way for you to customize this part though, e.g. by doing something like this:

```csharp
services.AddRebus(
	configure => configure
		.(...)
		.Serializer(s => {
			s.UseNewtonsoftJson(JsonInteroperabilityMode.PureJson);

			s.UseCustomMessageTypeNames()
				.AddWithCustomName<MyMessage>("my_php_message");
		})
);
```

which would make it possible for you to send a JSON message from PHP by setting the headers

* `rbs2-content-type`: `application/json; charset=utf-8`
* `rbs2-msg-type`: `my_php_message`

and setting the message body to UTF8-encoded JSON.

Rebus would then try to deserialize the message as the type `MyMessage`, so that type should match the incoming JSON.

I hope this helps 🙂
