### ISSUE TITLE
RabbitMQ transport different then others regarding message-id

### ISSUE THREAD

**Issue by riezebosch** [rebus-org/Rebus#1060]
As mentioned in some other issues as well, the RabbitMQ transports injects a pseudo-random message id for incoming messages when the rebus-specific header is missing.

Now I would love to see that functionality on other transports as well. I'm trying to open up the pub/sub for other participants that are unaware or unable to use rebus as a framework.

I've copied parts of the RabbitMQ transport and put it into a pipeline step that I inject right before the SimpleRetryStrategyStep. But instead of me doing that for my purposes is it something you would want to have in Rebus itself?

**Comment by riezebosch** [comment]
For me, I don't need the pseudo-random message id. It is only to satisfy the retry-step. Later on in the process, I replace the generated header with a value I read from the contents of the cloud event.

**Comment by mookid8000** [comment]
> But instead of me doing that for my purposes is it something you would want to have in Rebus itself?

Not sure, actually. Honestly, I cannot remember why the RabbitMQ transport got that functionality in the first place, because I think Rebus should throw an error if it detects an incoming message with missing, required pieces of information to avoid surprises when trying to consume messages from non-Rebus sources.

The reason I have this opinion is because it makes for the lowest risk of nasty surprises later on, if something fails because something did not work as expected.

I can definitely understand why an expert user then might want to circumvent the rejection, like you have done, by inserting a pipeline step before `SimpleRetryStrategyStep`. This is a great way to do it, but I think this should be opt-in. 

Since there's no reason for this to be part of Rebus itself, I recommend you simply package your pipeline step in a NuGet package and add some confoguration helper code similar to this:

```csharp
public static class RiezeboschConfigurationExtensions
{
	public static void ProvideStableSurrogateMessageIdsForIncomingMessages(this OptionsConfigurer configurer)
	{
		configurer.Decorate<IPipeline>(c => {
			var pipeline = c.Get<IPipeline>();
			var step = new YourCustomStep();
			return new PipelineStepConcatenator(pipeline)
				.OnReceive(step, AbsolutePosition.Front);
		});
	}
}
```
and then you can install your step wherever you need it like this:

```csharp
services.AddRebus(configure => configure
	.Transport(...)
	.Options(o => o.ProvideStableSurrogateMessageIdsForIncomingMessages())
);
```

**Comment by riezebosch** [comment]
That's indeed exactly [what I did](https://github.com/riezebosch/CloudEventify/tree/main/Rebus/CloudEventify.Rebus)! Except for the concatenator, didn't know about that one. Just wanted to make sure that if this applies to other expert users that there might be a fit in Rebus itself, probably with an opt-in. But it's no problem at all to ship it with my package otherwise.

**Comment by mookid8000** [comment]
Hi @riezebosch , I assume we can consider this issue solved? Closing for now... let me know if you have anything else 🙂
