### ISSUE TITLE
Any advice on deploying infrastructure from a pipeline

### ISSUE THREAD

**Issue by riezebosch** [rebus-org/Rebus#1062]
Is it possible to set up a bus with the only goal of deploying the infrastructure?

I like the idea of Rebus being in charge of creating topics and subscriptions, a bit like the code-first approach we got used to with EntityFramework. But I do need to set up a bus then from a designated command line application that I execute during the deployment pipeline without actually consuming messages from the bus. Is that possible? Or are there other ways of deploying the infrastructure using Rebus?

Hint: https://masstransit-project.com/advanced/topology/deploy.html#deploy-topology

**Comment by mookid8000** [comment]
This is a thing I've never considered, but I think I can understand why one might want to do that.

Rebus doesn't have anything built in, but it should be possible to do it with most of Rebus' transports, simply because of the fact that the transport implementation (i.e. the class implementing `ITransport`) is public and provides methods that can accomplish the necessary things.

I.e. with Azure Service Bus, you would new up a transport (satisfying the ctor's dependencies)

```csharp
var transport = new AzureServiceBusTransport(...);
```

and then, depending on which other interfaces the transport implements, you should be able to initialize it:

```csharp
transport.Initialize();
```
(if it implements `IInitializable` – will create the transport's own input queue), and register/unregister subscriptions:

```csharp
await transport.RegisterSubscriber(topic, queueName);
```

(where `queueName` must be the transport's own queue name for centralized transports, and `topic` can be set to Rebus' default assembly-qualified name by calling `typeof(MyMessage).GetSimpleAssemblyQualifiedName()`)

All of this should be possible to implement by having a single factory method somewhere that returns an `ITransport` implementation, and then a bunch of conditional stuff calling possible things depending on `IInitializable`, `IDisposable`, and `ISubscriptionStorage` – e.g. like

```csharp
var queueName = GetQueueNameFromSomewhere();
var transport = GetTransportImplementation(queueName);

try
{
	(transport as IInitializable)?.Initialize();

	if (transport is ISubscriptionStorage subscriptionStorage)
	{
		await subscriptionStorage.RegisterSubscriber("some-topic", queueName);
		await subscriptionStorage.RegisterSubscriber("another-topic", queueName);
	}
}
finally
{
	(transport as IDisposable)?.Dispose();	
}
```

or something like that.

**Comment by riezebosch** [comment]
It is just a matter of decorating the `IWorkerFactory` and returning a "lazy" worker that does nothing 😃. Might it be a worthy contribution to Rebus itself, including the docs?
