### ISSUE TITLE
rbs2-msg-type header not set when deserializing messages

### ISSUE THREAD

**Issue by jleon15** [rebus-org/Rebus#1081]
Hey everyone, we are starting to use Rebus to consume some messages that were not published by Rebus from a Azure Service Bus queue, but we are experiencing an issue when Rebus tries to deserialize the message before it is received by our handler.

 The exception thrown is 
``` 
---> System.ArgumentNullException: Value cannot be null. (Parameter 'returnType')
   at System.Text.Json.ThrowHelper.ThrowArgumentNullException(String parameterName)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at Rebus.Serialization.Json.SystemTextJsonSerializer.Deserialize(String bodyString, Type type)
   --- End of inner exception stack trace ---
```

This happens because the `rbs2-msg-type` header is not set on the TransportMessage as shown in the following screenshot:

<img width="749" alt="Screenshot 2023-03-09 at 17 37 05" src="https://user-images.githubusercontent.com/29789962/224406682-e15a1e63-4b38-4ce0-9840-17917f1f20b4.png">

If I change the serialization configuration to use Newtonsoft, then it doesn't throw because the Newtonsoft deserializer doesn't have that type condition check, and it deserializes it as a JObject. 

I was able to get past this by using a decorator that adds the `rbs2-msg-type` header to the messages, but this is a bad workaround since it means all messages will be set with the same type unless we add some dirty conditions. 

I would expect the `rbs2-msg-type` header to be set by Rebus and not depend on the data the Service Bus message contains, since that would mean external services need to know about Rebus implementation details. 

Am I missing something in the configuration or is this expected behaviour?

Here is my Rebus configuration in case it helps:
```                  
 configure.Transport
      (
         t =>
          {
              t.UseAzureServiceBus(configuration.GetConnectionString("ServiceBus"),
                "my-queue");
              t.Decorate(c => new RebusTransportDecorator(c.Get<ITransport>()));
          }
      )
      .Routing(r => r.TypeBased()
      .Map<MyType>(MessageTopics.MyTopic))
      .Serialization(c => c.UseNewtonsoftJson(new JsonSerializerSettings().InitializeDefaults()));
```

Thanks for the help!

**Comment by mookid8000** [comment]
> I would expect the rbs2-msg-type header to be set by Rebus and not depend on the data the Service Bus message contains, since that would mean external services need to know about Rebus implementation details.

> Am I missing something in the configuration or is this expected behaviour?

It's expected behavior.

Rebus' built-in serializers are made to be able to deserialize what they have themselves serialized.

You may be able to have one of Rebus' built-in JSON serializers deserialize your message properly, if you provide an acceptable rbs2-msg-type header yourself in your decorator. But generally, I advise people to treat messages to/from non-Rebus-based sources/targets as places where integration needs to take place instead of trying to bend Rebus into working with them directly. The reason for this is that it will often result in more brittle integrations with no guarantee that can e.g. port your code to another transport etc.

So my suggestion is that you create your own Azure Service Bus `ServiceBusProcessor` that receives your raw ASB messages and forwards them to Rebus.

I hope this makes sense. 🙂

**Comment by mookid8000** [comment]
> (..) so it knows the message type of a given topic?

This is unfortunately not really possible, because it's not given that only events of one particular type be published to a topic.

Rebus just defaults to publish e.g. `MyStuff.Messages.MyEvent, MyStuff.Messages` to a topic named after it (e.g. like `mystuff_messages/mystuff_messages_myevent` or something like that), but you might as well

```csharp
await bus.Advanced.Topics.Publish("custom_topic", new CustomEvent());
```

IOW Rebus can come up with a default topic name from the type (given the configured `ITopicNameConvention`), but it can't go from a topic name to a type.
