### ISSUE TITLE
The limit on the number of worker threads only take effect if the maximum parallelism is reached.

### ISSUE THREAD

**Issue by filipsichm** [rebus-org/Rebus#1082]
Rebus 6.6.5
Rebus.RabbitMq 7.4.2

A potential issue: unless the maximum parallelism is reached, the limit on the number of worker threads is not honoured.

_Steps_:

1, set the number of workers to 1, set the max parallelism value to 3,
2, send 6 messages of the same type at once,
3, put await _Task.Delay(1000)_ in the _Handle_ method to simulate an asynchronous work,
4, as expected: 3 messages are processed at the same time, after the first batch of messages is completed the next batch of messages (3) will start processing; output example:

```
[3/22/2023 10:08:30 AM] processing message; ID=2
[3/22/2023 10:08:30 AM] processing message; ID=0
[3/22/2023 10:08:30 AM] processing message; ID=1
[3/22/2023 10:08:40 AM] processing message; ID=3
[3/22/2023 10:08:40 AM] processing message; ID=4
[3/22/2023 10:08:40 AM] processing message; ID=5
```
5, now replace _await Task.Delay(1000)_ with _Thread.Sleep(1000)_ to simulate a synchronous work,
6, send the same 6 messages again,
7, expected: messages are processed one by one, actual: 3 messages start processing simultaneously, only after processing the first batch of messages, messages start processing one by one (the number of workers = 1); output example:

```
[3/22/2023 10:09:45 AM] processing message; ID=0
[3/22/2023 10:09:45 AM] processing message; ID=2
[3/22/2023 10:09:45 AM] processing message; ID=1
[3/22/2023 10:09:55 AM] processing message; ID=3
[3/22/2023 10:10:05 AM] processing message; ID=4
[3/22/2023 10:10:15 AM] processing message; ID=5
```

The question is: is this an actual issue or is this by design?

- _code samples_:
```
    [HttpGet]
    [AllowAnonymous]
    public async Task Send([FromServices] IBus bus)
    {
        for (int i = 0; i < 6; i++)
        {
            await bus.Send(new TestMessage { Id = i });
        }
    }

   public class TestHandler : IHandleMessages<TestMessage>
  {
      public async Task Handle(TestMessage message)
      {
          Console.WriteLine($"[{DateTime.UtcNow}] processing message; ID={message.Id}");
          //Thread.Sleep(10000);
          await Task.Delay(10000);
          await Task.CompletedTask;
      }
  }

```
Thank you!

**Comment by mookid8000** [comment]
> The question is: is this an actual issue or is this by design?

It's by design 🙂 

Rebus' worker threads do the initial receive on the transport, but the work is only ACTUALLY executed on the worker thread until the first `await` - after that, continuations are executed on the thread pool.

I think it's a little bit random that it turned out like this, but it has proven to work pretty well. But still, it could probably also be better.


The responsible class is [`ThreadPoolWorkerFactory`](https://github.com/rebus-org/Rebus/blob/master/Rebus/Workers/ThreadPoolBased/ThreadPoolWorkerFactory.cs)  which is the [`IWorkerFactory`](https://github.com/rebus-org/Rebus/blob/87b8bf21c703e2768d51088a4eb553cf37e73bdf/Rebus/Workers/IWorkerFactory.cs) implementation that Rebus will use by default.

It's entirely pluggable though, so one could register a custom worker factory if some other threading/polling strategy would work better.
