### ISSUE TITLE
Scale out - multiple producers and multiple consumers in the same topic/queue

### ISSUE THREAD

**Issue by NinjaCross** [rebus-org/Rebus#1084]
I've read the documentations and took a general overview to all the samples.
It seems everything well-explained, but I admit it's not very clear to me (sorry if I missed it somewhere) the behaviour of the system in the following cloud/distributed scenario:
- Multiple processess acting as producers
- Multiple processess acting as consumers
- A producer sends a message "X" into the topic/queue

How many consumers will receive the message "X" ?
Is it guaranteed (or can it be guaranteed) that **only one consumer will receive only once** the message "X" ?
Is the message always removed after a consumer receives it ?
If it's not the default behavior, which kind of configuration allows to enforce it ?
Does it depend on the kind of underlying provider ?

I'm particularly interested in using Redis and/or Sql Server as storage/transport.
Thankyou for any clarification.

**Comment by mookid8000** [comment]
Hi @NinjaCross , here's how it works with Rebus (regardless of which supported transport you're using):

1. When you SEND a message, Rebus will deliver one copy to a specific queue
2. When you PUBLISH a message, Rebus will deliver n copies to n queues (i.e. one per queue)

Generally, you'll just start a single Rebus instance that will consume messages from each queue. In some cases, though, when you need to scale up, you can start MULTIPLE instances of the same app, consuming messages from the SAME queue – this is called ["competing consumers"](https://www.enterpriseintegrationpatterns.com/patterns/messaging/CompetingConsumers.html).

### 1. About SENDing

When you SEND, you'll use 

```csharp
await bus.Send(new MyMessage());
```

and then you'll need to tell Rebus beforehand which queue to send messages of type `MyMessage` to. This is done with "endpoint mappings", e.g. like this:

```csharp
services.AddRebus(
	configure => configure
		.(...)
		.Routing(r => r.TypeBased().Map<MyMessage>("myqueue"))
);
```

In this case, messages of type `MyMessage` will be sent to the queue named "myqueue" when you `await bus.Send(new MyMessage())`.

### 2. About PUBLISHing

When you PUBLISH a message with Rebus, it'll be distributed in 0 copies to 0 subscribers by default 😁 so, in order to actually have someone receive the message, subscribers should SUBSCRIBE to the message type beforehand, e.g. like so:

```csharp
await bus.Subscribe<MyEvent>();
```

Calling `await bus.Subscribe<MyEvent>()` will create a binding between a topic that represents `MyEvent` and the caller's input queue. This way, whenever someone calls

```csharp
await bus.Publish(new MyEvent());
```

a copy of the `MyEvent` message will be distributed to each subscriber's input queue.

### To address your bullets I'll take them one by one

> Multiple processess acting as producers

Doesn't change anything. A "producer" would be a bus instance that either SENDs or PUBLISHes messages, and messages will simply be distributed as described above.

> Multiple processess acting as consumers

Each message copy will be consumed only once.

> A producer sends a message "X" into the topic/queue
> How many consumers will receive the message "X" ?

Depends on whether you SEND or PUBLISH. The logic is explained above.

> Is it guaranteed (or can it be guaranteed) that only one consumer will receive only once the message "X" ?
> Is the message always removed after a consumer receives it ?

Yes. Queueing systems usually work by placing some kind of lease on consumed messages, meaning that they're just made invisible for a while when received. If the consumer then ACKs the message before the lease expires, then the message is removed from the queue. If the consumer NACKs or doesn't reply at all, then the message will become visible again.

This way, each message copy will be consumed only once.

> If it's not the default behavior, which kind of configuration allows to enforce it ?

It's the default behavior when using Rebus, and it's either impossible or very hard to have it any other way with Rebus, because that's the type of messaging Rebus supports.

> Does it depend on the kind of underlying provider ?

No. To qualify as a "Rebus transport", the underlying queueing system/database needs to support mechanisms that allow for the behavior described above to be implemented. 

> I'm particularly interested in using Redis and/or Sql Server as storage/transport.

Unfortunately, there's no Redis transport. You can use Microsoft SQL Server as a transport, though, by adding the [Rebus.SqlServer](https://www.nuget.org/packages/Rebus.SqlServer) NuGet package and calling

```csharp
services.AddRebus(
	configure => configure
		.Transport(t => t.UseSqlServer(...))
		.(...)
);
```

I hope all of that made sense 🙂

**Comment by NinjaCross** [comment]
Thankyou very much for the explanations @mookid8000 , they have been extremely usefull!
