### ISSUE TITLE
Is there anyway to integrate Rebus with Amazon EventBridge?

### ISSUE THREAD

**Issue by labeled** [rebus-org/Rebus#1093]
Hello, thank you for your time. I currently use Rebus.AmazonSQS and it's working beautifully. We would like to get the benefits of rebus with our Amazon EventBridge bus's. Is that something Rebus could handle or is it outside the scope, since we wouldn't be the same sender when receiving messages?

Thanks again for your time :)

**Comment by mookid8000** [comment]
Hi @labeled , I am not familiar with Amazon EventBridge , and as far as I know there's currently no way Rebus can interact with it.

How did you imagine them working together?

**Comment by labeled** [comment]
The more I think about it, it's not really interaction with event bridge. I
need to have rebus consume messages that weren't sent by rebus.

We have messages sent to a bus, and that bus fwds messages to a queue, and
we want to subscribe to those messages using rebus.

That means it doesn't have any headers, or a Body.

I found a way to set headers so I can override those but I couldn't find a
way to set a different Body. Ie, our 'Body' is actually the 'detail'
property.

**Comment by mookid8000** [comment]
I usually do not recommend that people use Rebus to consume messages that were not produced by Rebus (or were produced with Rebus in mind), because I've seen too many attempts at doing this that seemed to go well most of the way, but then it turned out that some kind of obstacle made it impossible anyway.

Also, if you think a little bit about it, it's nicer to think of your Rebus-connected apps as a network of connected things, and then e.g. if you need to connect with another transport (e.g. Amazon EventBridge), then it's an integration at the periphery of this network. Then it's clear that your Rebus network will have all the nice Rebus properties (e.g. it's portable to another transport/hosting environment, you can connect them to Fleet Manager (if you have [Rebus Pro](https://pro.rebus.fm/) etc.), but at the periphery you'll need to tailor things to a higher degree.

I hope that makes sense. 🙂 

Btw. I'm closing this issue for now. Feel free to keep posting to this thread if you have further questions.
