### ISSUE TITLE
Limiting the handling of messages of the same type

### ISSUE THREAD

**Issue by den-bessal** [rebus-org/Rebus#1105]
Greetings!

How can I limit the processing of messages of the same type at parallelism?

For example, I have two types of message (bindings in RabbitMq): ForMessage and BarMessage. Messages are queued in the following order: Foo, Foo, Bar, Foo, Bar. Parallelism cap is 2. Prefetch count is 5. At the same time, only messages of different types should be handled at one time, in this case only one Foo message and one Bar message. That is, messages of the same type must be handled sequentially.

Is it possible to do something like this?

**Comment by mookid8000** [comment]
It's definitely possible, but there's nothing built-in in Rebus that will help you with this.

My recommendation is that you use a distributed locking library (e.g. [DistributedLock](https://github.com/madelson/DistributedLock), which is nice and easy to work with and has great support for a whole bunch of underlying technologies), because that way you can implement exclusivity as granular as you like. 🙂
