### ISSUE TITLE
Creating a queue when using AsOneWayClient

### ISSUE THREAD

**Issue by TimurSadorov** [rebus-org/Rebus#1120]
Hello! We need a message queue to be created when the application starts when using AsOneWayClient. 
I looked through the documentation and Googled and found nothing. Is it possible to do this and if so how?

**Comment by mookid8000** [comment]
No, unfortunately that's not readily possible.

Normal Rebus instances will (by default at least) create their own input queues, and then ensure that a dead-letter queue named "error" also exists. But since your Rebus instance is a one-way client, it doesn't have an input queue, and so it skips this part entirely.

**Comment by tleclaire** [comment]
I had the same question and was wondering, that when you have to add something to a queue in the first place to receive something I assumed thet the sender creates the queues
