### ISSUE TITLE
Is it possible to use Azure Blobs for Saga Storage?

### ISSUE THREAD

**Issue by dops0** [rebus-org/Rebus#1125]
I have just started exploring Rebus and have been able to successfully use Azure Queues for Transport. I've been experimenting with Sagas and was wondering if one could use Azure Blobs for Saga storage?

I see a method UseFilesystem when setting up the Rebus Configuration, but I don't see any method to use Azure Blobs. I do see some extension classes in in the Rebus.AzureBlobs repository but haven't been able to find any example of how one could use Azure Blobs for storing Saga state. Is it even possible?

**Comment by mookid8000** [comment]
It was once possible, but it turned out that the implementation could fail because of consistency problems between its state blob and its correlation properties (i.e. the secondary index used to look up blobs from property values of incoming messages), which had to reside in Azure Table Storage.

If you are running in Azure anyway, I suggest you use Rebus.SqlServer and provision a hosted SQL Server for blobs – maybe you can find a pricing tier that isn't too expensive which can still server your needs? It can also work as a subscription storage, i.e. "polyfill" the feature that maps topics to the input queues of subscribers, so you can do pub/sub messaging even though storage queues do not support that.
