### ISSUE TITLE
Approach to get Saga state

### ISSUE THREAD

**Issue by dops0** [rebus-org/Rebus#1126]
What would be the best approach for an application which isn't the Saga executor to get the current state of the Saga.

For example, if we take the Saga Demo in the documentation, we have `AmountsCalculated`, `TaxesCalculated`. Assuming AmountsCalculated and TaxesCalculated take hours to process, an external application might want to know the current status, i.e., areAmountsCalculated, areTaxesCalculated etc. 

Furthermore, maybe we could be having a REST service which is being invoked by a user to get the status, meaning, we probably need a quick way to get the current status and return it back. Is there already some way to get the Saga status, or do we need to go into the storage where Saga state is saved after identifying the SagaId corresponding to the CaseNumber (in case of the example)?

Thanks.

**Comment by mookid8000** [comment]
You may want to consider the following options:

1. "Reach into" the saga storage behind its back
1. Publish relevant info as events at the rate they become available
1. Code the saga manually

(1) would be if you were using SQL Server as your saga storage, and you then coded something that could retrieve and manually decode the saga's state. That's definitely possible, but you should of course take note of the fact that you are suddenly much more tied to a specific type of storage and data layout than you were before.

This means that you should of course cover your logic pretty thoroughly with some integration tests that both involve Rebus and your custom saga decoder. And you should probably also hide your implementation behind some kind of interface, so that your code can still be ported to other platforms, while still being observant of the fact that your next choice of saga storage might not offer the same capabilities for "reaching into" the saga storage behind Rebus' back.

(2) would be simply publishing an event (e.g. like `AmountsCalculated(string OrderId, decimal Amount)` once it has been calculated and is a pretty simple way of making any kind of information from the saga available to the outside world.

If you do this, please remember to add some kind of sequencing information to your events so the subscribers can figure out which data to keep, even if some of the events have been residing in a dead-letter queue for a while.

(3) is for when Rebus' sagas don't cut it 🙂 Rebus' sagas are simple and limited in many ways - this is intentional, because it makes it possible to make them act the same across all storage types, and because that's very often enough.

If you really need something beyond what Rebus' sagas can easily let you do, it isn't too hard, if you're already working with a database, to build something that correlates incoming messages, mutates some state, possibly uses [a distributed lock](https://github.com/madelson/DistributedLock) to coordinate state access in the face of parallelism, etc. to implement what Rebus does + whatever you feel like adding.
