### ISSUE TITLE
Outbox difficulty

### ISSUE THREAD

**Issue by dazinator** [rebus-org/Rebus#1132]
https://github.com/rebus-org/Rebus/wiki/Outbox

~~I took me a while to find this api, turns out you need to bring in the package `Rebus.SqlServer` not  just `Rebus.Outbox.SqlServer` not sure if its worth mentioning on wiki.~~

I spoke prematurely.

I am having difficulty finding this api.

I am using packages

- Rebus.SqlServer 8.0.2
- Rebus.SqlServer.Outbox 2.1.0

When I try to use this API, there are none that configure an `IOutboxStorage` - these are the ones I see:

<img width="1275" alt="image" src="https://github.com/rebus-org/Rebus/assets/3176632/3c286ae9-d1d6-4fdb-9eb7-63a40598bb9c">

e.g I see this extension method offered for DataBus storage, Saga storage, Saga snapshot storage, Subscription storage, and Timeout Manager storage.

Could someone point me in the right direction? I was hoping to configure the outbox with a conn string and table name.

**Comment by dazinator** [comment]
Is outbox used when InMemory network based transport, or FileSystem based transport is used? Reason I ask is that I am using these for the purposes of an exploratory test, and have enable Outbox in a sql server test container. I can see the Outbox table was created, but I don't see any messages persisted there. My test is running a saga with in memory saga storage. I have several handlers participating in the saga which is completing so expected to see several messages.

**Comment by mookid8000** [comment]
Hi @dazinator , you're right that Rebus + Rebus.SqlServer is enough to run Rebus using MSSQL Server as the outbox.

> (..)  it gives the illusion that by calling Outbox() you are provider agnostic, and only when you call StoreInSqlServer() you are accessing provider specefic apis (...)

Well, I can certainly understand why you might think that if you're not used to Rebus - but it's a general pattern in Rebus:

```csharp
services.AddRebus(configure => configure.Transport(t => {});
```

doesn't do anything, while

```csharp
services.AddRebus(configure => configure.Transport(t => t.UseAzureServiceBus(...));
```

does. That's just how it is with Rebus 🙂 

Btw. there's no such thing as being "provider agnostic" with Rebus' outbox implementation - it is very much coupled to MSSQL Server.

Oh, and if you want to use the Postgres outbox, you'll go  

```csharp
services.AddRebus(
    configure => configure
        .Transport(t => t.Use(...)
        .Outbox(o => o.StoreInPostgreSql(...))
);
```

but yes, you're right that the `.Outbox` extension happens to be defined by the outbox provider - this is because the outbox is not "core Rebus functionality", so the Rebus core library does not know anything about the concept. This can of course clash a bit if you're using both MSSQL and PostgreSQL in the same project.

Let me know if you have further questions. 🙂

**Comment by dazinator** [comment]
Thanks

> but yes, you're right that the .Outbox extension happens to be defined by the outbox provider

Thanks that it was I was trying to say in a roundabout way. I think most of the other api's have their provider specific extension method not directly on the RebusConfigurer. I appreciate outbox isn't provider agnostic just as transports aren't provider agnostic, but the transports don't carry their own `Transport()` extension method if you see what I mean ;-)

Anyway no big deal, everything seems working now, thank you ;-)
