### ISSUE TITLE
Question: Manually acknowledge the message in RabbitMQ

### ISSUE THREAD

**Issue by krunal-jethva-tark** [rebus-org/Rebus#1148]
My question is how can I send `notAcknowged` to rabbitMQ ? 

This is my demo handler where I'm intentionally failed the processing of message with id = 5. 

Currently, the message with ID = 5 stays in the `unacknowledged` state and on disposing it disappears from the queue. This leads to the behavior, when I restart the service or set the number of workers to 1 again, it will start fetching messages after ID = 5.

My original use case requires the message to be process in strict order and if anyone of the message fails, after some retries, I will stop processing more messages. And from there it would be manual task.

***Program.cs***
```C#
using var activator = new BuiltinHandlerActivator();
activator.Register(() => new UserCreatedEventHandler(activator.Bus));

var subscriber = Configure.With(activator)
    .Transport(t => t.UseRabbitMq("amqp://rabbitserver:rabbitserver@localhost:5672", "user-created").Prefetch(1))
    .Options(o => o.RetryStrategy(maxDeliveryAttempts: 3, secondLevelRetriesEnabled: true))
    .Options(o => o.SetMaxParallelism(1))
    .Start();

await subscriber.Subscribe<UserCreatedEvent>();
```

***UserCreatedEventHandler.cs***
```C#
internal class UserCreatedEventHandler(IBus bus) : IHandleMessages<UserCreatedEvent>, IHandleMessages<IFailed<UserCreatedEvent>>
{
    private readonly IBus _bus = bus;

    public async Task Handle(UserCreatedEvent message)
    {
        if (message.Id == 5)
        {
            throw new Exception("Unable to handle message");
        }
        Console.WriteLine($"{nameof(UserCreatedEvent)} received. Username: {message.UserName} {message.Id}");
    }

    public async Task Handle(IFailed<UserCreatedEvent> message)
    {
      // send nAck to rabbitMQ 
    
       // stop the further processing of messages
        _bus.Advanced.Workers.SetNumberOfWorkers(0);
    }
}
```

**Comment by krunal-jethva-tark** [comment]
Okay I think I have some potential solution to this. This is my redefined Fail event handler.
```C#
public async Task Handle(IFailed<UserCreatedEvent> message)
{
    await _bus.Unsubscribe<UserCreatedEvent>();
    _bus.Dispose();
}
```

But only issue I'm seeing is I have to completely shut down the service Otherwise the Message stays in `unacknowledged` state. just desposing the bus and unsubscribing to queue does not help.

**Comment by mookid8000** [comment]
I'm sorry to say it, but if you want to handle messages sequentially in strict order, message queues are generally not the best way. Especially if you're using a service bus like Rebus, because you have to work against it to achieve strictly ordered message processing (in this case because Rebus will try to move a failing message out of the way (to avoid "clogging the pipes", so to say, and so you have found out that you need to terminate everything to avoid continuing processing messages)

If I were you, I would either 

* make my message consumer tolerant to reordered messages - this would be the best solution
* use RabbitMQ directly without Rebus - this would be acceptable for your use case
* make it use e.g. Polly and infinite retries (passing Rebus' `messageContext.GetCancellationToken()` so Rebus can still shut down) - this would be the least appealing solution, at least to me

**Comment by krunal-jethva-tark** [comment]
Thank you for your detailed response. Even i was reconsidering my approach to handling this business requirement.

In our case, the message consumer cannot be tolerant to reordered messages due to the nature of the database sync operation.

While using RabbitMQ directly is acceptable for our use case, my team is inclined to use Rebus for its extension abilities, which would allow us to easily switch to other transport services if needed.

Sorry to bother, but Do you happen to know of any message brokers or tools that could be applicable to our use case? 

Our scenario involves modifying data on one instance and synchronizing the modified data to its dependent instances, with some business logic to be applied before processing the messages (which is why direct database synchronization is not suitable). Any suggestions would be greatly appreciated.

**Comment by mookid8000** [comment]
Since you're interested in recording events in order and consuming them in the same order, I would suggest you try to do without any kind of broker. That would probably fall short if you need something with better scaling properties, and in that case I would be tempted to look towards Kafka (possibly with [Topos](https://github.com/mookid8000/topos) on top), although managing Kafka is a pretty daunting task, so there you might want to look to one of the hosted Kafkas available (I'm using Confluent Cloud myself and have been for ~4 years now).

**Comment by krunal-jethva-tark** [comment]
I will definitely look into Kafka, 

Also, We're really impressed with the Rebus library and wanted to say a big thank you for all your hard work. It's awesome that you take the time to answer questions and help out on the internet. I'm grateful for you support

**Comment by mookid8000** [comment]
Cool! 👍 And thank you for your kind words - it makes me happy to hear that 🙂
