### ISSUE TITLE
Throw exception if a message causes multiple saga instances to load

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/Rebus#126]
Within one unit of work, it is an error if a message can be correlated with two saga instances. That goes for two instances of the same saga type (this constraint is enforced by the saga persistence), but also for two instances of sagas of different types.

**Comment by pruiz** [comment]
I know this is a bit old, but due to this restriction we are facing a few quirks and anti-patterns in our code, so I am thinking on a compromise scenario with MongoDbPersister where more than one SagaHandlar can be invoked (for the same message), but assuming an 'at least once' delivery support on saga handlers, and/or by saving already processed message-ids along with saga data. 

What I am thinking would be to 'simply' have MongoDbPersister instead of assuming a single UnitOfWork for each message received, to instead assume a UnitOfWork for each saga handler. This way, the persister would save changes after invoking each saga, but the message wont be ack'ed at rabbit until all saga handlers have been invoked.

So, if a Handler in the middle of the pipeline fails to process a message, an exception would be thrown, the message would be back at source's queue, and will be reprocessed next. As such, I see two paths we may follow during re-processing:

 1) The persister will save along with saga's details the list of message-ids which has already been processed successfully by this saga, so during reprocessing, already invoked sagas can be skipped. (This is similar [while a lot simpler] to my previous idempotent-sagas feature, but it is something which can be done from within the MongoDbPersister w/o side effects or modifications to other parts of the systems.
 2) The persister will simply call again all handlers (even already 'invoked ones', as the persister has no way to know wether a handler has already been invoked), and assume they will adhere to an 'at least once' delivery guarantee, and so, handle idempotency internally.
 
What do you think guys?

**Comment by mookid8000** [comment]
Hi @pruiz , first off I want to say that I really appreciate your work making it possible to have idempotent sagas etc. in Rebus :)

With this approach, wouldn't there be a problem with outgoing messages being lost?

Say, for instance, that we have saga A and B, and the following sequence of events occurs:

* saga A publishes a message
* saga A's data is updated
* saga B throws an exception

As far as I an tell, in this case the message published by A would be lost.

**Comment by pruiz** [comment]
Hi, 

I rally appreciate your comment here @mookid8000, as I was making a comment here at the issue as an open call for opinions in order to avoid errors I could have missed.. ;)

And in fact, you are more than correct in that w/o (being both A & B fully) idempotent sagas, in your example saga A's published message would be lost.. I missed that one. :?

It looks like only using fully idempotent sagas would allow for this to work, but in such a case using an interface (ICanUpdateMultipleSagasAtomically) as a means to let the dispatcher know if we can update multiple sagas poses the limitation that exposing an interface cannot be controlled dynamically.

I would argue then that we may need an additional check inside the dispatcher, so if more than one saga is to be invoked, and all of them are idempotent, let it rock. ;)

Maybe an additional interface (IMaybeCanUpdateMultipleSagasAtomically?) which exposes a method accepting the list of saga types and returns a boolean indicating wether this persistence provider is able to work with such sagas? 

Does it sound too convoluted?
