### ISSUE TITLE
Rebus.RabbitMq with merged/bundled RabbitMQ.Client dependency.

### ISSUE THREAD

**Issue by pruiz** [rebus-org/Rebus#199]
Hi,

I am currently migrating some projects to use Rebus instead of a previous in-house developed code using RabbitMQ.Client. Such a migration would be done at incremental steps, first using both systems at the same time, and then, once everything works, removing legacy code and relaying on Rebus only.

However, during the upgrade I faced a problem with missmatching versions of RabbitMQ.Client between the one needed by Rebus and the one used by legacy code.

My current solution is using ILRepack (an ilmerge alternative) to bundle RabbitMQ.Client (and internalize) into Rebus.RabbitMQ... This way I will create an alternate Rebus.RabbitMQ nupkg which will be published to our internal nuget repo.

But maybe this is something worth not only for me, but usefull for others too. If so, I could send a pull-request modifying Rebus' scripts in order to create an additional nuget versions Rebus.RabbitMQ, with bundled rabbitmq dependency.

Opinions?

**Comment by mookid8000** [comment]
Never did anything about this... and I think the problem has diminished with the new Rebus, because Rebus2 (versions 0.90.* an on) has better nuspecs, which means that some version tolerance is added for most dependencies.

ATM in Rabbit's case, Rebus depends on versions `[3.5, 3.6)` thus allowing any version within that range. If it's not OK, we should talk some more about this :)
