### ISSUE TITLE
Fix AmbientTransactionContext lifetime management

### ISSUE THREAD

**Issue by jasperdk** [rebus-org/Rebus#230]
Running in non-HTTP and non-WCF contexts uses a ThreadStatic variable to manage the lifetime of TransactionContext but the cleanup in AmbientTransactionContext is not executed in the that thread when enlisted in a DTC transaction.

I suggest to let the IoC-Container manage the TransactionContext lifetime by adding stuff to the ContainerAdapter. Doing that could make RebusHttpContext and RebusOperationContext obsolete and also opens up for support of distributed transactions in other hosting scenarios e.g. selfhosted Web Api

**Comment by mookid8000** [comment]
this is most likely due to the crappy fact that `TransactionScope` does not flow with the _logical execution context_ by default, it's bound to the ("physical") thread

(unless you're on .NET 4.5.1 and you use the ctor overload that accepts `TransactionScopeAsyncFlowOptions.Enabled`)

this will not be a problem in Rebus2
