### ISSUE TITLE
Serialization problems in TimeoutReplyHandler (Custom message serialization)

### ISSUE THREAD

**Issue by AGiorgetti** [rebus-org/Rebus#284]
Hello, I'd have to say that this issue #182 is causing some troubles to me too, 
As Andrea I also had to implement my version of a CustomJsonMessageSerializer to hace access to the internal JsonSerializerSettings.

Now the problem is another component: TimeoutReplyHandler  which is used to manage the delayed messages. 
This handler does message serialization and deserialization on its own terms, which is totally unrelated to what the ISerializeMessages (JsonMessageSerializer/BinaryMessageSerializer) does (so switching to binary serialization to solve the problem is not an option, because TimeoutReplyHandler is fixed on using json serialization).
Even worse, the component is not easily replaceable as the ISerializeMessages is: it has static methods that are used to serialize messages in the CustomData property of a TimeoutRequest message.

There should be a way for the message serialization to be managed the same way by both these components (or any other component that serializes the message itself), or have a way to replace the TimeoutReplyHandler with a custom implementation we can keep in sync with the JsonMessageSerializer of choice.

**Comment by mookid8000** [comment]
I've never actually paid that much attention to the serialization aspect of Rebus because I usually default to using JSON serialization all over.

I can see that there's a problem with the timeout manager though, which effectively forces everyone to use the built-in JSON serializer - which is kind of silly, because the [TimeoutRequest](https://github.com/rebus-org/Rebus/blob/master/src/Rebus/Messages/TimeoutRequest.cs) and [TimeoutReply](https://github.com/rebus-org/Rebus/blob/master/src/Rebus/Messages/TimeoutReply.cs) could easily have been replaced by the real message (serialized with whatever serializer the user is using) and a few headers for the timeout delay and correlation information.

I'm closing this one now, moving the discussino to #286 (which is a change this will solve this issue)

**Comment by andreabalducci** [comment]
Agree. We had to cut off the original timeouthandler with a custom IInspectHandlerPipeline and add back our handler with the proper serializer to avoid deserialization issues.
