### ISSUE TITLE
IErrorTracker can't be implemented with internal PoisonMessageInfo constructor

### ISSUE THREAD

**Issue by bchavez** [rebus-org/Rebus#287]
Hi,

First off, Rebus has been an absolute joy to work with. Everything is very well thought out. Thank you. :+1: .

I did come across one small issue: I'm trying to implement a custom `IErrorTracker`. However, I got down to the part where I've needed to implement `GetPoisonMessageInfo`:

        public PoisonMessageInfo GetPoisonMessageInfo(string id)
        {
            return null;
        }

Currently, there's no way to create an `PoisonMessageInfo` because the constructor is internal.

My main reason for creating my custom error tracker is to deal with a possible problem with distributed competing consumers running on different compute nodes. Each node will compete for messages by pulling messages from a NoSQL store. The current `ErrorTracker` uses a `ConcurrentDictionary`local to a running in a process. Since worker processes are running on different compute nodes, error tracking is not shared. So I have a needed to push the error tracking state into the (wrapped) transport message itself otherwise there is a potential to have a message bounce around different compute nodes (worst case) `N x 5` retries on an exception.

I can submit a pull-request to get `PoisonMessageInfo` a public constructor. Let me know.

Thanks,
Brian

**Comment by mookid8000** [comment]
oh, I see - that's definitely not intentional, the ctor should be public.

I'm not sure your approach can work though, because the queue transaction is rolled back when an error occurs - therefore, the message will look the same when you see it again.

I've sometimes thought about implementing a "distributed error tracker" of sorts, one what could keep track of retries in a shared database - I've just never actually needed it because retries were infrequent, so even though I may have been processing messages in several nodes I've basically just tolerated the risk that `N x 5` retries could occur.

I think the best solution is to keep track of retries in a shared database - something like Redis or MongoDB comes to mind, because they both support lightweight server-side operations like "increment this number and append this string" and data expiration.

How does that sound to you?

**Comment by mookid8000** [comment]
and now I re-read what you wrote - what kind of NoSQL store are you using? Did you implement your own Rebus transport for that?

**Comment by bchavez** [comment]
Hi @mookid8000 ,

Yes, I've implemented my own Rebus transport for [`Couchbase`](http://www.couchbase.com) using a [`View Index`](http://docs.couchbase.com/admin/admin/Views/views-intro.html). I have another implementation using `N1QL` also but `N1QL` is still in Developer Preview and decided to use a `View Index` to minimize the moving parts. Yeah, since I have my own transport, I have control over the transaction rollback in the transport so I can write-back the wrapped message back to the datastore (with error tracking) if necessary.

Transcode message is received from Rebus and a video upload is retrieved from a distributed file store and transcode begins. It's bit of a heavy work load; so I'm kinda trying to be cautious of the `N x 5` issue. I thought about getting an error count inside the message handler, then throw a light-weight exception, but kinda felt hackish doing error handling that way.

I do like your solution of using a "singular" datastore instead of storing the error tracking *with* the message. A new error tracking document with a key formatted with "rebus:errortracking:msgId" and a document TTL for cleanup would work nicely as well. I'll investigate this solution too.

Re: Public .ctor on `PoisonMessageInfo`
I'll send a pull request to open up `PoisonMessageInfo` if that's okay! :)

Thanks,
Brian

**Comment by mookid8000** [comment]
Wow, that sounds pretty cool!
PR is most welcome :)
