### ISSUE TITLE
Property being Serailized when it shouldn't be

### ISSUE THREAD

**Issue by joshua5822** [rebus-org/Rebus#297]
I have a problem where a property that I have marked with JsonIgnore is still being serialized by the json serializer. Is there some other attribute I should use, so that the property is not serialized? When I try using the newtonsoft json serializer myself I have no issues.

**Comment by mookid8000** [comment]
It's because Rebus' internal serializer (which happens to be based on Newtonsoft JSON.NET) is merged into the Rebus.dll, and thus you'd have to use the `[JsonIgnore]` attribute that's inside Rebus - which you obviously can't because it's private.

The reason why it's merged and private, is that that doesn't interfere with other versions of the library etc. while still providing the ability to do JSON serialization out of the box. This is one of the core principles of Rebus: The core DLL has no dependencies that can cause conflicts.

If you're interested in being able to customize the serialization process, I suggest you create your own implementation of `ISerializeMessages` (grab the code [from the existing implementation](https://github.com/rebus-org/Rebus/blob/master/src/Rebus/Serialization/Json/JsonMessageSerializer.cs)) and then let the used `JsonSerializerSettings` be customizable.

**Comment by joshua5822** [comment]
Thanks, I wasn't sure if that was the route to go.

**Comment by mookid8000** [comment]
If you're in for it, you can add it as a Rebus.NewtonSoft.Json integration project - it would actually be pretty nifty if you could go

    var myFunkySerializerSettings = new JsonSerializerSettings {
        // ...
    };

    Configure.With(..)
         .Serailization(s => s.UseNewtonSoftJsonSerializer(myFunkySerializerSettings))
         .(...)

if you have special serializer needs - I'll happily do the required NuGet song&dance if you send a PR with the project.

**Comment by joshua5822** [comment]
I'll look into it.

**Comment by joshua5822** [comment]
Should the NewtonSoftJsonMessageSerializer use the NonDefaultSerializationBinder class as well as be capable of using JsonSerializationOptions like the JsonMessageSerializer?

**Comment by mookid8000** [comment]
No, that's not necessary - [`NonDefaultSerializationBinder`](https://github.com/rebus-org/Rebus/blob/master/src/Rebus/Serialization/Json/JsonMessageSerializer.cs#L186) is just a serializer-agnostic way of giving the user ability to map types to names and back, which can easily be done by setting a new binder on the `JsonSerializerSettings`.

You would get all the flixibility (as well as the ability to use an updated version of JSON.NET) with these two options:

    Configure.With(..)
        .Serialization(s => s.UseNewtonSoftJsonSerializer())
        .(...)

for default JSON.NET settings, and

    Configure.With(..)
        .Serialization(s => s.UseNewtonSoftJsonSerializer(myFunkySerializerSettings))
        .(...)

for customized settings.

**Comment by mookid8000** [comment]
One thing, though: I set `TypeNameHandling` to `All` in order to provide full .NET type information in the serialized objects. This means that every single JSON object has a `$type` property with the assembly-qualified name of the serialized type, allowing for proper deserialization of e.g. inherited types.

There is one important caveat, though: The root message type can't be properly deserialized without knowing which type to deserialize to.

Therefore, I think you should insert a header into the transport message with the assembly-qualified name of the serialized type, which you should use to deserialize into the proper type in the other end.

You might have figured this out already, I just thought I should direct your attention towards this issue in case you hadn't :)

**Comment by joshua5822** [comment]
Due to the way you have Newtonsoft merged in I don't think I can test properly if my change works for me. I tried just referencing the dll's my copy generated and it worked using both JsonMessageSerializer and NewtonSoftJsonSerializer. Is there a way for me to deploy it locally in the same way as you do? I noticed the build.proj, but I wasn't sure if that was what I wanted or what to do with it.

**Comment by mookid8000** [comment]
yes sure, if you add the project file to [the list of projects to be built](https://github.com/rebus-org/Rebus/blob/master/scripts/build.proj#L7) and create a nuspec file in [the scripts directory](https://github.com/rebus-org/Rebus/tree/master/scripts) (just copy and adapt one of the existing files), you should be able to build a set of NuGet packages by invoking build.bat at the root of the repository with a version to be built, e.g. like so:

    build.bat 0.79.1

which will generate a proper set of release-mode packages in the [/deploy/NET45] folder. You could then bring in the packages into a test application (possibly by adding a local path as a package source), and see if it works as it should.

I'd be happy to help with this part though, so if you've got the project ready you can also just send me a PR and I'll make sure everything is peachy.

**Comment by joshua5822** [comment]
I created a pull request
https://github.com/rebus-org/Rebus/pull/299
