### ISSUE TITLE
RabbitMq Tests

### ISSUE THREAD

**Issue by gertjvr** [rebus-org/Rebus#323]
Wrote a simple example to use Rebus.Rabbitmq, notice that all message that where sent alos ended in the error queue.

Ran the RabbitMq.Tests and the same thing happened.

**Comment by mookid8000** [comment]
why did they end up in the error queue? you should have seen a bunch of stack traces for all of the failed delivery attempts...

**Comment by mookid8000** [comment]
I just found out that the Rebus.RabbitMq packakge would not readily work because NuGet defaults to including the lowest version of each dependency (which is RabbitMq.Client 3.5.0), and Rebus.RabbitMq is built against RabbitMq.Client 3.5.4.

One solution is to `update-package rabbitmq.client` - another is to update your Rebus packages to 0.92.1 because I have fixed it there (Rebus.RabbitMq now explicitly depends on version 3.5.4 of the driver)

Please re-open the issue if that did not fix your problems :)

**Comment by gertjvr** [comment]
I was testing 0.92.0 and the RabbitMq.Client was 3.5.4, there wasn't any failed delivery attempts which was weird. 

I have updated to the latest version and still has the same behavior running tests or my example below

Rebus 0.92.1
RabbitMQ 3.5.4
Erlang 18.0

Linqpad example
http://share.linqpad.net/6wqliq.linq

Seq events doesn't show any failed delivery attempts.
http://i.imgur.com/OuKvQFO.png

This is an image from my rabbitmq queue showing 1 message in the error queue..
http://i.imgur.com/WGAuBky.png

**Comment by mookid8000** [comment]
I copied your code (but left out the Serilog/Seq stuff) - got this:
![image](https://cloud.githubusercontent.com/assets/32968/9218356/175c743c-40d2-11e5-8a22-2e61cfe70638.png)

**Comment by mookid8000** [comment]
ah sorry! I've figured it out, it's a BUG in the RabbitMQ transport that creates wrong queue bindings........ I've fixed it in 0.92.2

you can spot the error by checking the bindings on each queue in Rabbit - in my case, when I go to the error queue, I have this binding:

![image](https://cloud.githubusercontent.com/assets/32968/9218453/f6288b92-40d2-11e5-9298-c6afb3e0af3c.png)

which is wrong, because Rebus _should_ have created a default binding for each queue from a topic with the same name, but it would always use the input queue's topic

Solution: Unbind your bindings and update to 0.92.2

**Comment by mookid8000** [comment]
thanks for reporting the issue btw :+1: that was a pretty bad error  :scream: :laughing:

**Comment by gertjvr** [comment]
Thought it might be something with the bindings, happy you found the error!
