### ISSUE TITLE
Bring back ability to configure queue polling backoff strategy

### ISSUE THREAD

**Issue by darilek** [rebus-org/Rebus#343]
Please add back ability to configure queue polling backoff strategy :-)

I'm using Sql server transport and I would like apply old behavior when ReBus consumers poll the database for messages in two modes. Fast if messages are present and slower if none are available for a period of time.

The new (beta) version polls DB in short intervals (200ms)

**Comment by mookid8000** [comment]
oh sorry, I forgot about that! it'll be available soon, I promise :)

**Comment by mookid8000** [comment]
In 0.98.7 which will be out later today, you can

    var goodTimes = new [] {
        TimeSpan.FromSeconds(0.2),
        TimeSpan.FromSeconds(0.5),
        TimeSpan.FromSeconds(1),
        TimeSpan.FromSeconds(5),
    };

    Configure.With(...)
        .(...)
        .Options(o => o.SetBackoffTimes(goodTimes))
        .(...)

in order to configure the backoff times used during the seconds after becoming idle - in this case, queues will be polled at 0.2s interval the first second after becoming idle, followed by 0.5s poll interval the next second, and so on. The last entry in the backoff times sequence will be used from eternity thereafter (or until the next message is received ;))

**Comment by darilek** [comment]
nice ... many thanks. Keep up good work :-)
