### ISSUE TITLE
Create signed version of assembly

### ISSUE THREAD

**Issue by darilek** [rebus-org/Rebus#344]
Create signed version of Rebus. Because main Rebus assembly has no outer dependecies (NewtonSoft.Json is already merged to main assembly) it should not be a problem

**Comment by mookid8000** [comment]
what would be the benefit of strong-naming the Rebus.dll?

**Comment by darilek** [comment]
Generally - in projects, where strong-namings is used, it is impossible reference unsigned assemblies. Currently I'm using ILDASM/ILASM to recompile Rebus assembly with own key.

**Comment by mookid8000** [comment]
I'll have to know more about this before I start signing the Rebus DLL(s).

Is there really no downside to signing the DLL when it has no dependencies?

Can applications that depend on Rebus.dll do an in-place update of the assembly?

Why do other library authors sometimes provide a set of signed assemblies "on the side"? (e.g. like StructureMap - it has both [normal](https://www.nuget.org/packages/structuremap/3.1.6.186) and [signed](https://www.nuget.org/packages/structuremap-signed/3.1.6.191) versions)

**Comment by darilek** [comment]
As far as I know, load unsigned assembly to signed one is possible only by reflection API (LoadAssembly). 

Signed assemblies can be installed to GAC, has stronger version verification and mainly gives unique information about publisher (can not be tampered)

Therefore some authors provides two versions - for using their assemblies in both enviroments (signed / unsinged).

IMHO you can still continue publish unsigned version on nuget, just add option to build signed assembly from source code.

In our projects we are using combination AssemblyInfo.cs file linked over all projects and some compilation directives

I can try prepare pull request fore review with these changes.

**Comment by rpenha** [comment]
I'm sure that there are no downside signing the assemblies. But if they aren't signed, they can't be referenced by a signed assembly and this is the reason I am almost quiting using Rebus.

**Comment by gertjvr** [comment]
http://strongnamingconsideredharmful.com/

**Comment by gertjvr** [comment]
This argument about strong naming has been going around in multiple forms for many years, it unfair burned to place on library authors

**Comment by zabulus** [comment]
Here is workaround:
https://www.nuget.org/packages/StrongNamer/
Just add the package to a project

**Comment by mookid8000** [comment]
@zabulus cool! :metal: I'll point to that if I ever hear about anyone with this sad requirement again.

**Comment by mookid8000** [comment]
I have a deeply felt resistance against strong-naming myself because I have had bad experiences with it in the past. IIRC these experiences came from not being able to update assemblies, not working at all with NuGet, etc etc etc. 

However, my memories of these things are so far away in the past that I cannot recall exactly what snagged me - I just know that my life has been Good And Simple for the last 4 years where I have been fortunate enough to not have to strong-name anything.

I have had VERY few people asking me to strong-name Rebus over the years, so it does not seem to me that it is an actual problem that I chose not to.

If people are unfortunate and have to work in an environment where strong-naming is a requirement, I suggest you take a look at [StrongNamer](https://www.nuget.org/packages/StrongNamer/) as suggested by @zabulus .

I am closing this issue now 😄

**Comment by rpenha** [comment]
Thank you fellas! I will use Strong Namer. Rebus addresses a lot of challenges that I am facing today and I really hate the signed projects that were developed in the company I work today. Again, thank you so much!

**Comment by vdachev** [comment]
Please, refer to [Microsoft docs](https://docs.microsoft.com/en-us/dotnet/standard/assembly/strong-named#why-strong-name-your-assemblies) for the benefits for strong-naming of assemblies. It is indeed [recommended](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming#create-strong-named-net-libraries) by Microsoft to strongly sign assemblies, especially for OSS projects. I guess that's why the website [mentioner previously](https://github.com/rebus-org/Rebus/issues/344#issuecomment-217323124) no longer exists.

In more practical terms, there are many solutions that use strong signing in order to guarantee consistency of the assembly references and to actually prevent drop-in replacement, unless you need to be able to replace a DLL with a one of a completely different version (which in proper semver versioning could cause a runtime error).

Using "Strong Namer" on the other hand slows down the build of solutions with lots of multiple references.

Therefore, I would be glad if you could reconsider your decision to close this issue.

**Comment by mookid8000** [comment]
Hi @vdachev , it seems to me strong-naming is mostly about enabling registration in the GAC, which is something no one should ever do with Rebus. 

Is there something else you feel prevented from doing because Rebus’ assemblies are not strong-named?

**Comment by Fabsky** [comment]
Hi @mookid8000 , I just get this "issue".
I really don't understand why there is some resistance about strong-naming de dll ? this has no impact, and doesn't cost any money. Just adding a SNK file to a build. Most nuget package have strong named dll.

But anyway that's your choice and I respect. I've tested StrongNamer and it works, I didn't know this package so I learned something new 👍 
Thank you for your work in Rebus 🥇

**Comment by vdachev** [comment]
> Is there something else you feel prevented from doing because Rebus’ assemblies are not strong-named?

Hi @mookid8000 , the solutions we use Rebus consist of multiple projects from several repositories, so have lots of referenced assemblies and we want to prevent assembly conflicts. So our projects are strongly named.

However, this prevents us from Rebus as-is and we have to slow down our builds and reference additional components just to have Rebus strongly named.

**Comment by mookid8000** [comment]
> (we) have lots of referenced assemblies and we want to prevent assembly conflicts. So our projects are strongly named

How does strong-naming help with avoiding assembly conflicts?

**Comment by vdachev** [comment]
The identity of a a strongly named assembly includes the version so referencing it prevents the use of a different version of the assembly. From what I understand, it also enables loading different versions of the same assembly side-by-side, which comes in handy when your code references assembly A and assembly B but assembly B also references a different version of assembly A.

Actually, [Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming) advises the use of strong naming when targeting .NET Framework 4.5, .NET, .NET Core, Xamarin, etc since [enhanced string naming](https://docs.microsoft.com/en-us/dotnet/standard/assembly/enhanced-strong-naming#limitations-of-conventional-strong-names) was introduced.
