### ISSUE TITLE
UseMsmqAndGetInputQueueNameFromAppConfig?

### ISSUE THREAD

**Issue by donig** [rebus-org/Rebus#353]
There are several cases in the documentation that mention UseMsmqAndGetInputQueueNameFromAppConfig as in:

https://github.com/rebus-org/Rebus/wiki/Transport

but that doesn't seem to be in the latest Rebus 2 code. How is this supposed to be configured in Rebus 2? Is it something like:

            Configure.With(adapter)
                .Transport(t => t.UseMsmq(null))
                .Routing(r => r.TypeBasedRoutingFromAppConfig())
                .Start();

**Comment by mookid8000** [comment]
Thanks for pointing it out!

Unfortunately, almost none of the XML configuration capabilities from Rebus 1 have been ported to Rebus 2, mostly because I intend to make Rebus 2 available on DNX and thus cannot rely on `ConfigurationManager` to be there, but also because I almost always end up having several endpoints in my processes and therefore cannot reallly use XML configuration of an endpoint.

I see you've found the XML-based endpoint mappings configurer :) that's the only thing in Rebus 2 that looks into app.config.

For now, I suggest you wrap calls to `ConfigurationManager.AppSettings[someKey]` in a static method somewhere, e.g. on a `Config` class, allowing you to do something like this:

    Configure.With(adapter)
        .Transport(t => t.UseMsmq(Config.AppSetting("inputQueueName")))
        .Routing(r => r.TypeBasedRoutingFromAppConfig())
        .(...)

**Comment by mookid8000** [comment]
I've updated the wiki page btw to reflect the current options with Rebus 2 - it might change some time in the future when I get the time to look into porting Rebus 2 to DNX.
