### ISSUE TITLE
How exactly does the new logging injection work?

### ISSUE THREAD

**Issue by dkr88** [rebus-org/Rebus#355]
I cannot for the life of me figure out how to configure logging in the latest releases...

With the "old" way, 

... RebusConfigurer.Logging(l => l.NLog()) ..
and in the handlers,
.. RebusLoggerFactory.Changed += f => Log = f.GetCurrentClassLogger(); ...

I now only get a Rebus ConsoleLogger and not my configured NLog logger.

I thought maybe the new way was to receive an IRebusLoggerFactory as a dependency, but there is no such component registered with the container and so Rebus can no longer resolve any of my handlers.

So what is the proper way to use NLog now?

**Comment by mookid8000** [comment]
Well... I moved away from the global static logger thingie in order to support e.g. hosting multiple Rebus endpoints within the same process, where each endpoint can use a [Serilog event enricher](https://github.com/serilog/serilog/wiki/Enrichment) to enrich logged events with information that is special for that particular endpoint.

I didn't think that the funny `RebusLoggerFactory.Changed` would be used in "user code" like that, but I can see why that has happened.

For now, you can manually set `RebusLoggerFactory.Current` to Rebus' NLog logger factory when your application starts.

In the future, I suggest you use NLog directly - if I recall correctly you can

    static readonly ILogger = LogManager.GetCurrentClassLogger();

with NLog at the top of your class, making for a much cleaner experience than the Rebus logger initializer.

**Comment by mookid8000** [comment]
I don't think I ever advised anyone to use Rebus' logging mechanis for their own code, but in case I did it anyway or somehow insinuated via vague documentation or anything, I apologize! :smiling_imp: 

My own approach to logging (which I think work pretty well) is to pull in whichever logging library I want into my application. At the moment I use [Serilog](https://github.com/serilog/serilog) for everything.

I even pull the core logging library into my innermost domain projects! :scream: which is pretty useful, because then I can log stuff from anywhere I want.

Logging libraries usually provide so much flexibility that this is never a problem. I can even make Serilog log to an NLog appender if I need to some time down the road :stuck_out_tongue_winking_eye: 

With this outset, only thing left is to make the libraries and frameworks I use log to the same target - that's where I would configure Rebus to use Serilog too, and Topshelf, and maybe other stuff too.

This is the approach I recommend you use.

**Comment by mookid8000** [comment]
oh btw - the new logging injection works with everything that is registered in ["the injectionist"](https://github.com/mookid8000/Injectionist), which is the IoC-like container that Rebus uses behind the scenes in the configuration builder to gradually build its configuration.

An example on how this could look could be e.g. [Rebus' idempotent sagas extension](https://github.com/rebus-org/Rebus/blob/master/Rebus/Sagas/Idempotent/IdempotentSagaConfigurationExtensions.cs), where the `IdempotentSagaIncomingStep` needs to log stuff and therefore gets a `IRebusLoggerFactory` injected.

**Comment by dkr88** [comment]
Thanks for the feedback! Not sure how I missed the injectionist stuff, but that solves the issue with logging in my custom persistence implementation.

And I was using Rebus' logging stuff in my endpoints... but I will stop that now :smile:

**Comment by mookid8000** [comment]
:+1: 

I should probably write a piece on the wiki about logging with Rebus some time in the future
