### ISSUE TITLE
Message Dispatch Issue related with WindsorContainerAdapter or BuiltInAdapterContainer

### ISSUE THREAD

**Issue by Uma19** [rebus-org/Rebus#380]
Hi Guys :

We are facing some issue when rebus is trying to dispatch the message.And this issue occurs sometimes.
Exception details are as follows :
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Rebus.UnhandledMessageException: Could not find any handlers to execute message of type.
   at Rebus.Bus.Dispatcher.Dispatch[TMessage](TMessage message)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Rebus.Bus.Worker.DoTry()
   at Rebus.Bus.Worker.TryProcessIncomingMessage()
   at Rebus.Bus.Worker.MainLoop()

We are using WindsorContainerAdapter container and the configuration for the bus are as follows :

  Bus = Configure.With(new WindsorContainerAdapter(container))
              .Serialization(x => x.UseJsonSerializer())
              .Transport(t => t.UseMsmqAndGetInputQueueNameFromAppConfig())
              .MessageOwnership(m => m.FromRebusConfigurationSection())
              .Sagas(m => m.StoreInMemory())
              .Subscriptions(m => m.StoreInMemory())
              .Timeouts(m => m.StoreInMemory())

Can you provide us the direction where we can further investigate this issue ?

**Comment by mookid8000** [comment]
The exception comes when Rebus cannot fint any handlers to execute for the given incoming message (which has been successfully deserialized and everything, and is ready to be dispatched).

If you _know_ that the container has your handler registered as the proper `IHandleMessages<TheIncomingMessage>`, it is most likely because Windsor silently ignores resolution errors when calling `ResolveAll<TService>` (which is what Rebus does to resolve the handler instances), so you should probably check if your handler's dependencies are properly set up in the container as well.

During development, it can sometimes be beneficial to have something like this execute during startup:

    // for each type of message that we want to handle
    var handlers = container.ResolveAll<IHandleMessages<ImportantMessage>>();

    if (!handlers.Any()) 
    {
        throw new ApplicationException($"Could not get any handlers for 'ImportantMessage'");
    }
