### ISSUE TITLE
"How To Create a Message" Documentation

### ISSUE THREAD

**Issue by paulmarshall** [rebus-org/Rebus#383]
I can't easily find any documentation as to how to create a simple bespoke message

**Comment by mookid8000** [comment]
I've added a [page about 'Messages' on the wiki](https://github.com/rebus-org/Rebus/wiki/Messages) just now :smiley: 

Is there any information you're particularly looking for?

**Comment by paulmarshall** [comment]
Let me give you a concrete example....

I want to wait for a file to appear in a folder. The file contains multiple bank transactions that I want to reconcile - the transactions are in a specific vendor format.
When the file appears, I want to read the contents of the file, create an event (containing the contents) and publish the event "BankFeed1DataReceived" (to a MSMQ). This is an example of a "channel adapter". For this example, this adapter runs in a simple console (but that's not really important).

Next, I want a separate process to "subscribe" to this event, read the contents (of the file) and transform the contents into an agnostic format (a "normalizer" adapter).

I have two consoles and a separate class library - the library defines the event.

So my question is, does my event/message have to derive from some marker interface or be marked as being serialisable etc in order to "play" with Rebus.

Here is an example of the code for the "file watcher" bit....

```
  class Program
  {
    const string TransformQueueName = "transform";

    static void Main(string[] args)
    {
      var path = args.Length>0 ? args[0] : "";

      using (var activator = new BuiltinHandlerActivator())
      {
        Configure.With(activator)
            .Transport(t => t.UseMsmq(TransformQueueName))
            .Routing(r => r.TypeBased().Map<BankFeed1DataReceived>(TransformQueueName))
            .Start();

        var fsw = new System.IO.FileSystemWatcher(path);
        fsw.EnableRaisingEvents = true;
        fsw.Created += delegate(object sender, System.IO.FileSystemEventArgs e)
        {
          if (e.ChangeType == System.IO.WatcherChangeTypes.Created)
          {
            var contents = System.IO.File.ReadAllText(e.FullPath);
            activator.Bus.Publish(new BankFeed1DataReceived { Contents = contents }); 
          }
        };
          
        Console.WriteLine("Press enter to quit");
        Console.ReadLine();
      }
    }
  }
```

Here is the transformer bit:
```
  class Program
  {
    const string TransformQueueName = "transform";

    static void Main(string[] args)
    {
      using (var activator = new BuiltinHandlerActivator())
      {
        activator.Register(() => new TransformBankFeed1());

        Configure.With(activator)
            .Transport(t => t.UseMsmq(TransformQueueName))
            .Routing(r => r.TypeBased().Map<BankFeed1DataReceived>(TransformQueueName))
          //.Options(b => b.EnableMessageAuditing(AuditQueueName))
            .Start();

        Console.WriteLine("Press enter to quit");
        Console.ReadLine();
      }
    }

    public class TransformBankFeed1 : IHandleMessages<BankFeed1DataReceived>
    {
      public async Task Handle(BankFeed1DataReceived bankFeed1)
      {
        Console.WriteLine(bankFeed1.Contents);
      }
    }
```

**Comment by mookid8000** [comment]
> So my question is, does my event/message have to derive from some marker interface or be marked as being serialisable etc in order to "play" with Rebus.

No need to do anything :) you can publish `BankFeed1DataReceived`, it just needs to be JSON-serializable (i.e. either have publish get/set properties or have constructor parameters that match up with the properties). There's more details [here](https://github.com/rebus-org/Rebus/wiki/Messages).

**Comment by mookid8000** [comment]
Just a thing - this line:

    activator.Bus.Publish(new BankFeed1DataReceived { Contents = contents }); 

needs to be changed into

    activator.Bus.Publish(new BankFeed1DataReceived { Contents = contents }).Wait(); 

Notice the `.Wait()` at the end? That will wait for the asynchronous operation to complete before returning, allowing you to be sure also that the message was actually published.

**Comment by paulmarshall** [comment]
Sorry, missed the Wait method.

I'm missing something....when I run the file watcher console, I get the following output when I present a file into the watched folder:

```
Rebus.Routing.TypeBased.TypeBasedRouter INFO (Thread #9): Mapped Rebus.Common.Messages.BankFeed1DataReceived -> transform
Rebus.Transport.Msmq.MsmqTransport INFO (Thread #9): Initializing MSMQ transport - input queue: 'transform@00-00-00-00-00-'
Rebus.Threading.TaskParallelLibrary.TplAsyncTask INFO (Thread #9): Starting periodic task 'CleanupTrackedErrors' with interval 00:01:00
Rebus.Threading.TaskParallelLibrary.TplAsyncTask INFO (Thread #9): Starting periodic task 'DueMessagesSender' with interval 00:00:01
Rebus.Bus.RebusBus INFO (Thread #9): Starting bus 1
Rebus.Bus.RebusBus INFO (Thread #9): Setting number of workers to 1
Rebus.Bus.RebusBus DEBUG (Thread #9): Adding worker Rebus 1 worker 1
Rebus.Bus.RebusBus INFO (Thread #9): Started
Press enter to quit
Rebus.Workers.ThreadBased.ThreadWorker DEBUG (Rebus 1 worker 1): Starting (thread-based) worker Rebus 1 worker 1
Rebus.Pipeline.Send.SendOutgoingMessageStep DEBUG (Thread #16): Sending Rebus.Common.Messages.BankFeed1DataReceived -> <no destinations>
```

The key here is <no destinations>.

I'm assuming my setup will publish the event  onto the "transform" queue in the file watcher process and subscribe/handle the event in the transform process....but the subscription doesn't work. 

Any ideas?

**Comment by mookid8000** [comment]
Ah - this line says it all:

    Sending Rebus.Common.Messages.BankFeed1DataReceived -> <no destinations>

Notice the `<no destinations>` part? :)

Someone else needs to subscribe to this message.

If there will only ever be exactly 1 recipient of this message, you could also just `bus.Send` it - do to that, you do this:

    bus.Send(new BankFeed1DataReceived { Contents = contents }).Wait();

and then you use "endpoint mappings" as described on the [Routing](https://github.com/rebus-org/Rebus/wiki/Routing) page to determine the message's destination:

    Configure.With(...)
        .(...)
        .Routing(r => r.TypeBased().Map<BankFeed1DataReceived>("transform"))
        .(...)

assuming that you have a Rebus endpoint with `transform` as its input queue.

**Comment by mookid8000** [comment]
If you want to pub/sub, I suggest you read the [page about the subscription storage](https://github.com/rebus-org/Rebus/wiki/ISubscriptionStorage), because the publisher will need some persistent way of saving information about which queues to deliver published messages to.

**Comment by paulmarshall** [comment]
> Someone else needs to subscribe to this message.

They are, just not in the same process. I want to be able to "fire and forget".....publish the event into the queue....and forget about it.....and in a separate "consumer" (or "competing consumer") listen for messages, thereby decoupling "adapters".

Is this possible?

**Comment by mookid8000** [comment]
All messaging with Rebus is "fire and forget".

The "types" of messaging that you can do with Rebus is divided into two basic scenarios:

1. `Send` a message - which can be a **command** (i.e. purely one-way), or a **request** (to which it would be natural for the recipient to `Reply` to)
1. `Publish` an **event**

The first thing is what you do if you want **exactly one recipient** for the message.

The other thing is what you do if the publisher basically does not care whether anyone is listening, because then there will be **zero to infinite** recipients, depending on how many endpoints have subscribed.

Based on what I have heard so far about your requirements, it sounds to me like you want to `Send` the message to one specific queue - and then you can have multiple processes consuming messages off of that queue (although that does not scale that well if you're using MSMQ).

**Comment by paulmarshall** [comment]
I changed the file watcher to ```Send``` and got the following:

- The file watcher process (the "publisher") then reported the following warning:
```
Rebus.Retry.ErrorTracking.InMemErrorTracker WARN (Rebus 1 worker 1): Unhandled e
xception 1 while handling message with ID 7ebd5b60-5882-4077-81cd-415d6a69e6c5:
Rebus.Exceptions.RebusApplicationException: Message with ID 7ebd5b60-5882-4077-81cd-415d6a69e6c5 and type Rebus.Common.Messages.BankFeed1DataReceived, Rebus.Common could not be dispatched to any handlers
```

- The transformer process (the "subscriber") then handled the message (by displaying the contents to the console)

So, sort of a success :-)

Final thing, how do I prevent the publisher from throwing a warning during ```Send``` if no handlers (within the process) have been set up to handle the message?

 but the only thing missing is ensuring the file watcher sends a command (one-way) and not worry that no handlers

**Comment by mookid8000** [comment]
> how do I prevent the publisher from throwing a warning during Send if no handlers (within the process) have been set up to handle the message?

It is assumed that you care about the message and don't want to risk losing it if you accidentally send it to an endpoint that does not have a handler for it. Therefore, if the receiver does not have a handler for it, the message will be moved to the error queue. It can then be retried later, or moved to another queue if the recipient was the wrong one.

> but the only thing missing is ensuring the file watcher sends a command (one-way) and not worry that no handlers

In your case, I would probably design the solution so that one process watches the directory and does a `bus.Send` whenever it detects a change. This could be designed in a generic fashion, basically allowing this process to never ever have to be restarted, which will reduce the risk that it misses a change in the directory it is watching.

In another process (possibly multiple processes) you then process the sent messages. You can shut down the processor at anytime to be updated etc. and messages will just queue up for it to be received when it is ready again.

**Comment by paulmarshall** [comment]
Your understanding of my problem is spot on, as is the solution - its just my understanding of Rebus's capabilities and implementation interpretation that is at fault. Thanks for your guidance.

> It is assumed that you care about the message and don't want to risk losing it if you accidentally send it to an endpoint that does not have a handler for it. Therefore, if the receiver does not have a handler for it, the message will be moved to the error queue.

Can I simply register a "null" handler to avoid this "no handler registered to handle the message" scenario? But in doing so, won't the handler take the message off the queue before the other consuming process have chance to read it?

**Comment by mookid8000** [comment]
No problem :)

> Can I simply register a "null" handler to avoid this "no handler registered to handle the message" scenario? But in doing so, won't the handler take the message off the queue before the other consuming process have chance to read it?

Hmm, I am not sure I understand the problem. In the solution I sketched above, I would either have two queues (e.g. "filewatcher" and "fileprocessor", each identifying the responsibility of the service), or I would have only one queue ("fileprocessor") and then let the watcher process use a [one-way client](https://github.com/rebus-org/Rebus/wiki/Different-bus-modes#configuration-options-and-one-way-clients)(bus client that is not capable of receiving messages) to send the commands.

**Comment by paulmarshall** [comment]
> one-way client

That was the missing piece and it works - awesome !

I'm a big advocate of the book "Enterprise Integration Patterns" so I'm trying to implement some of those patterns using Rebug - but the above has been my only "speed bump".

Thanks for you help - I like the library and would be interested in contributing to the project (to give something back). Get in touch if I can help.

**Comment by mookid8000** [comment]
Good to hear :+1: 

And yes, that book certainly has changed the way I do software :grin: 

Be sure to stick around Rebus here at GitHub and do not hesitate to report any issues and/or suggestions in [the issue tracker](https://github.com/rebus-org/Rebus/issues), which is also where you could go see if something seemed like an interesting task to do.

If you're new to this whole open sourcey thing, I'm trying to keep an [up-for-grabs](http://up-for-grabs.net/) label (are you familiar with that concept?), which is for tasks that are fairly easy and do not require too much knowledge about Rebus. It has [only one single task at the moment](https://github.com/rebus-org/Rebus/issues?q=is%3Aopen+is%3Aissue+label%3Aup-for-grabs) though - for some reason it's hard to keep many unsolved easy tasks open ;)

**Comment by paulmarshall** [comment]
I've got a working spike - great.

The thing that puzzles me about the API is "routing". Look at the following code:

```
  class Program
  {
    static void Main()
    {
      using (var adapter = new BuiltinHandlerActivator())
      {
        adapter.Handle<BankFeed.Common.Messages.NormalisedBankFeed>(async message =>
        {
          Console.WriteLine("Processing bankFeed {0}", message.Id);

          foreach (var transaction in message.BankTransactions)
          {
            Console.WriteLine("{0}, {1}, {2}", transaction.AccountNumber, transaction.Timestamp, transaction.Amount);
          }

          await Task.Delay(200);
        });

        Configure.With(adapter)
            .Logging(l => l.ColoredConsole(LogLevel.Warn))
            .Transport(t => t.UseMsmq("normalisedBankFeed"))
            .Routing(r => r.TypeBased()
                           .Map<BankFeed.Common.Messages.NormalisedBankFeed>("normalisedBankFeed"))
            .Start();

        adapter.Bus.Subscribe<BankFeed.Common.Messages.NormalisedBankFeed>().Wait();

        Console.WriteLine("Consumer listening - press ENTER to quit");
        Console.ReadLine();
      }
    }
  }
```
This is a simple "consumer" process, that simply subscribes to a message being sent to a queue and when received, writes the message to the console.

Simple. But yet the routing configuration of this "receiver" is very similar to the routing configuration of a "sender".

Why not make this distinction explicit?

For example for a "sender" perhaps the configuration API could look like this:
```
.Transport(t=>t.UseMsmq())
.Sending(s=>s.TypeBased()
             .Map<OutgoingMessage>("outgoingChannel"))
```
And for a "receiver", perhaps the configuration API could look like this:
```
.Transport(t=>t.UseMsmq())
.Receive(r=>r.TypeBased()
             .Map<OutgoingMessage>("outgoingChannel"))             
```

Comments welcome :-)

**Comment by mookid8000** [comment]
I realize that the routing part can be kind of funny and esoteric when you first learn about it.

First off, figure out which endpoint depends on which - as in: If the bus with the input queue `normalisedBankFeed` subscribes to the `NormalisedBankFeed` message, _it can be said to have a dependency on whichever service "owns the `NormalisedBankFeed` message type_. In this relationship, the `normalisedBankFeed` is the "client" and whoever publishes the `NormalisedBankFeed` message is the "server".

The concepts "client" and "server" _can_ be a little bit confusing here, but as I see it, it's a matter of determining who depends on who. A "server" is never less important than a "client".

If we are talking about **sending commands or doing request/reply**, the "client" is the one sending the command or the request. This is because it is implied that this endpoint needs to know where to send the command/request (maybe not literally, but the bus needs to know), and thus some kind of "server" needs to be addressable out there.

If we are talking about **publish/subscribe messaging**, the "client" is the subscriber. Again, it's because it is implied that the subscriber needs to know where to subscribe to some particular message type (again not literally, but the bus needs to know), and thus some kind of "server" needs to be addressable out there(*).

*) An exception to this is if your chosen transport supports publishing to topics, like e.g. RabbitMQ and Azure Service Bus do - with these transpors, the transport layer takes care of delivering the message to each subscriber's input queue when you publish it.

hmm, I guess the answer got a little bit out of hand - I'd be happy to explain this in greater detail, I think I might need to write a book some day.

Please keep asking of it still doesn't magically make sense to you :grin:
