### ISSUE TITLE
Is there any wayt to set priority for message in MSMQ?

### ISSUE THREAD

**Issue by alkampfergit** [rebus-org/Rebus#393]
Probably I've not found in the documentation, but I did not find a way to send a message changing priority in Rebus when I'm using MSMQ.

It would be nice to have an extension that looks in the header for a specific value that can set the priority of that specific message in MSMQ.

**Comment by alkampfergit** [comment]
One of the problem implementing that feature could be that is seems that rebus always send message with a transaction, while [MSMQ does not allow priority to be set if you are using transactions])https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/92d2ea87-594c-4f9c-8286-35bf21518002/transactional-priority-msmq-sometime?forum=msmq) (one of the reason why you want to move away from MSMQ) ...

**Comment by mookid8000** [comment]
hmmm, well... MSMQ is the only transport that actually has transactions... I've been contemplating moving to the same model as the other transports by storing outgoing messages in-mem until after the user's code has finished successfully...

do you have any thought on this?

**Comment by alkampfergit** [comment]
It should be an opt-in option. 

To avoid breaking existing code, with standard settings everything works as is now, just add another options for MSMQ configuration that allows users to work with Non transactional Queue.

**Comment by mookid8000** [comment]
Yes, you are right. Current MSMQ users will have transactional queues all over the place.

From the link you sent, it looks like you _can_ send transactional messages with priority - you just have to use the same priority for all of the messages.

If the sent messages were collected inmem, the sending of the outgoing messages after running the user's code could consist of grouping the outgoing messages by priority (without reordering them), and then sending them in one transaction per priority.

**Comment by alkampfergit** [comment]
Sadly enough it is not possible :(, as you can read from [this link](http://microsoft.public.msmq.programming.narkive.com/0Qrq4uDm/always-lowest-priority-when-sending-to-transactional-queue). It is a Design decision for MSMQ, if the queue is transactional, always the message will have priority set to Lowest :(.

I think that the only solution is a configuration for MSMQ that allows the user to opt-in for a non transactional queue, then we can add an header for MSMQ to setup priority of the message :).

Gian Maria.

**Comment by mookid8000** [comment]
I think this modification should start its life in a separate package, and then we can merge the implementations later. I would rather not tamper with the current MSMQ transport.

**Comment by mookid8000** [comment]
I'm thinking that this issue qualifies as "up-for-grabs" because it can be made easily by

- [ ] creating a new class library
- [ ] copying the existing `MsmqTransport` to it
- [ ] create an accompanying test project
- [ ] copy the transport tests (those using `ITransportFactory`) to the test project
- [ ] add new tests to verify that MSMQ message priorities do in fact work (should start out by failing)
- [ ] modify the new `MsmqTransport` as necessary, while preserving the old behavior (enforced by the suite of existing transport tests)

Also I would love to help out with directions and pointers :smile:

**Comment by alkampfergit** [comment]
Ok you suggest creating another transport, ex MsmqNonTransactionalTransport instead of modifiying the old MsmqTransport adding the capability of Non Transactional queue.

It can be probably the best idea, when I'll have some spare time I'll try to sort them out on my forked copy.

Thanks.

**Comment by mookid8000** [comment]
Yes that is what I mean  - and if you would do that, that would be awesome!

**Comment by mookid8000** [comment]
Let me know if you have any doubts

**Comment by Martz94** [comment]
Is this being worked on by anyone or may I take a stab at it?

**Comment by mookid8000** [comment]
As far as I know it is not being worked on.

The checklist pretty much describes what I think it takes to implement this 😄 please let me know if something is not clear.

**Comment by alkampfergit** [comment]
Hi, 

onestly I did not have time to work on this feature, I've had all other types of more urgent work to do :/. 

Maybe next week I'll have a little bit of time for working on it, but I'm not sure :(, sorry.

@Martz94 if you start working on it, it would be awesome. Let me know so we avoid doing duplicate work.

**Comment by Martz94** [comment]
@alkampfergit Yes I will give it a go this week.

**Comment by alkampfergit** [comment]
Thanks a lot.

**Comment by mookid8000** [comment]
I'm closing this one now.... in order to set priority on messages with MSMQ you have to work with non-transactional queues only - but that makes it impossible for Rebus to keep its at-least-once delivery guarantee, because the only way to perform an ACKed receive with MSMQ is to use a `MessageQueueTransaction` (either directly, or implicitly via `TransactionScope`) - but then the queue needs to be transactional again, and then we're back where we started....

😞
