### ISSUE TITLE
CastleWindsor - support constructing a bus that has dependencies

### ISSUE THREAD

**Issue by chilversc** [rebus-org/Rebus#399]
Currently the standard `CastleWindsorAdapter` is awkward to use from an `IWindsorInstaller` if the bus has dependencies that are resolved from the container.

A simple solution would be to register a factory that creates the bus. The factory will be registered by the user in the container. This allows the factory to have dependencies that will be resolved automatically by Castle Windsor.

This would not replace the simple container adapter, allowing users to chose to use either the installer or the container adapter depending on their requirements.

# Implementation

A quick test I created from the 0.84 version.

```csharp
interface IBusBuilder
{
    IBus Build (IContainerAdapter adapter);
}

class RebusWindsorInstaller : IWindsorInstaller
{
    public void Install(IWindsorContainer container, IConfigurationStore store)
    {
        var adapter = new Adapter(container);
            
        container.Register(
            Component.For<IBus>()
                .Named("bus")
                .UsingFactory<IBusBuilder, IBus>(builder => builder.Build(adapter))
                .LifeStyle.Singleton
                .Start(), // this is StartableFacilityRegistrationExtensions.Start
            
            Component.For<IMessageContext>()
                .UsingFactoryMethod(k => MessageContext.GetCurrent(), managedExternally: true)
                .LifestyleTransient());
    }

    private class Adapter : IContainerAdapter
    {
        private readonly IWindsorContainer container;

        public Adapter (IWindsorContainer container)
        {
            this.container = container;
        }

        public IEnumerable<IHandleMessages> GetHandlerInstancesFor<T>()
        {
            IEnumerable<IHandleMessages> handlers = container.ResolveAll<IHandleMessages<T>>();
            IEnumerable<IHandleMessages> asyncHandlers = container.ResolveAll<IHandleMessagesAsync<T>>();
            return handlers.Union(asyncHandlers);
        }

        public void Release(IEnumerable handlerInstances)
        {
            foreach (var handlerInstance in handlerInstances)
            {
                container.Release (handlerInstance);
            }
        }

        public void SaveBusInstances(IBus bus)
        {
            // no-op, bus will be registered by the installer
        }
    }
}
```

This uses the Castle Windsor StartableFacility to automatically start the bus. No special handling is required to dispose of the bus since its now managed by Castle Windsor.

# Usage

```csharp
void Main()
{
    using (var container = new WindsorContainer ()) {
        var start = new StartFlag ();

        // StartableFacility ensures the bus is created when the container
        // has been initialized, this avoids the need to run container.Resove<IBus>()
        container.AddFacility<StartableFacility> (f => f.DeferredStart(start));

        container.Install(FromAssembly.This(), new RebusWindsorInstaller ());

        start.Signal ();
    }
}

public class BusInstaller : IWindsorInstaller
{
    public void Install (IWindsorContainer container, IConfigurationStore store)
    {
        container.Register (
            Component.For<SomeDependency> ()
                .LifeStyle.Singleton,

            // The user must provide an implementation of IBusBuilder
            Component.For<IBusBuilder> ()
                .ImplementedBy<BusBuilder> ()
                .LifeStyle.Singleton);
    }

    class BusBuilder : IBusBuilder
    {
        public BusBuilder(SomeDependency theDependency)
        {
        }
        
        public IBus Build (IContainerAdapter adapter)
        {
            return Configure.With (adapter)
                .Logging (l => l.None ())
                .Transport (t => t.UseMsmqInOneWayClientMode ())
                .MessageOwnership (m => m.FromRebusConfigurationSection())
                .Serialization (s => s.UseJsonSerializer ())
                .Behavior (b => b.SetLowLatencyBackoffBehavior ())
                .CreateBus ()
                .Start ();
        }
    }
}

class SomeDependency
{
}
```

**Comment by mookid8000** [comment]
Well... the `*ContainerAdapter` suite of adapters are mostly there to provide a simple and consistent experience with registering the bus instance in the container, where the general usage pattern in applications usually will be

    static MyContainer _container;

somewhere, and then when the applications starts:

    _container = new MyContainer();

    Configure.With(new MyContainerAdapter(_container))
       .(...)
       .Start();

and then when the application shuts down:

     _container.Dispose();

which will make everything shut down cleanly.

It is intentional that the container instance given to the adapter always gets only two registrations: One that resolves an `IBus`, and one that resolves the current `IMessageContext` (which should throw if called accidentally outside of a message handling context).

If you want the bus' dependencies to be satisfied by the container, I suggest you register `RebusBus` and its dependencies in your container.

Note though that Rebus really has no RR (the Resolve/Release part of [RRR](http://blog.ploeh.dk/2010/09/29/TheRegisterResolveReleasepattern/)) going on anywhere except for message handlers. This means that all dependencies are single instances which are held on to by the `RebusBus` instance.

If you have come up with a superior way of using Rebus with Castle Windsor, I suggest you publish it as a new NuGet package. It's always good with options :smile:
