### ISSUE TITLE
Upgrading databasemodel

### ISSUE THREAD

**Issue by esbenUnipluss** [rebus-org/Rebus#403]
Hi,
We are currently upgrading Rebus (from 0.71.0 to 0.99.24 )

The database model in the two projects differ (0.71.0 version: recipient, seq, priority, label, headers,body) (0.99.24 version: id, recipient, priority, expiration, visible, headers, body)

By using  .Options(o => o.EnableLegacyCompatibility()) and inserting data to the database, works fine. The problem with this is to make sure that no one uses the old database.

Is there a way to use the old database together with the new one?

**Comment by mookid8000** [comment]
Unfortunately, `EnableLegacyCompatibility` is (very) experimental.... and I have no experience with using it myself.

I realize now (as you can see) that there's other issues besides the wire-level format of messages to consider in order to be truly legacy compatible, and even then it's probably only the simplest scenarios that will work.

In your case, you can see that the SQL transport uses different schemas for its messages table. I am afraid that it is not readily possible to use the old schema from the new version of Rebus, so I recommend that you upgrade everything to Rebus 0.99.* at once.
