### ISSUE TITLE
questions for version 'new'

### ISSUE THREAD

**Issue by stevengopmo** [rebus-org/Rebus#408]
Hi,

We have been using Rebus for sometime and we really like it.  We do, however, have a few small issues that we are fighting.  Please can you tell me if the latest version will resolve these.

1.  SimpleInjector - this is our primary IOC container and it just doesn't work well in the old version of Rebus.  Specifically once we call the container for something else, Rebus is still trying to configure it to add a reference to the bus singleton.  We have resorted to using Castle for our services since our web apps are primarily send only anyway but I'd rather we stick with SimpleInjector only.  Do you think you'll have better support for it in the new version?

2.  Publishing - This issue is more important and harder for me to describe as I don't remember all of the history but I'll try to explain.  The basics are, we have a lot of applications that subscribe to some messages but use commands as well.  For some reason (the reasons escape me but perhaps you'll know) we had to setup a separate service that just gets all published messages and forwards them to subscribers.  I think this may be in part because of the SimpleInjector problem mentioned above; our web apps are configured as one way send only and therefore can't publish.  It's possible that if 1 above is solved that this problem goes away.  Anyway I'm sure I'm missing some important aspect here but maybe you can comment anyway?

3.  Retry - Will the next version have a better retry mechanism?  The current version's retry doesn't really allow a pause between retries.  I saw that you put some code that might work on stackoverflow (I think) but I'm hoping that it might be better supported in the new version; more like NServiceBus maybe?

**Comment by mookid8000** [comment]
Hi Steven!  I'll answer your questions one by one :grin: 

1. I am not using SimpleInjector myself. I am not sure what you mean by

> once we call the container for something else, Rebus is still trying to configure it to add a reference to the bus singleton

If you describe to me what the expected behavior would be to a "SimpleInjector kind-of-guy", maybe I can help you either determine whether "new Rebus" behaves that way, or whether it would make sense to align Rebus' SimpleInjector integration better with how SimpleInjector folks would prefer it to work.

2. I cannot readily see how your container challenges can affect how publishing works for you. I can recommend reading [the wiki page about the subscription storage](https://github.com/rebus-org/Rebus/wiki/ISubscriptionStorage) because it has some relevant information.

In your case - if you would like to have one-way endpoints publishing messages - you should probably configure a [centralized subscription storage](https://github.com/rebus-org/Rebus/wiki/ISubscriptionStorage), which means that subscribers subscribe by registering themselves in that storage instead of sending a subscription request to the publisher.

This has the advantage that endpoint mappings are necessary _only for when you `bus.Send`_ - iow you can pub/sub from anywhere. A downside is that it requires all endpoints that need to pub/sub to have access to the centralized subscription storage, which might not always be what you want.

3. The new Rebus has "2nd level retries", which basically delegates the handling of a failed message to another message handler. This means that a failed `SomeMessage` (i.e. after the 1st level retries) will then be dispatched as a `Failed<SomeMessage>`, which you may handle by implementing `IHandleMessages<Failed<SomeMessage>>`. This way you can `bus.Defer` to your heart's desire :smile: 

I hope that clears it - please don't hesitate to ask some more if you still have questions

**Comment by stevengopmo** [comment]
Thank you for your reply and I'm sorry for the confusion around 1 & 2.  Let me clarify a bit more please.  Simple Injector doesn't allow you to modify the container (register new components etc.) after the first call to Resolve.  In the old code the following snippet would cause errors for us because somewhere in the bowels of Rebus this code is being called after we have already resolved some other dependency.

    public void SaveBusInstances(IBus bus)
    {
        container.Register<IBus>(() => bus,Lifestyle.Singleton);
        container.Register<IMessageContext>(()=>MessageContext.GetCurrent(),Lifestyle.Transient);
     }

Since the container has previously been resolved, this includes the call to Container.Verify that we do when starting our application during debug, the code above gives an error.  Of course you can't solve this by checking if it's already registered because you get a chicken/egg scenario.  In the new Rebus I think maybe this goes away because you have

        public void SetBus(IBus bus)
        {
            _container.RegisterSingleton(bus);

            _disposables.Add(bus);

            _container.Register(() =>
            {
                var currentMessageContext = MessageContext.Current;

                if (currentMessageContext != null)
                {
                    return currentMessageContext;
                }

                if (_container.IsVerifying)
                {
                    return new FakeMessageContext();
                }

                throw new InvalidOperationException("Attempted to inject the current message context from MessageContext.Current, but it was null! Did you attempt to resolve IMessageContext from outside of a Rebus message handler?");
            });
        }

I think as long as this is called when setting up the container then the whole problem goes away?

As for the retries, I like the idea of `Failed<SomeMessage>` and I think we can make use of that for sure, but I'm more wondering about the ability to make that retry hesitate for some configurable time.  Usually the message retries so quickly there wasn't time for the issue (in our case RavenDB loading) to resolve itself.

**Comment by stevengopmo** [comment]
Further information on the locking.  It looks like I'm still having this problem with the latest version of Rebus, but it looks like it has something to do with how I configure my logger to which uses the container to grab the current user.  I'll investigate further on my end but initially I think the new version should resolve this issue.

**Comment by mookid8000** [comment]
Regarding SimpleInjector, I would love it if you could try out the new version and see if it solves your SimpleInjector woes :)

Regarding the retries, the dispatch of a `Failed<TMessage>` would allow for forwarding to another endpoint, deferring to the future, etc. I believe it would be possible to create a reusable strategy on top of that, which could e.g. use `bus.Defer` and exponential backoff in combination to implement a pretty resilient 2nd level retry strategy.

I would love it if the core Rebus thing could be the `Failed<TMessage>` mechanism, and then more sophisticated stuff could be built on top of that.

**Comment by stevengopmo** [comment]
Initial SI tests are positive.  I will continue today because this would improve life on several of our projects.  Thank you.

Regarding retries, I think I see where you are going.  When I get to some actual use cases (besides the loading issue for RavenDB which is hard to test) I'll give it a spin too.

**Comment by stevengopmo** [comment]
update - I now do not appear to have any problems with SimpleInjector using the latest of Rebus.  Thank you!  I'll continue to develop and let you know any other interesting stuff I find and I'll also play with the new retry mechanism.

**Comment by mookid8000** [comment]
Cool! One thing, though: at the moment the 2nd level retries mechanism does not work completely as described, but it is close enough that you can try it out...

Sendt fra min iPhone
