### ISSUE TITLE
Change accessability of RebusScopeAccessor to public

### ISSUE THREAD

**Issue by Felorati** [rebus-org/Rebus#409]
First of all, thanks for the great work done on Rebus. Really enjoyable.

I have a request, of changing the accessability of RebusScopeAccessor to public. This would give the opportunity to create hybrid lifestyles with Rebus' own.

Something along the lines of:

```C#
namespace Castle.MicroKernel.Lifestyle
{
    public class HybridPerWebRequestPerMessageScopeAccessor : HybridPerWebRequestScopeAccessor
    {
        public HybridPerWebRequestTransientScopeAccessor() 
        : base(new RebusScopeAccessor())
    {
    }
  }
}
```
Let me know what you think.

**Comment by mookid8000** [comment]
it's internal to avoid exporting more symbols than necessary when importing the package... of course this one could be made public, but I have to say this: 

I always have separate containers in my applications, one for each type of application hosted in the process.

The reason is that the times I have shared a container between, say, Rebus and ASP.NET Web API, I have always ended up running into trouble with managing component lifestyles and unit of work handling.

My recommendation is always to treat a Rebus endpoint and e.g. a Web API endpoint as being two logically separate applications, which just happen to be hosted inside the same process. This way, you will never end up with complicated hybrid lifestyles and units of work that need to work in hybrid contexts too. In addition to this, you make your application much more flexible because it becomes much easier to e.g. pull out the Rebus parts and host them in a Windows Service later on.

**Comment by Felorati** [comment]
Thanks for the thorough answer, some great thoughts.

In my case, the dependencies being resolved between rebus and web api are identical, only the lifecycles vary. I guess this might be a, wanted or unwanted, shortcut for avoiding maintaining two containers.
