### ISSUE TITLE
Asymmetric vs Symmetric Encryption on the bus

### ISSUE THREAD

**Issue by xenoputtss** [rebus-org/Rebus#412]
What are your thoughts on an Asymmetric Encryption that could be used in lieu of the current symmetric encryption?  

I'm looking at a scenario where an endpoint in compromised.  Symmetric encryption I think doesn't offer a lot of protection because it's possible the password could get compromised as well which would make all messages on the bus readable (perhaps different transports handle messages differently, but with relation to the sql transport at least, all messages would then become readable).

If I used an Asymmetric encryption (difficulty of managing the keys goes up) the compromised kiosk would only leak the public key of the destination and it's own private key.

How do you feel about this idea?  Do you have any pointers if someone were to build this into the framework?

**Comment by mookid8000** [comment]
Asymmetric encryption would be harder to implement and manage, because the message would have to be encrypted using the recipient's public key.

For example when publishing a message to two subscribers, each subscriber's public key should be used on the message targeted at that subscriber. This would not readily be possible to implement with multicast-enabled transports, since e.g. Azure Service Bus and RabbitMQ publish only one single message which is then copied to each subscriber's input queue by the transport layer.

It should be possible though with transports that do not implement pub/sub in the transport layer, probably by having a registry of (endpoint, pubkey) somewhere that all endpoints could use.

**Comment by IanYates** [comment]
Valid point.  I suppose you could still use the registry approach for something like ASB.  The sender generates a random symmetric key for the message.  This key is encrypted with the public key of all endpoints known in the registry - so for N possible endpoints (and maybe only 1 or 2 of them are ever going to receive the message) you have N differently encrypted copies of the random symmetric key.  Then those N encrypted keys, plus the symmetric-encrypted message, are put onto the wire.

Receivers that actually get the message look in the little blob of keys to see if they're present.  If so, they use their private key to get to the random symmetric key and then unpack the message.

I don't have a use for it (and don't actually use Rebus yet - I just lurk and watch the issues feed as I aspire to using it soon one day) but that may well be a feasible approach.
