### ISSUE TITLE
Saga storage

### ISSUE THREAD

**Issue by runes83** [rebus-org/Rebus#423]
Are there any plans to make other Saga storage than SQL and RavenDB?

Redis and Azure TableStorage could be useful when living in the cloud.

**Comment by mookid8000** [comment]
Yeah well... I was thinking about adding an Azure table storage saga persister yesterday :) you know what, I'll convert this one into this: #424 

Don't know about Redis though - would you use it if there was one for Azure table storage?

**Comment by runes83** [comment]
Azure table storage is scalable and cheap, but it has some restraints on for example size pr column. But I guess it's possible to spread the json across multiple columns to come around. And larger data than that one should not have in saga data.

**Comment by mookid8000** [comment]
yeah well.... iirc the limit is 64 kB per column and 1 MB for the entire row - I seem to recall having seen a method somewhere whereby a serialized object was distributed among several columns in order to be able to utilize the full 1 MB.

moreover - when #401 is done and the saga serializer is configurable - it will be possible to plug in a decorator that GZIPs the content if it goes over some predefined threshold

**Comment by runes83** [comment]
Then this will be a very nice addition to an already great product.
Using tablestorage to presist sagas will put less restraint on the SQL server in Azure, witch is a expensive and not that scalable product.

I doubt there is a need to persist more than 1 MB of data (gzipped) in saga. In that case use SQL or something else :-)
