### ISSUE TITLE
Needed Sync option

### ISSUE THREAD

**Issue by Jeern** [rebus-org/Rebus#432]
While upgrading from Rebus1 to Rebus2 we have had several issues because Rebus1 defaulted to Sync, and Rebus2 defaults to Async.

We have a setup which uses TransactionsScope, and several senders that sends commands to publishers, these in turn publishes events to Subscribers.

1. It turns out that old code in the style of Bus.Publish no longer works. It HAS to be "await Bus.Publish" because otherwise the published events goes to the dead-letter queue. Reason being that the MSMQ transaction is already committed when Rebus tries to send it to MSMQ. This results in MSMQ treating it as a non-transactional message, consequently not allowing it to enter the transactional queue.

2. HandleTransactionScope in Rebus.TransactionScope is no longer an option for us. Why ? Because it uses the new transactionScopeAsyncFlowOption which means it is serializable instead of ReadCommitted, and more importantly means that it makes our code 42 times slower (perhaps because of some behind the scenes context switching). 2700 commands is 42 minutes to flow through the system instead of 1 minute. But if we do not use TransactionScope we have another problem. Our code is designed to use it. We get all kinds of errors. But using TransactionScope forces us to do Sync, which again makes Events go to the dead-letter Queue.

3. Tried Bus.Publish(...).Wait() instead but it results in deadlock.

So I guess what we really need is an optional interface that allows old style Sync Publish / Send.

Alternate option is to change the implementation of MsmqTransport.Send(...) to send to the queue using a simpler style, more like this:

            using (var msqTr = new MessageQueueTransaction())
            {
                msqTr.Begin();
                sendQueue.Send(logicalMessage, msqTr);
                msqTr.Commit();
            }

And stop reusing the MessageQueueTransaction. The code above actually works in our case.

**Comment by mookid8000** [comment]
1. I know MassTransit magically "captures" async calls started in a message context, ensuring that they run to end before ending the queue transaction. I would like to look into creating the same behavior in Rebus - I've opened #435 for that idea

2. Rebus 0.99.43 defaults to using "read committed" as the transaction scope isolation level, and the configuration extension has an overload that accepts a `TransactionOptions` instance so you can configure it.

3. Yes. This issue is [a known caveat when using `async`/`await`](http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html). It is best to get into a habit of never forgetting that `await` :grin: 

Regarding your "alternate option" - there is nothing wrong with how Rebus' MSMQ transport manages its `MessageQueueTransaction`. The proposed change might make things _look_ right when the programmer forgets to `await`, but it would ruin Rebus' ability to NOT send any messages in case one of the (later) send operations failed.

**Comment by Jeern** [comment]
As discussed on twitter your new TransactionScope package solves the performance issue. Great :)

Regarding the mentioned alternate option it was not meant as something that should actually make it to the codebase (then I would have made a pull request) but rather to showcase that a very simple fix might work. Furthing testing showed me that the alternate code only worked for very simple examples. Which you would have foreseen of course :)

**Comment by mookid8000** [comment]
Right! Thank you for helping me improve Rebus btw - it was good to get a more sensible default behavior brought to the transaction scope :grin: :+1:

**Comment by Jeern** [comment]
No problem :)
