### ISSUE TITLE
Sql Server transport and storage lacks SqlConnection costructor

### ISSUE THREAD

**Issue by zabulus** [rebus-org/Rebus#446]
We are using custom configuration through registry with encryption involved for our database. But I'd like to use our SqlServer as SqlServer centralized Subscription Storage. 

I suggest to add following method to class SqlServerPersistenceConfigurationExtensions and maybe to similar ones:
```public static void StoreInSqlServer(this StandardConfigurer<ISagaSnapshotStorage> configurer, Func<SqlConnection> connectionFactory, string tableName, bool automaticallyCreateTables = true)```

**Comment by zabulus** [comment]
I see EnsureMarsIsEnabled function in the DbConnectionProvider. 
1. Is MultipleActivityResultSet is mandatory for Sql storages?
2. Is it okay if I check (and patch?) for MARS in GetConnection function instead DbConnectionProvider.Ctor?

**Comment by mookid8000** [comment]
1. Well... because of the lazy nature of many of the things that the connection is going to be used for, it is required, yes. Or it used to - come to think of it, it might not be required anymore. I will have to do some testing to figure this out.
2. Yeah sure - if it turns out that MARS is still required, I can see no problem in moving it... although the best way would probably be for the `DbConnectionProvider` to build the MARS-enabled connection string in the ctor and keep it, so it doesn't have to do it every time it is needed.

**Comment by mookid8000** [comment]
fixed by #454

**Comment by mookid8000** [comment]
Will be out in 0.99.66
