### ISSUE TITLE
Reply to sender by IP-address

### ISSUE THREAD

**Issue by asgerhallas** [rebus-org/Rebus#463]
When sending a message by IP-address like this `inbox@192.168.123.123`, I would need to have a return address that points to the originating machine by IP-address too. Right now it postfixes the input queue name with `@machinename` and that does not work across nets. 

Would it be possible to make the return address dependent on the format of the destination address, so when sending to an IP-address it will also return to the senders IP-address?

**Comment by mookid8000** [comment]
Everything is possible 😁 

And yes - I can think of several ways of overriding the `rbs2-return-address` header, ranging from the explicit:

    await bus.Send(someMessage, new Dictionary<string, string> {{Headers.ReturnAddress, "inbox@10.0.1.18" }});

to a slightly more implicit way which would consist of installing an outgoing message step before the current `AssignReturnAddressStep`, which would then set the header. It should be fairly easy to do this in a generic way - I can get back to you with a code sample tonight if you like 😄  (otherwise I can walk you through it here)

**Comment by asgerhallas** [comment]
Thanks! I think the second approach it the right one for me, so I can make some logic to look up the local IP-address (we're sending from many machines). I see if I can discover the way to do it, or else I'll cry for help :)

**Comment by mookid8000** [comment]
oh, btw - you might get away with simply decorating `ITransport` in a way that changes the value returned by the `Address` property - this way, the current `AssignReturnAddressStep` will simply pick that up
