### ISSUE TITLE
RabbitMq connections doesn't recover from a network distribution

### ISSUE THREAD

**Issue by gertjvr** [rebus-org/Rebus#468]
Need to do more investigation but we are seeing a lot of error messages after a network distribution.

![image](https://cloud.githubusercontent.com/assets/1691062/16105584/03ed8724-33cf-11e6-825f-ceb219138f24.png)

**Comment by mookid8000** [comment]
Which version are you using?

The RabbitMQ transport was changed in version [0.99.56](https://github.com/rebus-org/Rebus/blob/master/CHANGELOG.md#09956) and I seem to recall also having done something about its ability to reconnect around that time....

**Comment by gertjvr** [comment]
Latest version

**Comment by mookid8000** [comment]
Hmm... I'll have to investigate this...

**Comment by mookid8000** [comment]
Just to clarify - what do you mean by "network distribution"?

**Comment by gertjvr** [comment]
We had a network outage at work and rebus worker lost communication and
never recovered. Needed a reboot.

**Comment by mookid8000** [comment]
I've done some testing now, and I cannot reproduce any problems.

I did fix it so that it is possible configure prefect by going

    .Transport(t => t.UseRabbitMq(...).Prefetch(10))

and then I made it ditch all prefetched messages in the event of a connection failure (because it would not be able to ACK them).

And then I added a few more defensive measures, mostly some `try-catch` around various calls to `Dispose` on the RabbitMQ client, because it seems to throw exceptions in the most unexpected places.

It would be awesome if you could reproduce the problem - possibly by adapting the `TestRabbitMqReconnection` test to work with your RabbitMQ server and messing around with your network adapter.

**Comment by gertjvr** [comment]
Will try tomorrow have a local rabbit cluster running on docker to test
with.

**Comment by gertjvr** [comment]
Do you have a private or early nuget package somewhere? can't see 0.99.61 on nuget.org

**Comment by mookid8000** [comment]
ah, sorry - the build server was still grinding.... I've released it now 😄

**Comment by mookid8000** [comment]
Dod you have a chance to try again?

**Comment by gertjvr** [comment]
Been running it for a week with no major issue. But I haven't had a chance to play chaos monkey yet. we can close this ticket will reopen if I see more issues?

**Comment by mookid8000** [comment]
Sure 😄  and yes, please let me know if it doesn't recover as it should.
