### ISSUE TITLE
Filesystem persisters should support ISagaStorage and ITimeoutManager

### ISSUE THREAD

**Issue by jeffreyabecker** [rebus-org/Rebus#472]
I would like to use this for development along with filesystem queues. I realize that this is probably super-slow. [Filesystem](https://github.com/jeffreyabecker/Rebus/tree/more-filesystem/Rebus/Persistence/FileSystem)

**Comment by mookid8000** [comment]
The timeout manager could probably be made without too much hazzle.

The saga persister requires some kind of synchronization mechanism because it needs to enforce a unique constraint on all the saga's correlation properties - I wouldn't really know how to do that in the file system.

Another option could be to maybe provide full persistence implementations for an embedded database, like e.g. SQLite or embedded Firebird.

What do you think?

**Comment by asgerhallas** [comment]
It could be done using some of the same techniques I used for the file system event store in Cirqus. I made it for fun, but it worked out well. Uniqueness (in that case it was stream IDs) was done using filenames and atomicity was made with a simple transaction log in a separate file. 

A filename might not be the best choice though for the unbounded number of correlation properties of Rebus sagas. 

And that said, it might be more straight forward to take the dependency on some embedded db as @mookid8000 suggests.

**Comment by jeffreyabecker** [comment]
My implementation assumes a single process and just uses reader-writer lock slim. I could rework it to use filesystem locking which is slow but fundamentally how stuff like sqlite or firebird work.

**Comment by mookid8000** [comment]
I guess using an embedded database would also work for a single process only, so that's actually not better.

I guess using an in-process locking mechanism to synchronize updates to the correlation properties would work alright then.

@jeffreyabecker  Do you already have an implementation working?

**Comment by asgerhallas** [comment]
I believe SQLite supports multiple concurrent processes, just not writing at the same time.

**Comment by mookid8000** [comment]
It does? Wow - that sounds slow 😁

**Comment by asgerhallas** [comment]
Yes, I think it is :) 

Details are here https://www.sqlite.org/faq.html#q5

Having a saga instance per file on the other hand will support multiple processes and be a lot faster :)

**Comment by asgerhallas** [comment]
Actually given that there's no batches or other commits spanning multiple docs, there's no need for a shared log. So I believe full multiple process support can be done. At least on some file systems.

**Comment by mookid8000** [comment]
That was actually a pretty interesting idea!

The files could be in [JSONL](http://jsonlines.org/) format then, where the first line could be the correlation properties, and the second line could be the saga data. E.g. like this:

    [{"name": "Id", "value": "384929n9"}, {"name": "CorrelationId", "value": "2016-06-23"}]
    {"Id": "384929n9", "Revision": 5, "CorrelationId": "2016-06-23", (...)}

which would allow for scanning the correlation properties pretty quickly by reading/parsing the first line of each saga file.

The file system would then ensure that an update was exclusive and atomic

**Comment by jeffreyabecker** [comment]
so my implementation is [here:](https://github.com/jeffreyabecker/Rebus/tree/more-filesystem/Rebus/Persistence/FileSystem). It uses filesystem spinlocks (kill me now) to ensure that stuff is safe across both threads and processes. Unfortunately that is the only cross-platform pure dotnet way of doing this.  Its LAME.

**Comment by asgerhallas** [comment]
There's a little catch though, as file writes are not atomic nor isolated. What I did in Cirqus was append only and that helps a lot.

**Comment by asgerhallas** [comment]
But it can be done by marking the end of a write in the file and then let the reader be sure only to read full writes. That's what I did with the tx log and it gives both isolation and atomicity in case of crashes and the like.

**Comment by mookid8000** [comment]
@jeffreyabecker it looks really good! if it works, I would accept a PR immediately! (and by "immediately" I mean some time tomorrow or in the weekend.... sorry 😁 )

**Comment by jeffreyabecker** [comment]
All the unit tests pass. Before you start talking about accepting my PR's...

1. How should I be using the logger? None of the stuff I've worked on logs anything and I'm not really clear on what the logging conventions are for storage.
2. I've got more issues incoming, obviously backed by code that I think is ready to merge. Let me get all those done.

**Comment by mookid8000** [comment]
1. The rule I follow is to log if there is something special going on, like doing something based on a check of some kind - like e.g. when a file system-based persister is nice enough to automatically create its own directory, I would log "directory (bla bla) does not exist - creating it now" or something.

This should be logged at the INFO level because it is not a thing that would happen continually when the system is running.

If you feel like logging something while doing ordinary work, you use DEBUG level - but it is often unnecessary to do that as long as you throw nice explanatory exceptions, and I can see that you are already doing that 😄 

2. I would prefer several smaller PRs over one big. I'm also prepared to go through the PR once merged and make sure that it fits with what I feel is good Rebus style - I seem to have some kind of OCD that forces me to do that.

**Comment by mookid8000** [comment]
Fixed by #477 which will be out in 0.99.66
