### ISSUE TITLE
Fully featured persistence mechanisms should be easier to configure

### ISSUE THREAD

**Issue by jeffreyabecker** [rebus-org/Rebus#473]
For persistence mechanisms that support a full set of interfaces there should be a one-stop configuration mechanism. E.g.

`Configure.With(myioc).UseSqlServer("MyConnection");`

**Comment by mookid8000** [comment]
That's a pretty good idea, although - based on my own experience - I would never get to use one of those (except maybe for demo purposes, which - come to think of it - could be reason enough)

Over time I have converged towards a style where new projects are started by identifying 2-3 endpoint roles, like e.g. "client", "server", and "router", and then provide a custom extension for each... could be something like:

    Configure.With(new CastleWindsorContainerAdapter(container))
        .AsServer("queueName")
        .Start();

which then does all the necessary configuration. This way, the configurations are consistent, while still providing a way to customize each endpoint since `AsServer` just attaches to `RebusConfigurer`

I'll have to think some more about this 😄

**Comment by jeffreyabecker** [comment]
Its actually my most common configuration. Mostly I use rebus as a way to background tasks for my website. Maybe this belongs in that convenience project?

**Comment by mookid8000** [comment]
Yes I think so - but "convenience" is just a solution folder iirc, but you could definitely create the Rebus.Convenience project now

Sendt fra min iPhone

**Comment by jeffreyabecker** [comment]
One open question on this: For Use???AsOneWayClient methods, should I configure saga persistence? I know the old version had issues with that configuration but i havent dug far enough in to tell with the new stuff.

**Comment by mookid8000** [comment]
Since one-way clients don't have an input queue or any worker threads, and thus are unable to receive messages, saga persistence is not relevant.
