### ISSUE TITLE
There should be a way to propagate the current principal through the message header.

### ISSUE THREAD

**Issue by jeffreyabecker** [rebus-org/Rebus#478]
Really this is a couple of questions:
1. What is the appropriate pipeline stage for outgoing steps? Currently I have this after AssingTypeHeaderStep.
2. Are pipeline steps like owin middlewares in that once await next() has completed we're on our way out? If so is before ActivateHandlersStep the correct place?

**Comment by mookid8000** [comment]
1. Since the job carried out by the step is to add a header to the message, I feel it would be best to put it near the other header steps - so yes 👍 
2.Yes, they're exactly like OWIN middlewares. But I would put it hear the other header-steps.

**Comment by mookid8000** [comment]
An extension method to provide this functionality could be a neat addition to an upcoming convenience package... something like

	Configure.With(...)
		.(...)
		.Options(o => {
			o.AutomaticallyPropagateCurrentPrincipal();
		})
		.Start();

which would automatically

1. Pick up `Thread.CurrentPrincipal.Identity.Name` and put it on outgoing messages, and
1. Set `Thread.CurrentPrincipal` based on the username in a handled message

would actually be pretty awesome.

**Comment by jeffreyabecker** [comment]
Its actually a little more involved than just picking up the name, at least for my usages.  I end up needing to serialize the whole ClaimsPrincipal.Current instance and use that. 

Code is here: https://github.com/jeffreyabecker/Rebus/tree/convenience/Rebus.Recipes/Identity

**Comment by mookid8000** [comment]
ah yes, using `ClaimsPrincipal` is much better

the good looks good, except for one thing: [this part](https://github.com/jeffreyabecker/Rebus/blob/convenience/Rebus.Recipes/Identity/RestorePrincipalFromIncomingMessage.cs#L30-L34) should

1. only do stuff if the `CapturePrincipalInOutgoingMessage.PrincipalCaptureKey` key is present among the headers, and
1. `try { await next(); } finally { revert the principal }` because exceptions will bubble right out of `next()`

I'm looking forward to the recipes PR 😄

**Comment by mookid8000** [comment]
PS: you're on fire! 🔥 who are you? have you been using Rebus for a long time?

**Comment by jeffreyabecker** [comment]
I've been using service buses in the dumbest configurations for years. I used the 'old' version pretty extensively for one app.

**Comment by jeffreyabecker** [comment]
Thanks!
