### ISSUE TITLE
Using async MSMQ methods

### ISSUE THREAD

**Issue by zabulus** [rebus-org/Rebus#484]
This is more curious question about MSMQ implmentation.
Have you considered using implementation provided here: http://stackoverflow.com/a/16104783/273577
```
    private  async Task<Message> MyAsyncReceive()
    {
        var queue=new MessageQueue();

        var message=await Task.Factory.FromAsync<Message>(queue.BeginPeek(),queue.EndPeek);

        using (var tx = new MessageQueueTransaction())
        {
            tx.Begin();
            queue.Receive(tx);
            //Process the results inside a transaction
            tx.Commit();
        }
        return message;
    }
```
for receiving messages. IMO this would allow to avoid loops and exceptions in worker threads.

**Comment by mookid8000** [comment]
I am aware that this is the recommended way to do transactional receive when using the async API of MSMQ, but I have never actually tried using it with Rebus.

You are absolutely right though that it would probably be nice to avoid (most of) the `MessageQueueException`s thrown when there is no message to receive - but since Rebus' worker threads are essentially competing consumers, there will be a small race condition between calling `BeginPeek` and `Receive` which must be accounted for.

If the performance does not suffer from making two calls instead of one for each received message, I think refactoring the transport to receive messages this way would probably be pretty nice.

**Comment by mookid8000** [comment]
So I guess this task consists of the following:

- [ ] create a test that measures receive performance (as in: how many msgs/s can be received with various settings of number of workers and max parallelism)
- [ ] run the test with the current implementation
- [ ] refactor MSMQ transport to use `BeginPeek`/`Receive` instead of the current `Receive` with a timeout
- [ ] run the test again with the new implementation

Figure out which implementation to keep 😄

**Comment by mookid8000** [comment]
I have played around with implementing this in the [msmq-peekaboo branch](https://github.com/rebus-org/Rebus/tree/feature/msmq-peekaboo), but it turned out to have worse performance than doing the synchronous receive that Rebus has always been doing.

With the introduction of the new thread pool-based worker factory (talked about in #501 ) the MSMQ polling timeout can be increased without affecting the latency with which continuations are processed, so that will lead to fewer exceptions in the background.

Moreover, the new worker factory allows for – almost trivially – introducing an "auto-scale" feature that will automatically shut down workers during idle periods and spin them up again when they are needed. This will lead to even fewer exceptions in the background.

Lastly – if you are exhausted from pressing F5 all the time because your debugger breaks on the `MsmqException` getting caught deep in the bowels of Rebus' MSMQ transport – [there are ways to set up your development environment to avoid this](http://stackoverflow.com/a/11183553/6560). In my opinion you should only be interested in exceptions that bubble out to your own code anyway 😉

**Comment by zabulus** [comment]
I don't exhausted by pressing F5. My concern is more about performance overhead due to multiple throwing exception. Though, your explanation is sufficient
