### ISSUE TITLE
Open existing non-sealed implementations for extension and modification.

### ISSUE THREAD

**Issue by Rzpeg** [rebus-org/Rebus#485]
Hello! :smile: 

I would like to make a few changes to existing InMemErrorTracker (For now I want to override RegisterError and CleanupOldTrackedErrors, then inject it as IErrorTracker), keeping the rest as is.
The problem is that, currently, Rebus implementations aren't inheritance-friendly: the fields and properties are private (not protected) and the methods are private and non-virtual. So the only option left is to literally copy-paste the code.  

So my suggestion is to make any injectable module (implementing https://github.com/rebus-org/Rebus/wiki/Extensibility#Abstractions) open for extension and modification. What do you think ?

**Comment by mookid8000** [comment]
I have intentionally made as much as possible private or internal in order to reduce the size of the surface API exposed to e.g. someone like you 😄 

Did you consider whether decorating `InMemErrorTracker` with your own implementation of `IErrorTracker`, calling the old in-mem error tracker as necessary would do the trick?

If you tell me what you are trying to do, maybe I can come up with another way of doing it...

**Comment by Rzpeg** [comment]
Can't say I agree :smile: I think it's OK for non-customizable and non-injectable modules though.
I was trying to do the following: 
1. In RegisterError, I wan't to pass the exception to my custom IExceptionHandler, this could be done using a decorator. 
2. I wanted to override CleanupOldTrackedErrors so I could change the 10-minute hardcoded timer.
 
P.S. Why is CleanupOldTrackedErrors is a Task and RegisterError isn't ? :smile:

**Comment by mookid8000** [comment]
`RegisterError` does not return a `Task` because I never actually made another implementation of `IErrorTracker`, even though I originally anticipated the need for implementations that would use e.g. MongoDB or Redis to track errors. `CleanupOldTrackedErrors` returns a `Task` because it uses Rebus' `IAsyncTaskFactory` to schedule its task.

IOW there's no good reason why it is so 😁 

For now I suggest you simply copy the code of `InMemErrorTracker` and adapt it to your needs and then make Rebus use it (and skip auto-registering its own) like this (pretending that you keep your `IExceptionHandler` service):

    .Options(o => {
        o.Register<IExceptionHandler>(c => new YourCustomExceptionHandler());
        o.Register<IErrorTracker>(c => {
            var exceptionHandler = c.Get<IExceptionHandler>();
            return new YourNewErrorTracker(exceptionHandler));
    })

although you probably might want to hide these rather crummy-looking lines behind a couple of nifty extension methods 😄 

Your suggestion touches on something interesting though that I feel is bigger than your problem at hand, which is the strategy I have chosen for extensibility. As you are now experiencing I have opted very much for composition over inheritance, which can be seen in that very few of Rebus' classes expose anything to subclasses (although none of them are `sealed` IIRC).

For now I feel that I have chosen the right approach to these things, as you are the first one to ask for better inheritance support. However I do feel a slight sting of sadness when I have to resort to asking people to "just copy the code and adapt it to your needs", because these cases CAN be a hint that something is inadequate.

I hope you can get by with my suggestion - if not, please keep pushing 😁

**Comment by Rzpeg** [comment]
Oh ok, Copy paste means copy paste! :smile: 
I was thinking about implementing MSSQL ErrorTracker, that could be shared between Rebus instances, so Task-based IErrorTracker contract would be great! :smile:
(My IExceptionHandler is also async, by the way!) 

It would be also nice, if rebus could pickup dependencies already injected in my container, without registering them again (e.g. IExceptionHandler) in Rebus InjectionList. Have you thought about ? Maybe we could use existing IContainerAdapter for this ?

**Comment by mookid8000** [comment]
> It would be also nice, if rebus could pickup dependencies already injected in my container, without registering them again (e.g. IExceptionHandler) in Rebus InjectionList. Have you thought about ? Maybe we could use existing IContainerAdapter for this ?

Yeah, well.... the thing is that Rebus does not really use a real IoC container, it uses [Injectionist](https://github.com/rebus-org/Injectionist), which is - granted - IoC-like - but still not quite an IoC container.

The way it differentiates from a real IoC container, is that it is not meant to work with the [RRR pattern](http://blog.ploeh.dk/2010/09/29/TheRegisterResolveReleasepattern/) because it has not concept of lifestyle - all registered factory methods get called once only.

The only place where the RRR pattern fits in with Rebus, is around handling a message. And that is where the `IContainerAdapter` fits in by providing an adapter for the different IoC containers to perform the last two Rs (Resolve/Release)

If you really want, I guess you _could_ configure Injectionist to forward the factory method call to your IoC container by registering `IExceptionHandler` like this:

    .Options(o => {
        o.Register<IExceptionHandler>(c => yourContainer.Resolve<IExceptionHandler>());
    })

BUT that would completely bypass your container's lifestyle management. You should ONLY do this if `IExceptionHandler` is configured to be a singleton in your container.

I hope that makes sense 😄
