### ISSUE TITLE
Data bus encryption

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/Rebus#497]
Support encryption via an `IDataBusStorage` decorator

**Comment by mookid8000** [comment]
[here](https://github.com/rebus-org/Rebus/issues/497) and [here](https://github.com/rebus-org/Rebus/issues/498)

**Comment by mookid8000** [comment]
Marked this one as less important.

(also raises a pretty important question: how to ensure that the order of compression/encryption is always right if both get enabled?)

**Comment by zabulus** [comment]
Compressors use magic number and/or headers

**Comment by TsengSR** [comment]
@mookid8000: I guess the order will have to be configured, as there are two scenarios where'd you want to use it. 

1. Compression reduces the payload, reduced payload is less storage and less data to en-/decrypt, so may be better for performance. But it may be vulnerable against plaintext attacks where the user can controll part of a plaintext (i.e. when the repeats the plaintext he can see on the size if it's compressd and used that as a base for his attack on the encryption), see [CRIME](https://en.wikipedia.org/wiki/CRIME) attack.
2. To avoid above scenarios weakness, you'd want to encrypt and then compress it. Since encrypting adds much entropy to the data, the compression won't be as effective as the other way around though

@zabulus: Json payload does that too, where the first 1 to 3 bytes are know to be there, as in `{ "`or `{"`, `[` etc., so I don't see that as much of an issue

**Comment by mookid8000** [comment]
@TsengSR pretty good points – interesting reading about the CRIME attack 😁 

Here's a thing though: The encryption provided by Rebus (for messages at the moment, possibly also for data bus data later on) is not really meant to be hacker-proof. 

It is designed to work in a way that provides just enough secrecy that e.g. developers and operations people can develop and maintain systems based on Rebus and not accidentally get to read e.g. his colleague's payroll information or other semi-sensitive pieces of information.

A real-world analogue could be something like having a lock on a file cabinet in your company's financial or HR department: If a malicious employee wanted to break in and read up on his/her colleague's relatively sensitive pieces of information, the lock would not really provide any substantial protection, as it would be fairly easy to just break the file cabinet open and start reading. I bet many companies would even have the keys to the file cabinet lying in a desk drawer right beside it.

You could say that this kind of protection is more a statement about secrecy than it is about providing real effective secrecy under all circumstances.

My own informal tests on a bunch of JSON messages reveal that doing the encryption first effectively defeats compression almost completely because of the added entropy, while doing it the other way around is really effective. 

And As I am not really worried about the slight weakness introduced by first compressing and then encrypting, I think this is the most sane order to do it in.

**Comment by mookid8000** [comment]
I am closing this one for now – we can keep discussing it in here if anyone has anything to add, and possibly reopen it if someone feels strongly about it, but for now I think it belongs in the archive 😄
