### ISSUE TITLE
Process message with single subscriber in pub-sub scenario. Howto?

### ISSUE THREAD

**Issue by zabulus** [rebus-org/Rebus#506]
I have pub-sub system, and I need some messages to be processed only by one subscriber, no matter what. Is it possible using just transport? 
I have ideas how to do this on higher layer with additional processing logic, but I'd like to try fix this on transport layer.

**Comment by mookid8000** [comment]
Generally, all messages are guaranteed to "get there". If a message has been properly sent - because the transport is durable - it is guaranteed to be processed some time in the future.

If you want a message to be processed by a single recipient, I don't think it sounds like you want to do pub/sub. I think it sounds like you want to

    await bus.Send(thatMessage);

in which case the message will be sent to the endpoint that owns the given message type.

The question of "who owns the message types" gets answered by asking the endpoint mapping, which you can set up by doing something like this:

	Configure.With(...)
		.(...)
		.Routing(r => {
			r.TypeBased()
				.Map<SomeType>("queue1")
				.Map<AnotherType>("queue2")
				.MapAssemblyOf<ThirdType>("queue3");
		})
		.Start();

How does that sound to you?

**Comment by mookid8000** [comment]
(oh and I'm closing this one because it's not really an "issue".... should probably have been on [StackOverflow](http://stackoverflow.com/questions/tagged/rebus) instead of GitHub)

**Comment by zabulus** [comment]
Sry I'll ask further question on SO
