### ISSUE TITLE
Dequeuing of rabbitmq is failing

### ISSUE THREAD

**Issue by takinosaji** [rebus-org/Rebus#508]
This issue related to our previous conversation according switching to Rebus 2: http://stackoverflow.com/questions/38613066/subscribing-rabbitmq-queue-via-rebus-2/

Rebus2 can't consume messages which Rebus1 consumed well with next exception:

> 2016-07-28 13:06:18 WARN  Rebus.Workers.ThreadBased.ThreadWorker: An error occurred when attempting to receive transport message: Rebus.Exceptions.RebusApplicationException: unexpected exception thrown while trying to dequeue a message from rabbitmq, queue address: MyQueue ---> System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Rebus.RabbitMq.RabbitMqTransport.CreateTransportMessage(BasicDeliverEventArgs result)
   at Rebus.RabbitMq.RabbitMqTransport.<Receive>d__32.MoveNext()
   --- End of inner exception stack trace ---
   at Rebus.RabbitMq.RabbitMqTransport.<Receive>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rebus.Workers.ThreadBased.ThreadWorker.<TryReceiveTransportMessage>d__16.MoveNext()

I have looked in code of RabbitMqTransport think it is because message doesn't have headers. If I am correct can i fix it somehow and make rebus consume messages composed by third parties?

**Comment by mookid8000** [comment]
You can definitely fix it. I suggest you start out by taking the code from the existing RabbitMQ transport, and then you adapt it so it does not die when there are no headers on the incoming message.

And then - since Rebus requires at least the presence of a message ID header ([`rbs2-msg-id`](https://github.com/rebus-org/Rebus/blob/master/Rebus/Messages/Headers.cs#L13)) you would need to somehow provide that header if it is not present.

The easiest way to do that would be to decorate `ITransport` and provide an ID somehow if it is not present.

You can install a decorator by doing something like this in the `Options` configurer:

	.Options(o => {
		o.Decorate<ITransport>(context => {
			// get actual transport
			var transport = context.Get<ITransport>();

			return new IdProvider(transport);
		});
	})

(I'm closing this issue because it is not an error - we can still continue the discussion in here 😄 )

**Comment by takinosaji** [comment]
Thanks for you attention - i don't want to abandon upgrade on half a way)
Approach with recorator defenitely the best solution but at the mean time for a test purposes i have created a copy of RabbitMqTransport where I changed

 ` public async Task<TransportMessage> Receive(ITransactionContext context, CancellationToken cancellationToken = default(CancellationToken))` method 

by adding a header if not exists

`
 BasicDeliverEventArgs result;
                if (!consumer.Queue.Dequeue(TwoSeconds, out result)) return null;

                if (result.BasicProperties.Headers == null)
                {
                    result.BasicProperties.Headers = new Dictionary<string, object>
                    {
                        [Headers.MessageId] = Guid.NewGuid().ToString()
                    };
                }
`

Now Rebus successfully consumes a message, deserializes it but i got another exception: 

> 2016-07-28 18:44:03 WARN  Rebus.Retry.ErrorTracking.InMemErrorTracker: Unhandled exception 1 while handling message with ID c64e23c3-dfb4-427d-89b6-573b9061e744: Rebus.Exceptions.RebusApplicationException: Message with ID c64e23c3-dfb4-427d-89b6-573b9061e744 and type Scope.Scope2.Scope3.MyMessageType, Library.Scope.Messages could not be dispatched to any handlers

although i have a generic message handlers `IHandleMessages<Scope.Scope2.Scope3.MyMessageType>`

and as my message falls - it is being requeueed if i can say so and i receive it again with empty handlers and eventually i am falling to endless circle of attempts to proceed this message.

**Comment by mookid8000** [comment]
Two things:

1) "The message cannot be dispatched to any handlers" means that your IoC container apparently refused to return any handler instances for the incoming message type. 

You should probably check to see which .NET type your message gets deserialized to, and then check if your expected handler(s) can be properly resolved with that type.

2) When you assign `Guid.NewGuid()` to an incoming message you make it impossible for Rebus' error tracker to track the message between delivery attempts - so if delivery fails, the error tracker will see the next delivery of the same message as if it was a NEW message.

This is bad for several reasons, mainly because it can very quickly lead to high memory usage because an in-mem dictionary of message IDs is kept to track delivery attempts.

The dictionary gets cleaned up periodically, but not fast enough to avoid this kind of selv-inflicted DOS attack 😨 

Moreover, since the message is delivered again and again, it will clog up the queue and block the way for other messages to get though.

**Comment by mookid8000** [comment]
In Rebus 0.99.70 (which will be out when the buildserver has finished munching through the tests) I've made the RabbitMQ transport more tolerant.

It will now accept null as incoming headers without failing.

And then, if there is not `rbs2-msg-id` header, it will either

1. assign the RabbitMQ message ID if it is present
1. calculate a hash from the message body and use that as the ID

I think this will actually solve all of your message ID problems.

Only thing left is then to e.g. decorate the serializer so that your non-Rebus messages get turned into something that can be properly handled. You can take a look at [how I have implemented a fallback serializer here](https://github.com/rebus-org/Rebus/blob/master/Rebus.RabbitMq.Tests/ReceiveNonRebusMessageWithRabbitMq.cs#L69-L97) which will try to use the real serializer to deserialize, and if that fails it will try to deserialize the message body as a UTF8-encoded string.

**Comment by takinosaji** [comment]
Very nice! Looking forward on your 0.99.70 update. (btw had a similar thoughts how to solve message id problem )
As for "The message cannot be dispatched to any handlers".
Previously we haven't registered explicitly message handlers while using Rebus1. Should I do it in Rebus2 using my container explicitly like (windsor for instance):
`
        windsorContainer.Register(Component.For<IHandleMessages<Entity>>().ImplementedBy<EntityMessageHandler>());
`  ?

**Comment by takinosaji** [comment]
Upd: i have set dependencies manualy and *phanfares* ..... yeah now rebus 2 consuming messages. 
So i am waiting for your update of rabbitmq transport and then check retry strategy.

**Comment by mookid8000** [comment]
0.99.70 is available now :)

Sendt fra min iPhone

**Comment by takinosaji** [comment]
Thanks. I have updated to latest version and now i am getting next exception while trying to start bus

> Rebus.Injection.ResolutionException: Could not resolve Rebus.Retry.IRetryStrategy with decorator depth 0 - registrations: Rebus.Injection.Injectionist+Handler ---> System.TimeoutException: The operation has timed out.
   at RabbitMQ.Util.BlockingCell.GetValue(TimeSpan timeout)
   at RabbitMQ.Client.Impl.SimpleBlockingRpcContinuation.GetReply(TimeSpan timeout)
   at RabbitMQ.Client.Impl.ModelBase.QueueDeclare(String queue, Boolean passive, Boolean durable, Boolean exclusive, Boolean autoDelete, IDictionary`2 arguments)
   at RabbitMQ.Client.Impl.AutorecoveringModel.QueueDeclare(String queue, Boolean durable, Boolean exclusive, Boolean autoDelete, IDictionary`2 arguments)
   at Rebus.RabbitMq.RabbitMqTransport.DeclareQueue(String address, IModel model, Boolean durable)
   at Rebus.RabbitMq.RabbitMqTransport.CreateQueue(String address)
   at Rebus.Config.RebusConfigurer.<>c.<Start>b__12_10(IResolutionContext c)
   at Rebus.Injection.Injectionist.ResolutionContext.Get[TService]()
   --- End of inner exception stack trace ---
   at Rebus.Injection.Injectionist.ResolutionContext.Get[TService]()
   at Rebus.Config.RebusConfigurer.<>c.<Start>b__12_14(IResolutionContext c)
   at Rebus.Injection.Injectionist.ResolutionContext.Get[TService]()
   at Rebus.Config.RebusConfigurer.<>c.<Start>b__12_15(IResolutionContext c)
   at Rebus.Injection.Injectionist.ResolutionContext.Get[TService]()
   at Rebus.Legacy.LegacyCompatibilityConfigurationExtensions.<>c.<EnableLegacyCompatibility>b__0_1(IResolutionContext c)
   at Rebus.Injection.Injectionist.ResolutionContext.Get[TService]()
   at Rebus.Config.RebusConfigurer.<>c.<Start>b__12_16(IResolutionContext c)
   at Rebus.Injection.Injectionist.ResolutionContext.Get[TService]()
   at Rebus.Config.RebusConfigurer.<Start>b__12_8(IResolutionContext c)
   at Rebus.Injection.Injectionist.ResolutionContext.Get[TService]()
   at Rebus.Config.RebusConfigurer.<Start>b__12_19(IResolutionContext c)
   at Rebus.Injection.Injectionist.ResolutionContext.Get[TService]()
   at Rebus.Config.RebusConfigurer.<>c__DisplayClass12_1.<Start>b__20(IResolutionContext c)
   at Rebus.Injection.Injectionist.ResolutionContext.Get[TService]()
   at Rebus.Injection.Injectionist.Get[TService]()
   at Rebus.Config.RebusConfigurer.Start()

This exception is reproduced using RabbitMq.Client of version 3.6.4. With previous 3.6.3 it works fine.

**Comment by mookid8000** [comment]
??? looks like an issue connecting to RabbitMQ - it's the `QueueDeclare` operation on RabbitMQ's `IModel` that gets a timeout...

**Comment by takinosaji** [comment]
Yeah and it is reproduces only with new version of  RabbitMq.Client 3.6.4. So far we are using 3.6.3 so it is not a critical problem for us.

**Comment by takinosaji** [comment]
So far Rebus2 sends messages which are successfully consumed by Rebus1 but sometimes we receive error from Rebus1 which says: "MessageObject = {Mismatch between transport-level and header-level message's id. This may indicate a software bug, or maybe due to processing of messages generated by previous versions of Rebus. (TLID: (null) - HLID: 853511a1-3335-45ef-a36d-cde1cfaed863)}". Does it mean that incoming message was lost for Rebus1 ?

**Comment by mookid8000** [comment]
No, it doesn't mean that the message was lost. I hope that is also not what you are experiencing?

If I recall correctly, this is just a warning that there is a mismatch between the two message IDs, since Rebus 1 would use the message ID from the header as the envelope message ID too when possible.
