### ISSUE TITLE
Automatically detect compression 

### ISSUE THREAD

**Issue by runes83** [rebus-org/Rebus#521]
Is it possible for the receiving bus to automatically detect if compression is turned on (as with encryption if not encrypted is does not try to decrypt). ?

There is a header that tells the receiving bus that the message is compressed, so it so the receiving bus should just decompress.

In development it's usually nice to not use compression for readability, and in production you often want to use compression. The problem comes when you get out of sync the client uses compression and the receiver not. Typically when there are some making the client and some the service.

**Comment by mookid8000** [comment]
Check out the [`Deserialize`](https://github.com/rebus-org/Rebus/blob/master/Rebus/Compression/ZippingSerializerDecorator.cs#L48-L75) method 😄 it will only decompress an incoming message if the `rbs2-content-encoding` header is present, so it works the way you are suggesting it should work.

If you look at the [`Serialize`](https://github.com/rebus-org/Rebus/blob/master/Rebus/Compression/ZippingSerializerDecorator.cs#L28-L46) method you can see that it only compresses an outgoing message if the size of its body is greater than the configured threshold.

I can recommend just enabling compression throughout, and then setting the threshold to a big value – e.g. 16 kB or 32 kB or some other number where you will most likely not want to look at the message contents anyway.

**Comment by mookid8000** [comment]
I must admit, though, that I have sometimes wondered to myself whether it would make sense to just enable compression all the time, and then just set the threshold to a pretty big value – e.g. 1 MB or something – because if the size ever got into that range, you would almost always save time by compressing/decompressing before sending the bytes over the network.

This way, the serializer decorator would always be present, and it would always be there to decompress an incoming message if it turned out to be compressed.
