### ISSUE TITLE
SqlServer transport polling interval

### ISSUE THREAD

**Issue by margusbirk** [rebus-org/Rebus#531]
When using SQL Server transport the database gets polled very frequently. For my use case it is acceptable that messages are delivered with a slight delay when that means less polling on the database. 
Is it possible to configure the polling interval for consumers?

**Comment by mookid8000** [comment]
Yes – the polling interval depends on two things: 1) the accepted degree of parallelism(*), and 2) the backoff behavior.

You can configure the parallelism like this:

	.Options(o => {
		o.SetMaxParallelism(5);
	})

and you will be able to configure the backoff behavior when Rebus 2.0.0 (yes! a real 2.0.0) is out, like this:

	.Options(o => {
		o.SetBackoffTimes(
			TimeSpan.FromMilliseconds(100),
			TimeSpan.FromSeconds(1),
			TimeSpan.FromSeconds(5)
		);
	})

in order to configure polling when idle to

* 100 ms for the first idle second
* 1 s for the next idle second
* 5 s for the rest of the idle time



---
(*) although the SQL Transport limits itself internally to max 10 concurrent asynchronous receive atempts

**Comment by jpierson** [comment]
@mookid8000: We are using _0.99.74_ and noticed that the `SetBackoffTimes` feature doesn't seem have an effect on the polling interval in our tests. Am I understanding correctly from above that this API exists pre-2.0 but isn't respected at least for the the SQL Server transport until 2.0.0?

**Comment by mookid8000** [comment]
Yes 😄 

In 0.99.74 it would only have an effect if you did this:

	.Options(o => {
		o.UseLegacyRebusThreadWorkerBlabla();
	})

which was marked as `[Obsolete]` and is completely gone now.

If you try with Rebus 2.0.0-b02 you should see an effect.

**Comment by jpierson** [comment]
Ok, it looks like the method I'm looking for is `UseClassicRebusWorkersMessageDispatch()` and so far with my testing this seemed to do the trick. Being marked obsolete should we have any concerns using this in the short term until 2.0.0 is ready? I don't see any mentioned in the docs?

**Comment by mookid8000** [comment]
No worries 😄 

The reason it is there, is because Rebus recently got a new "worker factory". The new worker factory creates workers that defer execution of continuations to the .NET thread pool, instead of always running the continuations on dedicated Rebus worker threads.

This turned out to be a much much better way to divide work: Rebus workers receive messages (possibly blocking the thread while waiting for the next message, doesn't matter), and then – when a message is received – it gets dispatched on the worker until the first `await`, after which execution continues on the thread pool.

This way, workers could poll with longer timeouts, while not needing to care about blocking the thread.

In 0.99.74 the new behavior was default, but you could revert to the previous behavior by calling `UseClassicRebusWorkersMessageDispatch()`.

From 2.0.0 and on, the "classic Rebus workers message dispatch" will be completely gone. It is not mentioned in the docs because it was a temporary addition to Rebus which could be used if anyone was experiencing problems with the new dispatch mechanism.

**Comment by mookid8000** [comment]
Btw. if you are interested in lowering your CPU load while lowering the message handling latency at the same time, I can recommend you update to Rebus 2.0.0-b02 and Rebus.SqlServer-b01 (yes, the SQL Server things have their own package now).

I don't think you will experience any issues – it's the same Rebus as you were using with 0.99.73, it's just got a better worker factory 😁 and soon Rebus will be out in an official 2.0.0.
