### ISSUE TITLE
Route messages without handlers to specific error queue

### ISSUE THREAD

**Issue by margusbirk** [rebus-org/Rebus#535]
What is the correct way to route messages that didn't have a handler configured to a named error queue?

I was able to achieve some success by using this routing configuration: 
`Routing(r => r.ForwardOnException<RebusApplicationException>("error.unhandled", LogLevel.Debug, e => true))
`

But this approach is obviously not good because RebusApplicationException is thrown in other places also. I could do some string comparison on the exceptions message but it would be better if I could just do something like this: `ForwardOnException<RebusNoHandlerForMessageException>(...)`

The `DispatchIncomingMessageStep` class could be modified without side-effects to achieve this.

**Comment by mookid8000** [comment]
I have recently implemented something for a customer where we let all failed messages go to a global error queue called `error` (which they do by default), and then we had a special error service that would consume messages from that queue and forward them to an appropriate queue using Rebus' transport message forwarding capability.... in your case, it could look something like this:

	Configure.With(...)
		.Transport(...)
		.Options(o => {
			o.AddTransportMessageForwarder(async transportMessage => {
				if (MessageCouldNotBeDispatched(transportMessage)) {
					return ForwardAction.ForwardTo("dispatch_error");
				}

				return ForwardAction.ForwardTo("another_kind_of_error");
			});
		})
		.Start();

Do you think that could work for you?

This is nice because it leaves all of the error handling etc. to each endpoint, and then it just works as a [message router](http://www.enterpriseintegrationpatterns.com/patterns/messaging/MessageRouter.html) that forwards each failed message to an appropriate queue.
