### ISSUE TITLE
Custom Backoff timers, and Rebus 2.0

### ISSUE THREAD

**Issue by xenoputtss** [rebus-org/Rebus#536]
I recently upgraded from version .9* to 2* (using nuget packages).

I noticed that when we have lots of messages in my queue to process that the first backoff timer was always being used.  I believe previously the behavior was that as long as there was work to be done it would always fetch the next workload right away and it would continue to do this until no work was received.  Then at that point we would being to iterate through the array of backoff timers.

here is how i am configuring rebus
```
            var rc = Rebus.Config.Configure.With(adapter)
                .Logging(l => l.ColoredConsole(LogLevel.Info))
                .Transport(t => t.UseSqlServer(_settings[KioskSettings.BusConnectionString], "Messages", $"Kiosk-{_settings[KioskSettings.KioskId]}"))
                .Routing(r =>
                {
                    var a = r.TypeBased();
                    legacySystemAdapters.Aggregate(a, (current, i) => i.ConfigureBusMappings(current));
                })
                .Options(o =>
                {
                    o.EnableCompression();
                    o.HandleMessagesInsideTransactionScope(); //From Rebus.TransactionScopes
                    o.SetNumberOfWorkers(1);
                    o.SetMaxParallelism(5);
                    o.EnableMessageAuditing("messageAuditQueue");
                    o.SetBackoffTimes(GetCustomBackoffTimers());
                    //o.UseClassicRebusWorkersMessageDispatch();
                });
```
and here is the function for my backoff timers

```
        public static IEnumerable<TimeSpan> GetCustomBackoffTimers()
        {
            return new[]
            {
                //TimeSpan.FromMilliseconds(1),
                TimeSpan.FromSeconds(1),
                TimeSpan.FromSeconds(1),
                TimeSpan.FromSeconds(1),
                TimeSpan.FromSeconds(1),
                TimeSpan.FromSeconds(1),//5 seconds total
                TimeSpan.FromSeconds(5),//10 seconds total
                TimeSpan.FromSeconds(10),
            };
        }
```

**Comment by xenoputtss** [comment]
As you can see in my commented out code, I do have a working hack for this, by putting the first element in the backoff timer array to 1 millisecond, i get the desired behavior.

**Comment by mookid8000** [comment]
I see 🤔 I am going to look at it now

**Comment by mookid8000** [comment]
Hmm, I have played around for an hour now, and I simply cannot get it to call `Wait()` on the back-off behavior thing when the queue has more messages in it.

If there is any way you can reproduce it in a small code snippet, e.g. a unit test or a small console app or something, it would be awesome 👍

**Comment by mookid8000** [comment]
I did some more testing by introducing a fake delay during the receive, in order to simulate the asynchronous receive you have with SQL Server-based transport.

I got some interesting results 😁 

The test consists of three phases:

1. 5 seconds idle
1. Make endpoint process 100k messages
1. 5 seconds idle

### In-mem result

You can see the initial in-mem transport-based result [here](https://gist.github.com/mookid8000/ad1267f5c2ee1fe68b7c20771abd3592) – the stars denote times where `.Wait()` is called on the back-off strategy, IOW a `*` is a time when a worker thread is sleeping.

It clearly shows around 5 seconds of idle time, making threads sleep while there is not work to do.

After that it takes ~ 10 seconds for 100k messages to be processed. No worker is sleeping during this period.

And then, in the end, we are clearly running idle again.

### In-mem result with introduced receive latency

I added a transport decorator which would consequently `await Task.Delay(10);` before delegating the `Receive` call to its inner transport. 

With an infinite number of parallel operations allowed, we should be able to reach the same throughput as without the latency, albeit with an increased time it takes for each message to be handled.

In [this test](https://gist.github.com/mookid8000/9309e15f04675c4e3c8c675dfc56987a) though, I set max parallelism to 500 and executed it.

The `*` still denote when a worker thread is sleeping because it could not receive a message, while the `.` denote when a worker thread is sleeping because it is not allowed to begin a new parallel operation. As you can tell, there will constantly be threads on pause because no more parallel stuff can go on.

### Conclusion

I think by now we can conclude that what you are experiencing is the fact that 1 single worker and 5 parallel operations allowed will sometimes result in pausing a thread even though there is plenty of messages to be handled.

If you think of it, that is perfectly allright.

The situation we have can be sketched like this:

	**********************
	**********************
	**********************
	**********************
	========| * * |=======
	        |*    |
	        |  *  |
	        |    *|

where we have lots of messages coming in, but at any given time we can only have 5 messages being handled.

Since the worker thread is ONLY used to receive a message up until the first real `await` (in SQL Transport's case that happens already inside the transport), the worker needs to pause from time to time even though there are plenty of messages to receive.

I hope that explains it 😁
