### ISSUE TITLE
Events in 2.0

### ISSUE THREAD

**Issue by chandmk** [rebus-org/Rebus#537]
Previous version of configure API was exposing events.  I have a feature that adds message contents to the log, on messge failure by handling OnPoisonMessage event.
What is the equivalent on 2.0?

**Comment by mookid8000** [comment]
yeah.... I realize that this bit has become slightly more involved with the design of the extensibility system in Rebus 2... I will probably add some events similar to those in Rebus 1 at some point, but I haven't done so yet.

At the moment, the easiest way to achieve what you want is to decorate [`IErrorHandler`](https://github.com/rebus-org/Rebus/blob/master/Rebus/Retry/IErrorHandler.cs) – the error handler is the one that gets to do whatever it wants to a failed message. By default the [`PoisonQueueErrorHandler`](https://github.com/rebus-org/Rebus/blob/master/Rebus/Retry/PoisonQueues/PoisonQueueErrorHandler.cs) is responsible for moving the message to the error queue.

You can decorate the error handler by doing this:

	.Options(o => {
		o.Decorate<IErrorHandler>(c => {
			var errorHandler = c.Get<IErrorHandler>();
			return new LoggingErrorHandlerDecorator(errorHandler);
		});
	})

which you should probably wrap in a nice extension method on `OptionsConfigurer` so that it can look nice like this:

	.Options(o => {
		o.LogPoisonMessageContents();
	})

`LoggingErrorHandler` in this case could look like this:

	public class LoggingErrorHandlerDecorator : IErrorHandler {
		readonly IErrorHandler _errorHandler;

		public LoggingErrorHandlerDecorator(IErrorHandler errorHandler) {
			_errorHandler = errorHandler;
		}

		public Task HandlePoisonMessage(TransportMessage transportMessage, ITransactionContext transactionContext, string errorDescription) {
			// do what you want here :)
			// ...
			// don't forget to delegate to the decorated instance:
			return _errorHandler.HandlePoisonMessage(transportMessage, transactionContext, errorDescription);
		}	
	}

where you would probably insert the logging in the `HandlePoisonMessage` method just before it delegates execution to the decorated instance.

I hope that makes sense 😄
