### ISSUE TITLE
Orphaned Subscriptions

### ISSUE THREAD

**Issue by mpaul31** [rebus-org/Rebus#540]
When an endpoint previous subscribes to an event and then later on the bus.Subscribe is removed it seems the subscription is left hanging around in the subscription store for sql server. Here is the error:

Rebus.Exceptions.RebusApplicationException: Message with ID 469c7f7f-9adc-484d-9c3a-7f31564fa84f and type GRP.COR.Management.Messages.Events.EventInfoChanged, COR.Management.Messages could not be dispatched to any handlers

the workaround for now is obviously just removing the record from the table :)

**Comment by mookid8000** [comment]
Yeah well – the way it works, is that subscriptions are intentionally persistent.

This way – once a subscriber has subscribed – it can crash & burn and be restarted after several days of downtime, and it would not lose a single message.

Since there is no way for Rebus to know when you stop a subscriber for the last time (i.e. you are killing it completely), you will need to either have it `await bus.Unsubscribe` when it stops the last time, or you will have to manually remove the subscription from whichever subscription storage you are using.
