### ISSUE TITLE
Worker threads are able to make multiple overlapping calls to ReceiveTransportMessage.

### ISSUE THREAD

**Issue by michac** [rebus-org/Rebus#541]
When running a bus with a max parallelism of 120 and 4 workers and noticed I was experiencing fairly high CPU usage when idle. I believe I've narrowed it down to ThreadPoolWorker.TryAsyncReceive where it awaits ReceiveTransportMessage. When it hits the await it frees the worker thread which invokes the next call to TryReceiveMessage from the Run loop. As long as there are parallel operation slots available the thread makes it back to await ReceiveTransportMessage a second time, which frees the worker thread again and so on. Even when there are no messages the thread continues to start queries to the empty table until the first call to ReceiveTransportMessage finishes and the back off strategy kicks in for a moment.

If I force ReceiveTransportMessage to be synchronous
`var transportMessage = ReceiveTransportMessage(token, context).Result;`
My CPU usage goes down significantly.

**Comment by mookid8000** [comment]
Which transport are you using?

I think this can be explained by the fact that you have 120 logical threads(*) pounding the transport with receive calls.

If you really want this many parallel operations, maybe you should try [customizing the back-off strategy](https://github.com/rebus-org/Rebus/wiki/Back-off-strategy) – my guess is that the perceived latency will still be pretty good even if you make them wait for a second or something while running idle.

I did have a thought some time ago whether it would make sense to have separate parallelisms for the receive part and the dispatch part – I guess that would probably have made a lot of sense in your particular scenario.

--

If the transport does not block the thread, i.e. it supports real async, you can think of the level of parallelism almost as if it was real threads.

**Comment by michac** [comment]
I'm using the SqlServer Transport, which I'm sure contributes to the problem since I imagine that's a relatively expensive receive operation.

In my case I ended up with high level of parallelism because I'm making network calls to clients in response to messages, and some of those network calls were timing out (effectively blocking a 'logical thread' for 60 seconds). With thousands of clients I didn't want a small percentage of timeouts to block the whole bus, so I naively cranked up the parallelism without considering the other potential consequences.

The only problem with customizing the back-off strategy, if I understand the code correctly, is the back-off strategy is applied to the worker threads not the parallel operations (logical threads). So even if I have it wait longer when backing off I'll still get bursts of queries every time a worker thread frees up and consumes as many parallel operation slots as it can before the first query returns and the back-off strategy kicks in.

* What if the back-off strategy included the ability to force a synchronous queue check if the last time the worker thread checked there were no messages?
* What if the SqlServer transport code had a setting that allowed you to force synchronous receive calls (essentially tying max parallelism for receives to worker threads)?
* What if max parallelism didn't apply to the receive part but only to the dispatch part? I admit this is very biased based on my situation, but I always considered the cool part of the parallelism setting was that it allowed me to have more dispatch operations going at once.
* Having the ability to set a parallelism just for the receive part would definitely solve my problem, although I worry about implementing a whole second parallelism check.

I will probably make a local change to try out one of these options, would you be interested in seeing what I end up with?

Also thank you so much for your work on Rebus, it's been very helpful and a pleasure to use.

**Comment by mookid8000** [comment]
> I'm using the SqlServer Transport, which I'm sure contributes to the problem since I imagine that's a relatively expensive receive operation.

You bet 😄 especially if you want to do 120 of them in parallel!

> In my case I ended up with high level of parallelism because I'm making network calls to clients in response to messages, and some of those network calls were timing out (effectively blocking a 'logical thread' for 60 seconds). With thousands of clients I didn't want a small percentage of timeouts to block the whole bus, so I naively cranked up the parallelism without considering the other potential consequences.

I can definitely understand then why you did what you did. If it is possible, I would consider making those network calls in a separate endpoint, the view being that dangerous things that can affect other things should be isolated somehow – at least by Rebus instance, maybe by OS process, or in some cases even by machine boundary.

---

I realize now btw what is causing the high CPU load – it's because the SQL transport is using an "async bottleneck" with a hard-coded limit of 20 parallel receive operations.

The bottleneck is implemented with `SemaphoreSlim`, which uses a spinlock for a short while when it tries to decrease the semaphore. This means that at any point in time, you will most likely have every single Rebus worker thread busy-waiting in an attempt to decrease the semaphore while 20 async receive attempts are being carried out.

The reason the "async bottleneck" was introduced, was that my initial testing with the SQL transport revealed that it was extremely easy for it to completely use up all available SQL connections in the pool, which resulted in timeouts each time a connection attempt was made.

Since the [maximum number of connections in the ADO.NET connection pool is 100](https://msdn.microsoft.com/en-us/library/8xx3tyca(v=vs.110).aspx), and the pool is shared among all things running in that particular AppDomain, I wanted to set it much lower than 100, while still preserving some room for parallelism. 20 seemed a good hard-coded default at that time 😄

**Comment by michac** [comment]
Ah, that makes sense! I did notice the async bottleneck and read up on the SemaphoreSlim, but didn't quite put together that the spin lock was likely what was causing the CPU load.

The more I think about it I agree with your assessment that I should isolate the network calls. I'm currently considering having the network call kicked off but not awaited, then have it send follow up messages when it finishes (possibly with a timeout message in case I don't hear back). This will let me set the max parallelism to a much more reasonable level.

I did end up tweaking my version of Rebus (the SQL transport specifically) to make the receive calls synchronous and it's been performing well that way, I will make it something I can toggle with configuration and leave it in for now. It does make it less aggressive at querying the message table while idling (limiting it to real threads vs logical threads), assuming I'm not totally misinterpreting my test results :). The fact that your architecture makes tweaking the transport so easy certainly helps.

Thanks for your help and feedback on this, I'll go ahead and close this since I don't think I've identified any issues that need to be tracked further.
