### ISSUE TITLE
How to handle long type names

### ISSUE THREAD

**Issue by hulvei3** [rebus-org/Rebus#558]
Hi.

Just a question. We are seeing some problems when using sql transport and type-based handling, where long namespaces is cropped. Not sure if I just missed something here, but this seems like a (stupid) problem.

Any suggestions to what I can do (/doing wrong)

**Comment by mookid8000** [comment]
It's not entirely clear which symptoms you are experiencing....

Due to [a limit in SQL Server](https://msdn.microsoft.com/en-us/library/ms191241.aspx) Rebus creates its subscriber table with topic and subscriber address columns that are 200 characters wide.

I would expect SQL Server to throw an exception if an attempt was made to insert anything that is longer than 200 characters... therefore it is not clear to me what is actually cropped in your case?

**Comment by hulvei3** [comment]
First of all. Sorry for posting this here. Can see that there's a SO topic for this.
Second, I explained it a bit wrong.

Pub/sub is working fine for us. I my questions is more a worry if long namespaces would result in wrongly type-based matching when you have subscribed to a specific event-type.
Example:

I'm using SQL as my subscription storage and publishing a message that is of type
`My.Very...............Long.Namespace.Event.Domain.SomethingUpdated`.

I then subscribe to that event on the other side. What happens when you have namespaces that is so long that the topic would be capped, because of that exact limitation?

I.e. `My.Very...............Long.Namespace.Event.Domain.Som`

**Comment by mookid8000** [comment]
> Pub/sub is working fine for us. 

Good – I am happy to hear that 😃 

> my questions is more a worry if long namespaces would result in wrongly type-based matching when you have subscribed to a specific event-type.

~~I think SQL Server would give you a slap in the face when you `await bus.Subscribe<SomeType>()` if the simple assembly-qualified type name of `SomeType` exceeds 200 characters in length.~~

WTF?! I was convinced that SQL Server would object to having a > 200 char string inserted into an `NVARCHAR(200)` column because I knew of the 

    Msg 8152, Level 16, State 4, Line 1
    String or binary data would be truncated.
    The statement has been terminated.

error from SSMS, _but it looks like SQL Server will happily go "thanks, idiot, for your data you, let me silently take a 200-character prefix of it and throw the rest of your valuable information out of the window"_ when the insert is done by ADO.NET........ I cannot imagine any good reasons why it is so.... Frankly, this is quite shocking!

Because of dumb luck Rebus will get the correct subscribers long topics _as long as the 200-char topic prefix does not collide with another 200-char topic prefix_. This means that you might be lucky and things will just work, or – if you have topic names as long as in my test:

    Rebus.SqlServer.Tests.Subscriptions.This.Is.Just.An.Incredibly.Long.And.Silly.Namespace.Name.That.Needs.To.Be.Even.Longer.Because.It.Just.Needs.To.Be.Long.OK.But.Soon.It.Must.Be.Long.Enough.To.Exceed.That.Silly.Limit.In.SqlServer.SomeClass, Rebus.SqlServer.Tests

it will be equivalent to

    Rebus.SqlServer.Tests.Subscriptions.This.Is.Just.An.Incredibly.Long.And.Silly.Namespace.Name.That.Needs.To.Be.Even.Longer.Because.It.Just.Needs.To.Be.Long.OK.But.Soon.It.Must.Be.Long.Enough.To.Exceed.

which does not even contain the class name.... so, as you can see, there's potential for collisions here... 😱 

For now, I will update the SQL Server subscription storage with the ability to throw an exception if a topic exceeds the 200-character limit. It will be out in Rebus.SqlServer 2.1.0-b02 in a few minutes.

This is disappointing.

**Comment by hulvei3** [comment]
Glad that it was not just me then :)

Cool with the explicit exception, but I guess this calls for either a custom serialization of the topics or another kind of subscription storage (maybe even just a key/value store).

Thanks for looking into this.

**Comment by mookid8000** [comment]
> Glad that it was not just me then :)

It's not you, it's me.

> Cool with the explicit exception, but I guess this calls for either a custom serialization of the topics or another kind of subscription storage (maybe even just a key/value store).

Rebus.SqlServer 2.1.0-b02 will reflect over the schema at startup and throw appropriate exceptions if you try to register a subscriber for a topic that is too long.

After the table has been created, you can change the size of the columns to e.g. 350/50, which will then give you 350 chars for the topic and 50 for the subscriber address (which – at least in my experience – is usually considerably shorter than fully qualified .NET type names).

Please keep in mind that SQL Server [has a max 900 byte index size](http://dba.stackexchange.com/questions/122000/why-sql-server-has-900-byte-index-size-limit) which means that the values of the two columns combined in each row cannot take up more than 900 bytes in storage space.

I will create an issue on making the sizes of the columns configurable.

> Thanks for looking into this.

Thanks for taking the time to report the issue 😃

**Comment by hulvei3** [comment]
👍
