### ISSUE TITLE
Please mark DefaultTransactionContext as serializable

### ISSUE THREAD

**Issue by JornWildt** [rebus-org/Rebus#559]
I have an issue with DefaultTransactionContext: we are trying to execute some code externally inside a separate assembly. Something along the lines of using AppDomain.CreateDomain to create a new AppDomain, Activator.CreateInstanceFrom to create a class instance and then invoke a method on that class inside the new AppDomain.

Now, apparently, .NET needs to serialize "all objects directly attached to the thread" and transfer them to the other AppDomain - and, tada ... DefaultTransactionContext is on the thread, as the ambient transaction, as gets serialized - but that is not possible as it is not marked as serializable and boom! we get an exception.

See this old post for some info: http://www.lhotka.net/weblog/PermaLink,guid,cfcaf6c4-63cf-4cf1-8361-ed3db07496a4.aspx

I am no expert in these matters but transfering the transaction context doesn't make sense as I would expect it to be unusable to the other AppDomain. None the less .NET insists on doing it - breaking code that previous worked :-(

Could DefaultTransactionContext please be marked as serializable? It probably also needs a default constructor.

**Comment by mookid8000** [comment]
> Could DefaultTransactionContext please be marked as serializable? It probably also needs a default constructor.

Unfortunately, no. The transaction context mainly consists of a `Dictionary<string, object>` which is used by various Rebus components to track _instances of whatever_, which in many cases are instances of non-serializable things. This could be e.g. MSMQ's `MessageQueueTransaction`, an `SqlConnection`, etc. So my guess is that marking `DefaultTransactionContext` as serializable would simply lead to another exception caused by a non-serializable object somewhere.

This suggestion has been made before by people who were juggling appdomains like you are 😁  (and by people who found out that initializing Entity Framework will apparently do something in a separate appdomain too)

Check out [this StackOverflow answer](http://stackoverflow.com/a/34021143/6560) for some more words on this thing + a suggested solution that is as clean as it can get.

**Comment by JornWildt** [comment]
Thanks, worked for me :-)

**Comment by s-drki** [comment]
I'm new in Rebus and I,m studying document,

As far as I've learned till now, Rebus supports transaction scope using "scope.EnlistRebus()" at transmitter side and "option.HandleMessagesInsideTransactionScope(...)" at handler side. So If I want to have a transaction scope at transmitter/handler side (for example dealing with SqlTransaction - DB write/read- side), two above methods is enough. Isn't it? So what is exact use of DefaultTransactionContext?
