### ISSUE TITLE
Timeout Manager questions

### ISSUE THREAD

**Issue by stevengopmo** [rebus-org/Rebus#564]
Hi,  I have a number of timeout manager questions.  Probably some could be opened as separate issues and I will if you would like.  Here they are in no particular order.

- does the external timeout manager for 2.x still work as described in your long ago posts on it (http://mookid.dk/oncode/archives/3421)

- having asked that, do I understand correctly that the external manager just sends the message back to the appropriate place when the timeout occurs?

- reading the docs it appears SQL Server does not require a timeout manager because SQL transport has built-in message deferral (#555).  It seems this should be possible for any of the database based transports, true?

- You have storage for RavenDB but it does not include a Transport.  Is there a particular issue or just time?

- I'm using the in-memory timeout manager with RavenDB as storage.  It seems that that timeouts are removed from storage before processing is complete and in the case of an error or shutdown of the service the 'next' timeouts are lost.  For example my code gets the timeout tries to do some processing then sets another timeout. but for some reason I no longer see the timeouts in the db.  Now that I've type it all, it sounds maybe my code problem :)

- This last may be an edge case...  I'm using RavenDB for storing my timeouts and it depends on a store singleton (my DI container is SimpleInjector).  The store has a Listener that depends on something that is context specific.  In this case the specific details of the principal retrieved from details in the message.  Is there a place where I can capture the request for the timeout manager so I can begin the execution scope and pass it the specific principal I need?  I hope that makes sense.

**Comment by mookid8000** [comment]
> Probably some could be opened as separate issues and I will if you would like.

Nah, I'll just answer them here quickly 😄 

> does the external timeout manager for 2.x still work as described in your long ago posts on it (http://mookid.dk/oncode/archives/3421)

yes and no ... there's no ready-made timeout manager anymore, because each Rebus endpoint can work as a timeout manager now.... if you want a dedicated timeout manager, just start an "empty" endpoint and treat it like your dedicated centralized timeout manager, because that will be it then

> having asked that, do I understand correctly that the external manager just sends the message back to the appropriate place when the timeout occurs?

yes... to be more precise, the timeout manager will return the message to the queue specified by the `rbs2-return-address` header, which by default will be the input queue of the sender, _unless you explicitly set it something else_ (which is how you can send delayed messages to other queues) 

> reading the docs it appears SQL Server does not require a timeout manager because SQL transport has built-in message deferral (#555). It seems this should be possible for any of the database based transports, true?

I guess that is true... however, if the database happens to support some kind of pessimistic locking, that makes it much easier to share a timeout storage... e.g. if multiple timeout managers are using the same table in a central SQL Server, they will NOT snatch each other's timeouts because the SQL Server timeout manager will grab a lock on the rows 

> You have storage for RavenDB but it does not include a Transport. Is there a particular issue or just time?

Mostly because RavenDB does not support any kind of pessimistic locking. Competing consumers (even just multiple threads in the same process competing for messages) would snatch each other's messages.

The RavenDB timeout manager has this "problem" too, so it will NOT work with multiple timeout managers sharing the same RavenDB database.

> I'm using the in-memory timeout manager with RavenDB as storage. It seems that that timeouts are removed from storage before processing is complete and in the case of an error or shutdown of the service the 'next' timeouts are lost. For example my code gets the timeout tries to do some processing then sets another timeout. but for some reason I no longer see the timeouts in the db. Now that I've type it all, it sounds maybe my code problem :)

yeah well.... I am pretty sure that [this code](https://github.com/rebus-org/Rebus.RavenDb/blob/master/Rebus.RavenDb/Timouts/RavenDbTimeoutManager.cs#L48-L75) defers the deletion of the timeout documents until AFTER the due messages have been sent

> This last may be an edge case... I'm using RavenDB for storing my timeouts and it depends on a store singleton (my DI container is SimpleInjector). The store has a Listener that depends on something that is context specific. In this case the specific details of the principal retrieved from details in the message. Is there a place where I can capture the request for the timeout manager so I can begin the execution scope and pass it the specific principal I need? I hope that makes sense.

it sounds a little bit involved... but yet, all incoming messages are passed through the [incoming messages pipeline](https://github.com/rebus-org/Rebus/wiki/Incoming-messages-pipeline) which you can inspect by [logging its contents](https://github.com/rebus-org/Rebus/wiki/Log-message-pipelines) and then you can [inject a step into it](http://mookid.dk/oncode/archives/3938) that establishes whichever context is required

**Comment by stevengopmo** [comment]
sorry for so late a reply, I had to noodle your answers for a bit.

> if you want a dedicated timeout manager, just start an "empty" endpoint
I'm sorry but what do you mean by "empty endpoint", a separate service?

> if the database happens to support some kind of pessimistic locking, that makes it much easier to share a timeout storage
It seems SQL Server is a much better option that RavenDB for this particular purpose, assuming SQL Express works the same I'll probably switch to this for timeout handling

Thanks for answering all my questions, I'll play with the last item as I think I got it now and if not I can ask in a more specific issue.

**Comment by mookid8000** [comment]
> I'm sorry but what do you mean by "empty endpoint", a separate service?

Yes 😄 

> It seems SQL Server is a much better option that RavenDB for this particular purpose, assuming SQL Express works the same I'll probably switch to this for timeout handling

SQL Express is even better because it's free 😉 and because of that you have more flexible deployment options, i.e. you don't need to worry about licenses if you e.g. want a local SQL Express on each machine hosting Rebus endpoints.

> I'll play with the last item as I think I got it now and if not I can ask in a more specific issue.

Feel free to return if you have questions, suggestions, etc.
