### ISSUE TITLE
Is it possible to add something to my IoC container from within a pipeline?

### ISSUE THREAD

**Issue by robvanpamel** [rebus-org/Rebus#574]
Hello, 

Is it possible to add something to my IoC container from within a pipeline?

For a project i'm working on, we are using SAASKIT to enable multi-tenancy. This will Register an apptenantContext resolverin the IoC at the beginning of the Http Pipeline. So when we want to know for which tenant we are working, this can be injected any-time. See https://github.com/saaskit/saaskit for more information.

I wonder if I can achieve the same functionality with Rebus. I saw i can Register some things done in the OptionsConfigurer but i don't think this is the correct place. Could you give me some guidance where to seek. 

Kind regards
  Rob

**Comment by mookid8000** [comment]
Hi Rob, I would say that it depends on which IoC container you are using and how it is supposed to be used.

With Castle Windsor (which is usually the container I am using) you would NEVER register anything in the container while the application is running, you would only do that when it starts.

In order to be able to resolve context-dependent things, you would probably register an implementation of a service as a factory method which then gets to look at the current context to make decisions about which implementation to return.

With Rebus you can access the current message context by using the static `MessageContext.Current` property, which you could then access in the factory method to e.g. check the headers of the incoming message and resolve something depending on that.

I hope that could provide a little bit of guidance :)

**Comment by robvanpamel** [comment]
Hi @mookid8000 , 

Thanks for the guidance. I didn't require to set anything in the IoC container anymore but could achieve the desired functionality with a factory in combination with MessageContext.

Thanks for the advice!

Kind regards
  Rob
