### ISSUE TITLE
Centralized Storage and Publish

### ISSUE THREAD

**Issue by stevengopmo** [rebus-org/Rebus#575]
This is more of a philosophy question.  If I am using a transport that supports centralized subscriptions, is there any reason I shouldn't be able to publish even when configured as a one way client?

For example 

            Configure
                .With(adapter)
                .Options(o =>
                {
                    o.SimpleRetryStrategy("Messages.Errors", 5, true);
                })
                .Transport(s => s.UseSqlServerAsOneWayClient("SQLMessageQueue", "RebusMessages"))
                .Routing(r => r.TypeBased().MapAssemblyOf<CreateProject>("Service"))
                .Start();

I'm not sure why a publisher needs to be a standard transport over one way but I think it may have to do with acknowledgement maybe?  But if subscription is centralized maybe that requirement could go away?

**Comment by mookid8000** [comment]
A publisher needs an input queue if you are NOT using centralized subscription storage, because subscribers establish their subscriptions by sending `SubscribeRequest` messages to the publisher.

This is the reason why subscribers need endpoint mappings that map events to their respective publishers.

When using a centralized subscription storage this requirement goes away, because the subscriber can simply subscribe by registering itself, and the publisher will find the subscribers when it queries for subscribers the next time.

You are definitely right that a publisher can be a one-way client – it just needs a subscription storage that has something in it. Using a centralized subscription is the easy way to do this 😄 but one could also imagine scenarios where a publisher is deployed with an accompanying JSON file that holds the subscriptions, which you would then edit as new subscribers enter the scene.

I hope that makes sense 😄

**Comment by stevengopmo** [comment]
It does make sense. So why doesn't publish work when I have my SQL transport configured as one way?

**Comment by mookid8000** [comment]
If you are running with the configuration shown above, you need the `.Subscriptions(...)` configuration spell, e.g. like so:

    Configure
        .With(adapter)
        .Options(o =>
        {
            o.SimpleRetryStrategy("Messages.Errors", 5, true);
        })
        .Transport(s => s.UseSqlServerAsOneWayClient("SQLMessageQueue", "RebusMessages"))
        .Subscription(s => s.StoreInSqlServer(connectionString, "Subscriptions", isCentralized: true))
        .Routing(r => r.TypeBased().MapAssemblyOf<CreateProject>("Service"))
        .Start();

**Comment by stevengopmo** [comment]
Ah... the missing ingredient. Thanks!

**Comment by mookid8000** [comment]
You're welcome 😄
