### ISSUE TITLE
JSON Deserialize error when no default constructor. [JsonConstructor] attribute ignored? Newtonsoft.Json embedded in Rebus DLL the issue?

### ISSUE THREAD

**Issue by jonathanyong81** [rebus-org/Rebus#587]
Using Rebus 3.1.0 (and 2.1.6) we are having JSON deserialization errors. We have removed default constructors from our classes in order to enforce that the objects are valid and fully populated when constructed. We have placed a [JsonConstructor] attribute on our parameterized constructor.

System.FormatException: Could not deserialize JSON text: {some json here}. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute.

We have tested by directly calling JsonConvert.Deserialize() from Newtonsoft.Json 9.01 and confirmed that it deserializes correctly.

I have also downloaded the Rebus 3.1.0 source code and locally compiled the Rebus DLL. When I use this locally compiled version the deserialization works correctly. But when I use the Rebus DLL from nuget it does not.

Using ILSpy I see that the version from nuget has all of the Newtonsoft.Json namespaces and classes merged into the assembly whereas the locally compiled version does not. I see in build-package.cmd the comment "HACK - merge Newtonsoft into Rebus.dll". I believe this is the reason the deserialization is failing.

Why are the Newtonsoft.Json classes merged into the Rebus assembly? And what version of Newtonsoft.Json has been merged?

Our only option seems to be to forego the use of nuget when refrencing the Rebus assembly and to instead reference the Rebus projects from the source code.

Could you please offer some guidance on this? Thanks.

**Comment by mookid8000** [comment]
> Why are the Newtonsoft.Json classes merged into the Rebus assembly? 

Because the Rebus core assembly can then come without any dependencies at all and be completely self-contained. This is a core principle.

> And what version of Newtonsoft.Json has been merged?

It would not help you if you knew 😄 the JSON serializer would not recognize the attribute, because the attribute it is looking for is the one in the Rebus assembly.

If you want to customize the JSON serialization, you can include the [Rebus.NewtonsoftJson](https://www.nuget.org/packages/Rebus.NewtonsoftJson/) package – then the Newtonsoft.Json package will be pulled in for real, and it will react to the [JsonConstructor] attribute (just remember to make Rebus actually USE the serializer like this:

    Configure.With(....)
        .(...)
        .Serializer(s => s. UseNewtonsoftJson())
        .Start();

**Comment by jonathanyong81** [comment]
Ok thanks for the response. Glad there's a supported workaround!
