### ISSUE TITLE
Saga correlation not working for nested properties

### ISSUE THREAD

**Issue by JornWildt** [rebus-org/Rebus#588]
We had the following code working in earlier versions of Rebus (2.X something early):

    Incoming<MatterInvalidFlowCommand>(m => m.Matter.Id).CorrelatesWith(d => d.Matter.Id);

After upgrading to Rebus 3 we have this code:

    config.Correlate<MatterInvalidFlowCommand>(msg => msg.Matter.Id, saga => saga.Matter.Id);

But now it does not work anymore as Rebus comes up with something like "Cannot find Matter.Id on class MatterInvalidFlowCommand" - meaning, it sees "Matter.Id" as a single identifier which is not the case.

So, at some point Rebus lost the ability to use nested properties for sage correlation. Could we please get that back? Thanks.

**Comment by mookid8000** [comment]
Hmm, the fact that this used to work cannot be attributed to anything but dumb luck 😁 

The reason it doesn't work now, is because of the new helpful type-checking function that ensures that you don't try to correlate with properties with unsupported types by accident.

I'll see what I can do... it'll be out in Rebus 4 if I can make it work in a way where I can guarantee that it behave nicely with all saga persisters.

Until then I suggest you use this easy workaround:

    public class ImportantMattersSagaData : SagaData {
        public Matter Matter { get; set; }    

        // check this out:
        public string MatterId => Matter?.Id;
    }

    public class Matter {
        public string Id { get; set; }
    }

and then your correlation must be changed from

    config.Correlate<MatterInvalidFlowCommand>(msg => msg.Matter.Id, saga => saga.Matter.Id);

into

    config.Correlate<MatterInvalidFlowCommand>(msg => msg.Matter.Id, saga => saga.MatterId);

**Comment by mookid8000** [comment]
I've changed my mind – Rebus 3.1.2 will be out shortly, it should work the way you expect it to.

**Comment by mookid8000** [comment]
it's out now 😄 

thanks for reporting this issue

**Comment by JornWildt** [comment]
Thanks. Just for the record, converting "Matter.Id" to "MatterId" would not work with existing (long lived) sagas as it would be impossible for Rebus to locate the old sagas with the "Matter.Id" format.
