### ISSUE TITLE
Support for SqlCe

### ISSUE THREAD

**Issue by Jeern** [rebus-org/Rebus#591]
It would be great with a package for SqlServer Compact (e.g. Rebus.SqlCe) similar to Rebus.SqlServer for development environments. I currently use SqlServer in Azure, but prefer to have something simple and totally local on the development machine.

There are probably only a few differences. I.e. use nvarchar instead of varchar. And use System.Data.SqlServerCe instead of System.Data

**Comment by mookid8000** [comment]
as suggested, this is best done in a separate `Rebus.SqlCe` package because of the dependency on [Microsoft.SqlServer.Compact](https://www.nuget.org/packages/Microsoft.SqlServer.Compact).

If the code is so similar, it could probably easily start out by simply copying the code from [Rebus.SqlServer](https://github.com/rebus-org/Rebus.SqlServer)

**Comment by mookid8000** [comment]
work is ongoing [here](https://github.com/rebus-org/Rebus.SqlServerCe)
