### ISSUE TITLE
"The message could not be dispatched to any handlers", with secondLevelRetriesEnabled=true

### ISSUE THREAD

**Issue by luferogo** [rebus-org/Rebus#592]
Hello, 
I am not sure this is an issue, or maybe a misconfiguration somewhere.

1. I downloaded a copy of https://github.com/rebus-org/RebusSamples/tree/master/Integration
2. I modified to use Amazon SQS.
3 Tested, The automatic retries worked fine. 
4. I am playing with error handling. So, I configured (both, client and integrationservice) to use :
` .Options(o => o.SimpleRetryStrategy(maxDeliveryAttempts : 2, errorQueueAddress : "IntegrationSample-errors", secondLevelRetriesEnabled : true)) `
Please note I set maxDeliveryAttempts=2 to increase the probability of a second level of retry.
5. I added a new handler method:
`public async Task Handle(IFailed<GetGreetingRequest> failedMessage)
        {
            Console.WriteLine(">>>Error message received, handling the second level of retry...");
            await _bus.Defer(TimeSpan.FromSeconds(5), failedMessage.Message);
        }`
6. Tested with the following results:
- When the web service failed twice, the handler was triggered correctly.
- The defer() method tried again (after 5 secs) to execute the request.
- When the web service responded successfully for the second time, the message never came back to the client. The error logged is:

> 2 unhandled exceptions: 3/21/2017 12:42:18 PM -07:00: Rebus.Exceptions.RebusApplicationException: Message with ID aeab20d0-8734-419f-8a13-f6ae378c7140 and type IntegrationSample.IntegrationService.Messages.GetGreetingReply, IntegrationSample.IntegrationService.Messages could not be dispatched to any handlers

Somehow the handler registration was broken on the client.... Is this an expected behavior? 

Note: If I set secondLevelRetriesEnabled = false, all works fine.

**Comment by mookid8000** [comment]
Does your handler implement the `IHandleMessages<IFailed<GetGreetingRequest>>` interface?

Is it resolved when you resolve all implementations of `IHandleMessages<IFailed<GetGreetingRequest>>` from your container?

**Comment by mookid8000** [comment]
Sorry, I deleted the other answer – I skimmed your question too quickly the first time around.

It sounds a little bit weird – if you send me the code (e.g. by pushing it to a GitHub repo), I will be happy to debug it.

**Comment by luferogo** [comment]
Of course, that would be awesome!
I invited to https://github.com/luferogo/RebusIntegration/.
Thanks

**Comment by mookid8000** [comment]
I checked it, and I found the problem 😄 

In your second-level handler of `IFailed<GetGreetingRequest>` you do this:

    public async Task Handle(IFailed<GetGreetingRequest> failedMessage)
    {
        Console.WriteLine(">>>Error message received, handling the second level of retry...");

        await _bus.Defer(TimeSpan.FromSeconds(5), failedMessage.Message);
    }


but when you `await bus.Defer` a message, its return address will be set to the return address of the endpoint currently handling the message (`IntegrationSample-IntegrationService-input` in this case), which means that when the request arrives again and we `await bus.Reply` we will end up sending the reply to `IntegrationSample-IntegrationService-input`.

If you look carefully, you will also see an error message saying `Message with ID 8f19776b-9eb1-4494-9490-6f80a8c47eb0 and type IntegrationSample.IntegrationService.Messages.GetGreetingReply, IntegrationSample.IntegrationService.Messages could not be dispatched to any handlers`, implying that the reply was suddenly sent to the server instead of back to the client.

The solution is to (1) either manually attach the correct return address to the message:

    public async Task Handle(IFailed<GetGreetingRequest> failedMessage)
    {
        Console.WriteLine(">>>Error message received, handling the second level of retry...");

        await _bus.Defer(TimeSpan.FromSeconds(5), failedMessage.Message, new Dictionary<string, string>
        {
            {Headers.ReturnAddress, _messageContext.Headers[Headers.ReturnAddress]}
        });
    }

or simply to (2) defer the entire message while preserving its headers:

    public async Task Handle(IFailed<GetGreetingRequest> failedMessage)
    {
        Console.WriteLine(">>>Error message received, handling the second level of retry...");

        await _bus.Advanced.TransportMessage.Defer(TimeSpan.FromSeconds(5));
    }

While (1) is an acceptable solution, I simply included it because it shows the mechanics involved in controlling who gets our replies. I would use solution (2) myself because it preserves all of the original headers, and thus message identity, and some other good stuff.

I hope it is pretty clear 😄  

---

btw in order to make solution (1) work, I set up injection of the current `IMessageContext` like this:

    public GetGreetingRequestHandler(IBus bus, HttpClient httpClient, IMessageContext messageContext)
    {
        _bus = bus;
        _httpClient = httpClient;
        _messageContext = messageContext;
    }

**Comment by luferogo** [comment]
Thank you very much for your help!   It is clear indeed.
