### ISSUE TITLE
[Question] Is ReBus good for my requirements?

### ISSUE THREAD

**Issue by vdecristofaro** [rebus-org/Rebus#595]
Scenario
I have two Asp.Net applicazioni: first one is a web api and the second one a regular mvc web site.

I have the following requirements:
1. from the web api I need to raise some events that will be offloaded to the mvc web site for compute
2. The messages exchanged should be threated as transactional. That is, the message should be considered handled only if the receiver confirm the handling
3. Messages should be either synchronous as well as asynchronous

I am using Ninject in both solutions. Could you please vive any hint on:
- the most applicable transport to use considerino that I'm on Azure?
- how to setup client (web api) and backend (mvc)?

Thanks a lot for this work.

**Comment by mookid8000** [comment]
Hi @vdecristofaro ,

> the most applicable transport to use considerino that I'm on Azure?

Rebus does what it can to behave in the same way, no matter which transport you are using. Since you are in Azure, I suggest you use the transport for Azure Service Bus. You can also use the Azure Storage Queues transport.

> how to setup client (web api) and backend (mvc)?

I have documented most parts of Rebus on [the wiki](https://github.com/rebus-org/Rebus/wiki), so I recommend you go there and read a little bit about it. E.g. check out the [Getting Started](https://github.com/rebus-org/Rebus/wiki/Getting-started) page.
