### ISSUE TITLE
SQL Transport Locking

### ISSUE THREAD

**Issue by stevengopmo** [rebus-org/Rebus#609]
Hi,

When I am looking at the messages table in SQL using SQL Management Studio sometimes the returns results are VERY slow.  For instance in my very small table of not even 20 rows, the "SELECT TOP 1000..." in studio took over 30 seconds to run.  This is only while a message is being processed of course.  It seems that Rebus is locking the table for this whole operation which does take a while to run.  Is this just because Studio or does this sound like I have something configured wrong?

I know there's been lots of discussions around the SQL Locking (Row with Snapshot etc) but I didn't really see an answer to this problem I'm seeing.

**Comment by mookid8000** [comment]
I think the problem is that a simple `SELECT TOP 1000 * ...` waits on the first locked row it meets, meaning that it will always be waiting if you have messages being handled.

If you check out [the select that Rebus uses](https://github.com/rebus-org/Rebus.SqlServer/blob/master/Rebus.SqlServer/SqlServer/Transport/SqlServerTransport.cs#L239-L260) you will see that Rebus uses the `ROWLOCK` and `READPAST` hints, meaning that it will only lock a single row (the received message) and it will happily skip already-locked rows in its search for the next row to lock & receive.

If you add the `READPAST` hint to the `SELECT` like this

    SELECT TOP 1000 * FROM [Messages] WITH (READPAST)

it will skip the locked rows and show the rest.
