### ISSUE TITLE
Limit workers CPU usage?

### ISSUE THREAD

**Issue by hbiarge** [rebus-org/Rebus#616]
When a message handler has hard work to do, it consumes 100% of available CPU. Are there any configuration in Rebus to limit the % of CPU that the worker threads can consume?

Thanks!

**Comment by mookid8000** [comment]
Not at the moment, no.

How do you think such feature could be implemented?

**Comment by hbiarge** [comment]
As far as I have investigated it seem prety difficult in .Net itself. You can play with the Proccess priority but it seems it could have undesired collateral effects.
As it is explained in this thread on Stack Overflow ([https://stackoverflow.com/questions/9793359/can-you-limit-the-cpu-usage-on-a-net-process-object](https://stackoverflow.com/questions/9793359/can-you-limit-the-cpu-usage-on-a-net-process-object)) there are an API in the native kernell32.dll that coud help, but I need to test the sample code to really understand its implications.

**Comment by mookid8000** [comment]
That seems to change the behavior of the entire process. Doing that is IMO out of scope for Rebus for several reasons.

I initially thought that it might be possible to change the priority of the spawned worker threads, but after the first `await` (possible happening initially, when the transport received a message) all the work continues on the .NET thread pool.

It is generally not advised to mess with the threads in the thread pool because of its sophisticated inner workings.

If you are worried about CPU usage when your Rebus endpoint has hard work to do, I suggest you reduce the number of worker threads it uses, and possibly also increase the wait time between checking for messages if you care about CPU usage when idle:

    Configure.With(...)
        .(...)
        .Options(o => {
            o.SetNumberOfWorkers(1);
            o.SetMaxParallelism(1);
            o.SetBackoffTimes(
                TimeSpan.FromMilliseconds(100),
                TimeSpan.FromMilliseconds(200),
                TimeSpan.FromMilliseconds(500)
            );
        })
        .Start();

(Rebus defaults to wait 100 ms between checking the transport the first 10 s of running idle, and then it waits 250 ms the rest of the time)

**Comment by hbiarge** [comment]
Yes, I think you are right. It's not responsability of Rebus but of it's containing proccess.

Thank you very much!
