### ISSUE TITLE
Send as part of existing async call context

### ISSUE THREAD

**Issue by SaltyDH** [rebus-org/Rebus#619]
I'm trying out Rebus on a dot net core 1.1 code base at the moment. 

Because we don't currently have transaction scopes, I'm struggling to find a way to send a message in a durable, atomic way. In my use case, the storage queue is the same Sql database as the business data I'm also persisting so I was hoping to send the message on the same connection and transaction as the rest of the data. To access the existing connection, I wanted to use AsyncLocal but the SqlTransport resolves the connection via a separate async call context.

As this relates to dot net core, I thought it better to post here rather than say Stack Overflow.

Cheers!

**Comment by mookid8000** [comment]
I think it is possible to supply an already opened connection to the transport by using [this overload](https://github.com/rebus-org/Rebus.SqlServer/blob/master/Rebus.SqlServer/Config/SqlServerTransportConfigurationExtensions.cs#L24) when configuring the transport.

Could you try that out and see if it would work?

**Comment by SaltyDH** [comment]
That's in fact the method I'm using. I've added the connection I want to use to an async local variable just prior to the call to bus.Send. Unfortunately when the connection factory is called it seems to be a different async call context so I don't have access to my async local value.

**Comment by mookid8000** [comment]
Hi @SaltyDH , I apologize for the late reply – I have just returned from Summer vacation 🍺 🍷 🌞 

I went and thought about your problem, and while I was pretty sure that it could be solved, I could not remember having done it myself ever.

Therefore I created the new [SQL ALL THE WAY sample](https://github.com/rebus-org/RebusSamples/tree/master/SqlAllTheWay) which demonstrates how to do these things.

It uses `CallContext.LogicalSetData`/`.LogicalGetData` though because I was using .NET 4.5. It should work the same with `AsyncLocal`

Please check out the sample and see if you can adapt it to your needs.

**Comment by SaltyDH** [comment]
Thanks very much for taking the time to look at this. I wanted to report back that I have been successful in getting this to work as you've described in the SQL ALL THE WAY sample.

Really appreciate the time taken to look at this!

**Comment by mookid8000** [comment]
It makes me very happy to hear that 😎👌
