### ISSUE TITLE
Transport options are ignore during creation of ErrorQueue

### ISSUE THREAD

**Issue by robvanpamel** [rebus-org/Rebus#625]
Hi, 

Previously i created an option to skip Creation of queue's during Initialization. For this an additional property CreateQueue's was created. This works fine in AmazonSQS when creating the default queue, however for the errorQueue this property is ignored. 

I would like to fix this myself, but i can't find where to start :)  I don't see where the RetryStrategy is creating a new queue ? It is being redirected to AmazonSQS, but i assume it doesn't pick up the previous settings. 

if you could guide me I can give you a pull request. 

Kind regards
  Rob

**Comment by mookid8000** [comment]
It's the [`PoisonQueueErrorHandler`](https://github.com/rebus-org/Rebus/blob/master/Rebus/Retry/PoisonQueues/PoisonQueueErrorHandler.cs) that does it when it's initialized.

Maybe the transport should simply ignore calls to `CreateQueue` altogether when queue creation is disabled?

**Comment by mookid8000** [comment]
Hi @robvanpamel , did you get any further with this?

**Comment by mookid8000** [comment]
Hi @robvanpamel , I'm closing this issue now – mostly because I think it belongs in the [Rebus.AmazonSQS](https://github.com/rebus-org/Rebus.AmazonSQS) repo, but also because you didn't reply and so I am thinking you may have solved your problem somehow....?

If it's still a problem, please don't hesitate to raise the issue [here](https://github.com/rebus-org/Rebus.AmazonSQS/issues)

**Comment by robvanpamel** [comment]
Hi 
Sorry for the late response (Holidays ... :) )!  I got it temporary working but not it is not a proper solution. As soon as i have the time i will try to solve it in a decent manner. However the project has other urgenties at this moment.

Kind regards
  Rob
