### ISSUE TITLE
Rebus catching exceptions when resolving handlers [Improvement]

### ISSUE THREAD

**Issue by mclausen** [rebus-org/Rebus#627]
Hi Rebus team, 

Today i stumbled upon, the following exception message: 

Rebus.Exceptions.RebusApplicationException: Message with ID 7e55bcf2-7008-46e3-b1b7-3c161339fa23 and type Nabufit.AssetManagement.Messages.External.UpdateExercisePosterRequestMessage, Nabufit.AssetManagement.Messages.External could not be dispatched to any handlers

Which led me to believe that I forgotten to implement a IHandleMessages<UpdateExercisePosterRequestMessage>.

I've confirmed that I've already implemented the handler, I checked that the handler was registered in my Castle Windsor container. 

However i still got the exception thrown.

After an hour of debugging, i discovered, that when i was resolving the handler manually i was thrown a a user exception that i could handle. 

However I expected to retrieve that specific exception in my error message instead of "could not be dispatched to any handlers".

**Comment by mookid8000** [comment]
Unfortunately that's how Castle Windsor works – when you `container.ResolveAll<IWhatever>()` (this is what Rebus does) and one of the registered implementations of `IWhatever` cannot be resolved (e.g. due to missing dependencies and stuff), it is simply omitted by Windsor.

Therefore, there is no sensible way for Rebus to figure out that there was a problem, it is simply left with dealing with an empty list of handler instances.

You should probably create an automated test that iterates over all of your handler types and resolves them – this way you can be sure that you don't forget to register a dependency.

**Comment by mclausen** [comment]
Roger 👍
And may you have a wicked day 😃

**Comment by mookid8000** [comment]
You too, my working friend 🍺🍷

Sendt fra min iPhone

-
Mogens Heller Grabe
Torsmark 4
8700 Horsens
Danmark

(+45) 29 36 70 77
mookid8000@gmail.com
