### ISSUE TITLE
String interpolation missing?

### ISSUE THREAD

**Issue by kenoma** [rebus-org/Rebus#630]
I have found following line at **Rebus/Rebus/DataBus/FileSystem/FileSystemDataBusStorage.cs**:
```csharp 
_log.Info("Checking that the current process has read/write access to directory {directoryPath}", _directoryPath);
``` 

I guess that lines like above may lead to fails in cases, when `_log` implementations will use something like `string.Format(message, objs)`

**Comment by mookid8000** [comment]
This is intentional 😄 Rebus provides the [`RenderString`](https://github.com/rebus-org/Rebus/blob/master/Rebus/Logging/AbstractRebusLoggerFactory.cs#L25-L60) method for logger factories to use if they are not capable of doing it themselves.

The reason it was made this way was for Rebus to be able to provide structured logging for logging libraries that are capable of making use of it, e.g. Serilog (which I always use because it's the best 😁 )
