### ISSUE TITLE
Missing IBus.Advanced.Subscribe in new version

### ISSUE THREAD

**Issue by alkampfergit** [rebus-org/Rebus#649]
In a project I'm using a really old version of rebus (0.77) where I have the ability to use  

     IBus.Advanced.Routing.Subscribe(type, subscription.Endpoint);

to explicitly subscribe a message from more than one input queue.

My situation is

Process A - Queue A
Process B - Queue B
Process C - Queue C
Process D - Queue D
Process E - Queue E

Now I need to subscribe Process D and process E to a particular message from A,B,C. I have processes A B and C that publish a special message that is CommandHandled, and I want these processes to send CommandHandled to Queue D and E.

How can I obtain this kind of publish/subscribe with Rebus 4?

Thanks.

**Comment by mookid8000** [comment]
> How can I obtain this kind of publish/subscribe with Rebus 4?

You can't. Sorry about that.

As you have discovered, Rebus 4 does not have a way of explicitly routing its [`SubscribeRequest`](https://github.com/rebus-org/Rebus/blob/master/Rebus/Messages/Control/SubscribeRequest.cs)
 – this feature was removed from Rebus versions >= 0.90.0.

What you can do, is to either

a) manually send the `SubscribeRequest`, filling out the `SubscriberAddress` with the input queue of the subscriber you wish to enlist and `Topic` with `type.GetSimpleAssemblyQualifiedName()` of the type you wish to subscribe to, or

b) use a [centralized subscription storage](https://github.com/rebus-org/Rebus/wiki/ISubscriptionStorage#central-subscription-storages)

I would prefer (b) – since "Rebus 2" (which is the name for versions >= 0.90.0) it has been possible to configure all subscription storages as centralized, bypassing the `SubscribeRequest`, thus registering subscribers directly in the storage.

This completely removes the need to map events to publishers in each subscriber, and it makes it much much easier for multiple publishers to be able to publish the same event types.

**Comment by alkampfergit** [comment]
Perfect, I've already implemented in few minutes solution a, and it works. I'll explore solution b, because it seems to me preferable (actually solution A was a few minutes fix).
