### ISSUE TITLE
Any mechanism for broadcasting events that may have no subscriptions?

### ISSUE THREAD

**Issue by ronnyek** [rebus-org/Rebus#652]
This may actually not be a legitimate need... but in just pre-planning some consumption of rebus with RabbitMQ, I was curious if there was anyway to have services broadcast events that may have 0-many consumers... eg, Some thing happened, and other services might consume or not consume this message. 

(I suppose I preface with may not be legitimate because I've not necessary got a specific use case in mind, other than some entity got updated and send out a blip that that entity was updated... but as of today nothing might subscribe... and these specific messages would be good to just disappear if nothing was listenting. This also might be outside the realm of intentions with existing service bus tech)

**Comment by mookid8000** [comment]
You simply want to `await bus.Publish(anEvent);` 😉 

With Rebus, there's basically two modes of sending messages:

### 1. Point to point

This is when you `await bus.Send(yourMessage);` – then the message is sent to exactly one destination address.

In the literature it is know as a ["point-to-point channel"](http://www.enterpriseintegrationpatterns.com/patterns/messaging/PointToPointChannel.html)


### 2. Publish/subscribe

This is when you `await bus.Publish(anEvent);` – then the message gets distributed to between zero and an infinite number of recipients, depending on who is currently subscribed to that particular "topic". By default, Rebus infers the topic from the type of the event published, generating it out of the "short assembly-qualified name" of the type (i.e. a .NET type without version, hash code, and culture, so e.g. `System.String, mscorlib` would be the topic inferred from an ordinary string.

This is know as a ["publish/subscribe channel"](http://www.enterpriseintegrationpatterns.com/patterns/messaging/PublishSubscribeChannel.html) in the literature.

### Conclusion

You're looking for (2) 😄

**Comment by ronnyek** [comment]
I was using publish, but with no subscriber the queue just backs up... I've got 2400 messages waiting to be subscribed... I guess that's kinda what I meant...

**Comment by ronnyek** [comment]
Hmm.... actually with a newly created queue, I am actually not seeing it backup... maybe this queue was originally created as a work queue initially or something

**Comment by mookid8000** [comment]
> but with no subscriber the queue just backs up... I've got 2400 messages waiting to be subscribed

Hmm the way you put it – "I've got 2400 messages waiting to be subscribed" – sounds to me like s light misunderstanding.

An endpoint with that particular input queue must have registered itself as a subscriber by calling `await bus.Subscribe<EventType>();`. And then, since subscriptions are persistent, you can start/stop the subscriber as much as you want, and it will always end up receiving all of the published events.

This of course means, that a subscriber that is not running will see events pile up in its input queue.

I hope it's clear to you how it works 😃

**Comment by ronnyek** [comment]
No I think I get how that part works but if you don't mind humoring me just so I dont get down the road and find out I totally didn't account for a very real situation.. I've got a few questions (maybe we could toss em in a FAQ if you've heard the questions enough and don't feel like they are represented in documentation. I'm by no means an expert in rabbitmq, though I've used other transports and service bus mechanisms, and am well aware a poor design here (on my part I mean) could dramatically effect end application.

1) In the scenario I defined above, having no subscribers means its just passed through... broadcasted and as soon as the first service subscribes to that service, an input queue is created with name passed to the use rabbitmqtransport (not the send only one). After that messages are queued up because we've effectively let the framework / rabbit know something is indeed listening for these messages.

If I were to launch two services with the same input queue name, messages coming in would be automatically balanced (the nature of input queues and subscriptions)

2) I'm effectively (by default) having input queue be my service name, and so theoretically published messages could be subscribed to, by both services and not have any bearing on one another (both would receive regardless of what happened afterwards)

3) I assume for messages that were like little non-critical status updates because of how the queuing worked out, I'd probably want to set expiration super low, so that if a subscriber was offline and came back online a bunch of old (non applicable messages) dont just go getting delivered.

4) I should probably create some sort of instrumentation that would show me input queues so that I can be aware when say something happens.. .this service no longer listens and queue backs up. (maybe that's manual intervention deleting the input queue, or some mechanism of doing that automatically)

I appreciate the time, and am hoping some questions up front will help me understand potential pitfalls upfront and engineer around them. I'd be happy to build some documentation or examples that express these concepts. (I'm well aware of examples/samples repos)

**Comment by mookid8000** [comment]
1. That's correct 👍 

> If I were to launch two services with the same input queue name, messages coming in would be automatically balanced (the nature of input queues and subscriptions)

Yes. And therefore, it is important that the two services in question are _two instances_ of the same service. I'm guessing that that's what you mean, but I just think it should be really clear here 🙂 

2. ?

3. That sounds reasonable.

4. It's always a good idea to watch that queue length don't just grow and grow. Could be because of a leftover subscription after having retired a service, could be a service gone down or frozen for whatever reason.

4. With RabbitMQ, everything is actually "publish with a routing key", and then – depending on the type of exchange published to – the routing key gets interpreted as a single queue name (`RebusDirect`) or as a topic (`RebusTopics`). After that, messages end up in queues, and are received in the exact same manner, so at that point there's no difference between sent and published messages.

Please let me know if I misunderstood one of your questions 🙂
