### ISSUE TITLE
Injectionist does not integrate with IHandlerActivator/IContainerAdapter

### ISSUE THREAD

**Issue by MrMDavidson** [rebus-org/Rebus#654]
We came across an issue today that, after looking at the source, is obvious. But I wanted to confirm that it's the intended design.

With Rebus the bootstrap is `Configure.With(IHandlerActivator)` with the intent being that `IHandlerActivator` is a wrapper around the IoC framework that the given project uses (Castle, Autofac, etc). When Rebus needs to resolve a handler for a given message it calls `GetHandlers` on the `IHandlerActivator` which the given wrapper would then pass along to the IoC framework to resolve. All good.

What seems odd is that the use of `PossiblyRegisterDefault` within `RebusConfigurer` (which is a similar pattern I've used with Single Access Sagas - https://github.com/MrMDavidson/Rebus.SingleAccessSagas/blob/master/Rebus.SingleAccessSagas/SingleAccessSagaConfigurationExtensions.cs#L25 ). However both `PosiblyRegisterDefault` and `OptionsConfigurer` (https://github.com/rebus-org/Rebus/blob/master/Rebus/Config/OptionsConfigurer.cs#L78) directly refer to the `Injectionist` instance. In most real world projects you'd have a all of your IoC registrations happen automatically where as it seems that any interactions with the Rebus pipeline/infrastructure need have their implementations re-registered with Injectionist using;
```C#
var config = Configure.With(...).Options(
  opt => {
    opt.Register(ctx => new MyService());
    opt.Register(ctx => new OtherService());
  }
);
```
Should these `Has<>` style implementations defer to the `IHandlerActivator`/`IContainerAdapter`?

**Comment by mookid8000** [comment]
Injectionist is only there to wire things up at startup time. As soon as everything is wired up, the implemention of `IBus` handed to you by the configurer functions as a container for the bus and everything injected into it.

Container adapters are then brought into the mix because Rebus sometimes need to look up message handlers, and IoC containers are great for that.

You should probably not think of `IHandlerActivator` as a "wrapper" around the IoC container, it's more like a service Rebus needs someone to provide, and then it usually makes sense to provide this service by forwarding the calls to a container adapter.

So no, registrations in Injectionist and your own IoC container registrations should not be mixed.

I understand then, that people might feel like e.g. decorating some of Rebus' services and need to look up stuff in their IoC container in the process – that's totally fine, although I have gotten this far without having done that a single time (as far as I can recall).

I hope that makes sense 😄
