### ISSUE TITLE
Get topic subscriptions of the IBus and other health information.

### ISSUE THREAD

**Issue by robvanpamel** [rebus-org/Rebus#666]
Hi, 

We are using Rebus with type based topics. We are adding these subscriptions via Reflection. 
I was just wondering if there is a way to list out the topics to which rebus is subscribed @ runtime? 

If you were wondering why we would need this? 
Since Rebus is performing a very crucial task in our environment we are adding a Rebus health page and some Rebus health checks on our service. 
On this health page we would list out all the subscriptions.

We would also add a message to the queue over here to make sure we can write to the queue. Then we can check CanWrite on the healthPage.
Would there be a way to manually read from a rebus queue without 'subscribing' to it. This way i can verify if reading from that queue works as well. This information can be added to the healthpage then as well. This without affecting the actual subscriptions of the service.

However if you add a message without subscribers, it will not be added to the queue. So I don't know what the best solution is for this. Any suggestions?

Kind regards
  Rob

**Comment by mookid8000** [comment]
> I was just wondering if there is a way to list out the topics to which rebus is subscribed @ runtime?

Not readily, no. But if you are using e.g. SQL Server to store subscriptions, it would be pretty easy to have something query the subscriptions at runtime.

If you are interested in implementing something general, you can decorate `ISubscriptionStorage` and hook into [`RegisterSubscriber`](https://github.com/rebus-org/Rebus/blob/f1a50e94f1a1624512e83fbcc62464d767ef3ac1/Rebus/Subscriptions/ISubscriptionStorage.cs#L19) and [`UnregisterSubscriber`](https://github.com/rebus-org/Rebus/blob/f1a50e94f1a1624512e83fbcc62464d767ef3ac1/Rebus/Subscriptions/ISubscriptionStorage.cs#L24) and then maintain the information wherever you like.

**Comment by mookid8000** [comment]
> However if you add a message without subscribers, it will not be added to the queue. So I don't know what the best solution is for this. Any suggestions?

yeah well.... I recommend you only `await bus.Publish(...)` events, and then somehow model your system so that there is no strict assumption about the number of subscribers.... ideally, everything should work even when you start out with 0 subscribers.

With [Fleet Manager](https://rebus.fm/services/fleet-manager/) (which is a commercial product) it will be possible to enable "message auditing", which will save a copy of all handled messages and all published events – this way, you can be sure that the information published in an event exists in at least one copy, even though there can be zero subscribers at the time of publishing it.

**Comment by robvanpamel** [comment]
Thanks for the information.
We are using MySQL for keeping track of the subscriptions.
I had already planned to back-up everything to aws  S3 so, we have kindof the same thoughts. Maybe I can add it as an open source project. 

Thanks
