### ISSUE TITLE
rebus.transactionscope

### ISSUE THREAD

**Issue by nebelx** [rebus-org/Rebus#669]
could you please push new version of rebus.transactionscope to nuget?  It looks like current version added to nuget on 05.01.2017 is incompatible with latest Rebus (4.2.1) because of changes 
https://github.com/rebus-org/Rebus.TransactionScopes/commit/25176d4522f1f59f6e1aaf7058ff15de0f887fb7#diff-9ca058c8cb8ab30948d5f3033e2435b3 made on 10.05.2017

**Comment by joffreynorsys** [comment]
Do you  try this package https://www.nuget.org/packages/Rebus.TransactionScopes/ ?

**Comment by mookid8000** [comment]
oh yeah, sorry about the confusion – I have unlisted `Rebus.TransactionScope` on NuGet.org now, because `Rebus.TransactionScopes` is the correct package.

The source of this mess is that an `s` was accidentally added to the name at some point, when porting all Rebus projects to the new project structure, and then – since packages cannot be renamed/deleted/etc –  they have been leading a parallel existence for a while.

It should be pretty hard to accidentally import `Rebus.TransactionScope` now that it is unlisted.
