### ISSUE TITLE
Serialization issue when client is dotnet core and handlers are full .net

### ISSUE THREAD

**Issue by mattwhetton** [rebus-org/Rebus#672]
Hey,

I've come across a problem using Rebus in what I guess you'd call a multi-platform environment. Basicallyt I have a web client running .net core that sends commands via Rebus to a backend thats running net461.

Where the dotnet core front end serializes messages for the queue, it includes the type name (type and asembly name). With some system types (e.g. generic lists) it serializes them something like this:

```
"$type": "System.Collections.Generic.List`1[[MyType]], System.Private.CoreLib"
```

This then causes a deserialisation problem in the backend, as `System.Private.CoreLib` is not compatible with net461. The subsequent errors are something like:

`System.FormatException: Could not deserialize JSON text`

My current workaround is to force everything to use net461, which is fine for the moment, although may not be long term.

This might not be *worth* fixing? Or maybe there's a workaround by plugging in a custom serializer?
  
*I'm also happy to contribute if we identify the right solution*

**Comment by mookid8000** [comment]
oh damn!!

That is an obvious problem.

It can solved by hooking into JSON.NET and customizing the `SerializationBinder`, which is responsible for mapping .NET types to/from their type names – and then the .NET Core version would need to map to/from compatible collection types from the full .NET fx.

But I am not sure that that is the way to go....

I actually thought about simplifying the default JSON serialization a lot for Rebus 5 by not having JSON.NET include type information in the serialized format.

This way, Rebus would simply use the `rbs2-msg-type` header to figure out which type to deserialize.

It would of course mean that abstract classes and interface implementations would not readily roundtrip as they do now, but I am not sure I think it's a good idea to pass those things around in the first place. And one could always pass one's own `JsonSerializerSettings` when configuring Rebus, enabling full type name handling.

Using the default "pure" JSON serialization format would save a tremendous amount of space – e.g. consider this case, where I am using a `Currency` object as a value type to represent a currency:

Here it's serialized with `TypeNameHandling.All`:
```csharp
{"$type":"Customer.System.Primitives.Currency, Customer.System.Primitives","CurrencyCode":"DKK"}
```
and here it's just serialized using the default settings:
```csharp
{"CurrencyCode":"DKK"}
```

The space wasted by type information in this case is just crazy!

**Comment by mattwhetton** [comment]
Yeah, I think that sounds like the better way to go - feels a little more portable

**Comment by mookid8000** [comment]
> feels a little more portable

sure does 😄 I have also had more and more people ask be about interoperability lately, the ability to exchange messages with node.js- and JVM-based systems ... this change would make it simpler to exchange messages between platforms in general

**Comment by mookid8000** [comment]
otoh this change could potentially break lots of stuff running out there..... I will make it into a serialization configuration extension instead

**Comment by mookid8000** [comment]
Rebus 5.0.0-b02 has a new serialization configuration overload that makes it possible to do this:
```csharp
Configure.With(...)
    .(...)
    .Serialization(s => s.UseNewtonsoftJson(JsonInteroperabilityMode.PureJson))
    .Start();
```
which will then serialize messages into the pure format. One can also pass the value `JsonInteroperabilityMode.FullTypeInformation`, which is equivalent to simply calling
```csharp
    .Serialization(s => s.UseNewtonsoftJson())
```
which in turn it equivalent to
```csharp
```
because it's Rebus' old (and future) default 😉 

The new b02 version will be out as soon as the build server finishes crunching.

Thanks for reporting this issue!!

**Comment by lzarioiu** [comment]
Hey,
I think I'm facing the same issue (or a similar one). Some messages fail with : 

`System.FormatException: Could not deserialize JSON text: '{"$type":"Cpr.Eff.Messages.CertificateUpserted, Cpr.Eff.Messages","ID":130518.0, ... --->  Newtonsoft.Json.JsonSerializationException: Error resolving type specified in JSON 'Cpr.Eff.Messages.CertificateUpserted, Cpr.Eff.Messages'. Path '$type', line 1, position 75. ---> Newtonsoft.Json.JsonSerializationException: Could not load assembly 'Cpr.Eff.Messages'. `

Was it the same error for you @mattwhetton and did it constantly reproduce? 

Thank you!

**Comment by mookid8000** [comment]
> `Could not load assembly 'Cpr.Eff.Messages'`

...sounds to me more like the receiving end cannot load the `Cpr.Eff.Messages` assembly... could you check to see that `Cpr.Eff.Messages.dll` is present in the runtime directory of your application?

**Comment by alexvilper** [comment]
Hi @mookid8000 ,

My question is related to @lzarioiu 's. We currently use Rebus and we have a shared project that holds the command messages (payloads, etc). Both the client and the bus projects reference this shared "messages" project. When the client sends a message to the bus, the bus knows how to handle it because it has references to the same namespace:

To illustrate, we have 3 projects:
- project.rebus.bus
- project.rebus.messages (command messages)
- project.rebus.client

Solution1 - bus
- project.rebus.bus
` PingHandler<Ping>`
- project.rebus.messages (Ping message)

Solution2 - client
- project.rebus.client
` bus.send(new Ping {...})`
- project.rebus.messages (Ping message)


The scenario works because both **project.rebus.bus** and **project.rebus.client** share the same **project.rebus.messages**, all good.

How do we setup **project.rebus.bus**, when it needs to handle messages from a third party vendor, where we can't have a shared **project.rebus.messages** project? Is it possible?

Thanks for your help!

**Comment by mookid8000** [comment]
> UPDATE:
Sorry, I did not realized this thread was already closed. I posted the same question on stackoverflow...
https://stackoverflow.com/questions/49458072/how-to-setup-rebus-to-handle-messages-from-third-party-vendor

no problem 😄 I answered the question on StackOverflow

**Comment by keithernet** [comment]
Hello,
I'm sorry to resurrect this old issue, but we just ran into this problem. Making the serialization change mentioned above did solve the issue, but I was slightly concerned about:

> otoh this change could potentially break lots of stuff running out there..... I will make it into a serialization configuration extension instead

Could you provide any additional information about what the potential breaking issues with this could be? Thanks for a great library and your active support!

**Comment by mookid8000** [comment]
> Could you provide any additional information about what the potential breaking issues with this could be?

Sure 🙂 consider the message type

```csharp
public class ProcessFileUpdates
{
	public ProcessFileUpdates(IEnumerable<FileUpdate> updates) => FileUpdates = updated.ToList();

	public IReadOnlyList<FileUpdate> FileUpdates { get; }
}
```
where `FileUpdate` is defined as
```csharp
public abstract class FileUpdate
{ 
    protected abstract FileUpdate(string fileName) => FileName = fileName;
    public string FileName { get; }
}

public class FileAdded : FileUpdate
{
	public FileAdded(string fileName) : base(fileName) { }
}

public class FileChanged : FileUpdate
{
	public FileChanged(string fileName) : base(fileName) { }
}

public class FileDeleted : FileUpdate
{
	public FileDeleted(string fileName) : base(fileName) { }
}

```

As you can probably imagine, serializing 
```csharp
new ProcessFileUpdates(new FileUpdate[] {
	new FileAdded("stuff.csv"),
	new FileChanged("other-stuff.csv"),
	new FileDeleted("totally-unrelated-stuff.csv")
})
```

would normally result in the following JSON:
```json
{
	"FileUpdates": [
		{ "FileName": "stuff.csv" },
		{ "FileName": "other-stuff.csv" },
		{ "FileName": "totally-unrelated-stuff.csv" }
	]
}
```
thus erasing all knowledge about which types were actually serialized.

When deserializing this, the JSON serializer would complain that it's not possible to instantiate the abstract class `FileUpdate`, and – as you can see from the JSON – you would not be able to figure out which subclass to use either.

With Rebus' default "belt and braces" approach, full type information is included in the JSON

```json
{
	"$type": "Messages.ProcessFileUpdates, Messages",
	"FileUpdates": [
		{ "$type": "Messages.FileAdded", "FileName": "stuff.csv" },
		{ "$type": "Messages.FileChanged", "FileName": "other-stuff.csv" },
		{ "$type": "Messages.FileDeleted", "FileName": "totally-unrelated-stuff.csv" }
	]
}
```
meaning that the serializer would know exactly which concrete class to grab when deserializing.

This design values the ability to roundtrip rich object structures more than it values interoperability and flexibility, because the following things would break the serializer's ability to deserialize the message:

* If you moved one of the types – any single one of them – to another namespace, or renamed one of them
* If you moved any of the types to another assembly, even though the namespace was the same

and on platforms that do not have types like C# does, then it might not even make sense to talk about this type of object hierarchy.

So... like all decisions worth making, there's a trade-off. But I'm leaning towards changing this default some time in the future.

**Comment by keithernet** [comment]
This was immensely helpful. Thank you for you help!

**Comment by jmevel** [comment]
I just wrote an [SO answer](https://stackoverflow.com/a/73579781/1203116) about this issue.
Just leaving this in case it helps other people

To summarize, because .NET Framework has no idea about `System.Private.CoreLib` we should configure the serializer to specify the types only when the instance of a property is different from the declared type (i.e: a base `abstract` class with several implementations). For all other cases, the type is omitted in the JSON

```chsarp
var settings = new JsonSerializerSettings
{
    TypeNameAssemblyFormatHandling = TypeNameAssemblyFormatHandling.Full,
    TypeNameHandling = TypeNameHandling.Auto
};

rebusConfigurer.Serialization(opt => opt.UseNewtonsoftJson(settings));
```

It works in my case but I didn't extensively tested all different .NET types

**Comment by mookid8000** [comment]
@jmevel thanks for posting a note about your experience here 👍

**Comment by mookid8000** [comment]
Yeah well, as people seem to have figured out, having full .NET type information in the serialized format can lead to interoperability problems between .NET Framework and .NET (.NET Core/dotnet).

> We fall back to the problem of a base class with several different implementations. If the type isn't specified then the deserialization is impossible as we don't know which implementation was used.

True. With `JsonInteroperabilityMode.PureJson` you're free to have messages like

```csharp
public abstract record DepartmentEvent(string Department);
public record PersonHired(string Name, string Department) : DepartmentEvent(Department);
public record PersonFired(string Name, string Department) : DepartmentEvent(Department);
```

thus using inheritance at the root level, but using abstract classes/interfaces WITHIN the message format is going to be impossible to deserialize. E.g. with

```csharp
public record DepartmentEventBatch(IReadOnlyList<DepartmentEvent> Events);
```

I could easily serialize this

```csharp
var batch = new DepartmentEventBatch(new[]
{
    new PersonHired("joe", "accounting"),
    new PersonHired("moe", "accounting")
});
```

into this

```json
{
  "Events": [
    {
      "Name": "joe",
      "Department": "accounting"
    },
    {
      "Name": "moe",
      "Department": "accounting"
    }
  ]
}
```
but the deserializer would go
```
Newtonsoft.Json.JsonSerializationException : Could not create an instance of type DepartmentEvent. Type is an interface or abstract class and cannot be instantiated. Path 'Events[0].Name', line 4, position 13.
```

So... yeah well what I'm saying is: Maybe try to avoid using inheritance/interfaces inside your messages.

**Comment by jmevel** [comment]
Thanks for your answer, yeah it looks almost impossible to solve... ☹
At least now I have in mind all the limitations...

**Comment by jmevel** [comment]
@ssbehera-pmap no that's not fixed and that will probably never be since .NET Framework is now deprecated.
Read the previous messages, you'll understand the limitations and what not to do in order to avoid having this issue.

Good luck 😉

**Comment by mookid8000** [comment]
...but the error message
```
---> System.FormatException: Could not get .NET type named 'abcd.Api.Core.PubSub.Message, core-pubsub'
at Rebus.Serialization.Json.JsonSerializer.GetTypeOrNull(TransportMessage transportMessage)
at Rebus.Serialization.Json.JsonSerializer.GetMessage(TransportMessage transportMessage, Encoding bodyEncoding)
(...)
```
sounds more like a consumer that doesn't have access to the type `abcd.Api.Core.PubSub.Message, core-pubsub` - does the program reference the "core-pubsub" DLL? Does the class `Message` in fact live in the "abcd.Api.Core.PubSub" namespace?
