### ISSUE TITLE
Issues publishing messages from MVC.NET application

### ISSUE THREAD

**Issue by dannagel** [rebus-org/Rebus#673]
We're using ReBus within an MVC.NET/WebAPI application, using SQL for message transport and subscription storage.  For some reason when we call bus.Publish().Wait() the thread **hangs indefinitely** and the message is never published.  We have tried workarounds with less than 100% success (such as calling this code from a Task.Run call).  The exact same call to bus.Publish().Wait() works perfectly fine from within a non-web app such as a console application.  Please advise.

Thanks!

**Comment by dannagel** [comment]
I just ran into the bus.Advanced.SyncBus API (our code is not set up to be async).  At first blush this seems to work from with our web app.  Is this the recommended approach?

**Comment by mookid8000** [comment]
> For some reason when we call bus.Publish().Wait() the thread hangs indefinitely

That will happen in ASP.NET if you call `.Wait()` on ANY `Task`. It's because ASP.NET insists on running the continuation on the thread that calls `.Wait()`, but that thread is waiting for the `Task` to finish. It's a deadlock 💀 😁 

If you're interested in reading more about why, I suggest you check out [this blog post](https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html).

> I just ran into the bus.Advanced.SyncBus API (our code is not set up to be async). At first blush this seems to work from with our web app. Is this the recommended approach?

Well – the recommended approach when you're in an `async`-capable context (which ASP.NET definitely is) is to make your code [async all the way up/down](https://stackoverflow.com/a/29809054/6560) (depending on your perspective), because then you can

    await bus.Publish(yourEvent);

and benefint from being able to use your thread for other work while asynchronous database I/O is going on. If you happen to be deep in a call stack that does not return `Task`, the recommended approach is to use `ISyncBus` like you've figured out.
