### ISSUE TITLE
Question about monitoring rebus

### ISSUE THREAD

**Issue by ronnyek** [rebus-org/Rebus#676]
I just have a hopefully quick question. Basically I'd like to make sure I'm aware of the sort of usages that happen with rebus framework, as well as maybe some basic level of instrumentation (monitoring queues etc).

I currently back rebus with rabbitmq (dont know if that would make a difference), but dont know the best way to go about this. Seems like I could do IHandleMessages<Object> and let that listener grab what it needs from the messages being sent across the wire (though this seems wasteful and spendy), or undoubtedly consume some rabbit mq apis for the instrumentation.

I'm just curious if people have implemented anything like this, and if so pointers on how to go about it. Using a similar but not so similar framework at a previous employer, we had problems with stuff like subscriptions being created, and service being taken offline (finding out only later, messages just piling up)

**Comment by MrMDavidson** [comment]
You might want to look into the pipeline customisation stuff. Eg. We have a custom step in our pipeline that  collects metrics;

```C#
config.Options(
  x => x.Decorate<IPipeline>(res => {
    PipelineStepInjector injector = new PipelineStepInjector(res.Get<IPipeline>());
    MyCustomMetricStep metricStep = new MyCustomMetricStep();
    injector.OnSend(metricStep, PipelineRelativePosition.Before, typeof(SerializeOutgoingMessageStep));
    injector.OnReceive(metricStep, PipelineRelativePosition.After, typeof(DeserializeIncomingMessageStep));
  })
);
```

This will run just before submitting the message to your queue (whatever implementation that is) and just after pulling a message from the queue. The implementation of this will vary depending on your infrastructure...

```C#

public class MyCustomMetricStep : IIncomingStep, IOutgoingStep {
  public async Task Process(IncomingStepContext context, Func<Task> next) {
    // Message about to be processed. Log details of it to some kind of monitoring system, perf counters, etc
    try {
      await next();
      // Message succeeded.
    } catch (Exception ex) {
      // Log failure to monitoring but still throw so Rebus can retry
      throw;
    }
  }

  public async Task Process(OutgoingStepContext context, Func<Task> next) {
    await next();
    // Message sent! Log details of it to some kind of monitoring system; performance counters, whatever.
  }
}

```

Using this style of step in the pipeline we have stats on how deep our queues are (eg. Graphs of entire queue depth as well as per message type. We also log statistics of time taken for processing (simple stop watch around the `next()` in the `IncomingStepContext`) as well as the latency for processing (comparing time stamps between when it was sent and when we process it).

Hope that helps.

**Comment by mookid8000** [comment]
@MrMDavidson great answer 😄 

Rebus is pretty extensible in this regards, and as @MrMDavidson has shown, it is fairly straightforward to add hooks to almost everything Rebus is doing.

I just need to say this:

`<advertisement>`
In addition to maintaining Rebus and all of its integration packages, I run [Rebus FM](https://rebus.fm/), which is me trying to squeeze money out of Rebus 😁  (in a nice way, without bothering those who don't care).

It's just that I am providing something called [Rebus Pro](https://rebus.fm/rebus-pro/), which – in addition to support – offers access to [Fleet Manager](https://rebus.fm/services/fleet-manager/), which is pretty much what you're asking for... and it's made so that it makes no difference which transport and persistence types you're using.

Hit me up at `hello@rebus.fm` if you're interested in hearing more.
`</advertisement>`

Sorry about the commercial break there 😒
