### ISSUE TITLE
QUESTION: Race condition in Handlers

### ISSUE THREAD

**Issue by vdecristofaro** [rebus-org/Rebus#680]
I am experiencing a race condition on the database when using an handler with a UnitOfWork.
This is the rebus configuration

```
container.ConfigureRebus(
                rebusConfig => rebusConfig
                    .Logging( l => l.None() )
                    .Transport( t => t.UseAzureServiceBus( connectionString, "QUEUE1" ) )
                    .Options( options => {
                        options.SetNumberOfWorkers( 1 );
                        options.SetMaxParallelism( 1 );
                        options.SimpleRetryStrategy( errorQueueAddress: "QUEUE1_ERRORS", maxDeliveryAttempts: 3 );
                        options.EnableUnitOfWork( Create, commitAction: Commit, rollbackAction: Rollback, cleanupAction: Cleanup );
                    } )
.Start() );
```

As you may see I am using a singlue worker. In the handler I am looking for a row in the database to update, and if not found create it.
My query should return a single row of data, however I am not using a unique index.

What I am experiencing is that the first handler instance does not find a row and try to insert it. When the second handler starts however, the commitAction has not finished yet and so it will add a new row as well. 

I think that this can also depend on the EnableUnitOfWork static methods however I am not sure this can be the exact problem. 

Any suggestion?

**Comment by mookid8000** [comment]
Hmm, I've never heard anyone report any issues with the parallelism setting.

I could try and reproduce the issue in a test with some aggressive use of `async` stuff, but before I do that, could you maybe go through your code and verify that everything you have that returns a `Task` is awaited?

**Comment by vdecristofaro** [comment]
Good. I have verified and everything is awaited correctly. For instance the handler is very easy code with almost no intelligence.

**Comment by mookid8000** [comment]
I have tried to reproduce the issue here: https://github.com/rebus-org/Rebus.UnitOfWork/blob/master/Rebus.UnitOfWork.Tests/TryToReproduceRaceCondition.cs

The test records the sent messages by number and records the order of events for each message (i.e. "unit of work created", "message handled", "unit of work committed", "unit of work disposed"), and then it verifies 

* that the order of events is consistent for each message, and
* that no two events for different messages are interleaved 

From the looks of it it seems to work as it should. Could you maybe go over the test and see if you can spot some kind of difference between your implementation and my reproduction attempt?

**Comment by mookid8000** [comment]
Hi @vdecristofaro , have you had a chance to look further at this?

**Comment by vdecristofaro** [comment]
Yes. We have looked at it and your test seems correct and working at us. 
There should be something more that is creating the race condition. I think we will go firther in deep into this starting next week. 
I can close the issue for now and eventually open it again if we find something that may need your help again. 

Thanks vry much for the support and keep up the great work you're doing! (y)
