### ISSUE TITLE
Deserializing list of an abstract base class creates duplicate entries

### ISSUE THREAD

**Issue by markusgud** [rebus-org/Rebus#695]
It seems like when an abstract class is implemented like this:

```
public abstract class BaseTaskCommand
{
  private IList<TimeSpan> _delay = new List<TimeSpan>();
  public IList<TimeSpan> Delays => _delays;
}
```

and the derived class is implemented like this:
```
public class DerivedTaskCommand : BaseTaskCommand
{
  public int TaskId { get; set; }  
}
```

and a message has been added to MSMQ with 5 entries, then the Handle function of:
```
public class DerivedTaskCommandHandler : IHandleMessages<DerivedTaskCommand>
{
  public Task Handle(DerivedTaskCommand message)
  {
    // do something
    return Task.CompletedTask;
  }
}
```

will return a list inside the message which has doubled number of entries and has 10 entries, not 5 entries.

The last 5 entries are identical to the first 5 entries.
Is there possibly a bug where the property is deserialized twice?

**Comment by mookid8000** [comment]
That sounds pretty weird.... let me take a look

**Comment by mookid8000** [comment]
I've tried to reproduce the problem [here](https://github.com/rebus-org/Rebus/blob/master/Rebus.Tests/Assumptions/TestSpecificSerializationExample.cs), but I couldn't make it fail.

Could you show me the code that sends the message?

**Comment by mookid8000** [comment]
This issue is resolved. It was shown that the constructor of `BaseTaskCommand` (which was not included here) added items to the `Delays` list. This was great when creating a message of the derived type the first time, but during _deserialization_ it turned out to be a problem, because JSON.NET would then start out with some items in the list, and _then_ it would add the items found in the JSON text.
