### ISSUE TITLE
Easiest way to discard unwanted messages

### ISSUE THREAD

**Issue by stevengopmo** [rebus-org/Rebus#699]
Hello,

Our service publishes messages with headers that tell the receiver what customer the message belongs to.  Some of our subscribers use this header information to build a connection string.  In some cases, the incoming message headers tell us this subscriber can ignore the message.  Our problem is that we use this header information to build a connection string when the message arrives. (connection is Lifetime.Scoped).

Is there a place in the pipeline between where the message arrives and before our scope starts where we can change this header and discard the message if we need to?

**Comment by mookid8000** [comment]
Yeah sure, you can insert an implementation of `IIncomingStep` into the [incoming messages pipeline](https://github.com/rebus-org/Rebus/wiki/Incoming-messages-pipeline) and position it before `ActivateHandlersStep`, because that's where your IoC container gets asked to resolve message handlers.

**Comment by mattwcole** [comment]
Apologies for resurrecting an old issue, but how exactly can a message be discarded in an incoming pipeline step? Not calling `next()` (at least with RabbitMQ) causes the message not to be acknowledged.

**Comment by mookid8000** [comment]
@mattwcole You're right - it's not possible to do it by refraining from invoking the rest of the incoming message pipeline, because the pipeline has ACK as the last step.

The easiest way to do it is to call `MessageContext.Current.AbortDispatch()` (`AbortDispatch` is an extension method on `IMessageContext`)

It signals to the dispatch step that the handler pipeline should not be invoked. Everything else will work normally – it'll just skip invoking handlers.
