### ISSUE TITLE
Question out of curiousity: extremely large git repo

### ISSUE THREAD

**Issue by larsw** [rebus-org/Rebus#702]
remote: Counting objects: 36836, done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 36836 (delta 26), reused 36 (delta 14), pack-reused 36785
Receiving objects: 100% (36836/36836), 462.02 MiB | 677.00 KiB/s, done.
Resolving deltas: 100% (25836/25836), done.

As the title says; from a historical perspective, why is this repo so large?

**Comment by mookid8000** [comment]
It packs almost 6.5 years of history, including a time when NuGet packages were committed to the repository 😰 

It's probably mostly because of the NuGet packages 😁 

But – what exactly do you mean by "extremely large"? On my machine it takes up less than 600 MB

![image](https://user-images.githubusercontent.com/32968/40544682-76309de8-6029-11e8-9ec6-05127216a9a8.png)
