### ISSUE TITLE
How do I set MessageID property of a message sent in the bus queue

### ISSUE THREAD

**Issue by acolangelo86** [rebus-org/Rebus#720]
Hi,
I'm using rebus with Azure Service Bus.
I did enabled duplicate detection on the Azure queue.
I want to try to manage directly the property MessageId of every message.
How can I achieve my objective?
Thanks.

**Comment by mookid8000** [comment]
Unfortunately, Rebus does not set the Azure Service Bus message ID to anything when creating the `BrokeredMessage` to be sent.

It _could_ have used [the same approach as when transferring the correlation ID](https://github.com/rebus-org/Rebus.AzureServiceBus/blob/master/Rebus.AzureServiceBus/AzureServiceBus/MsgHelpers.cs#L39-L43) but it doesn't 😞 

If it's something you feel is needed, PRs are always welcome 😄

**Comment by mookid8000** [comment]
Just had a few minutes of spare time yesterday – I went and made it so that Rebus' message ID is set on the `BrokeredMessage`, which means you can now do this:

```csharp
await bus.Send(message);
```

and count on Rebus assigning a message ID, which is then also used on the `BrokeredMessage` delivered to Azure Service Bus, or this:

```csharp
var headers = new Dictionary<string, string> {
    {Headers.MessageId, "whatever you like"}
};

await bus.Send(message, headers);
```

if you want to explicitly specify an ID.

It's available in Rebus.AzureServiceBus 5.0.0-b01, which is on NuGet.org in a few minutes.
