### ISSUE TITLE
Not all handlers are invoked if there is exception thrown from one of the handlers

### ISSUE THREAD

**Issue by Liero** [rebus-org/Rebus#745]
GIVEN that both Handler1 and Handler2 implements IHandleMessange<MyMessage>
WHEN Handler1 throws exception
THEN Handler2 is never invoked.

Is this expected behavior? I guess that handlers should be independent by default.

Repo:

```csharp
using Microsoft.Extensions.DependencyInjection;
using Rebus.Bus;
using Rebus.Handlers;
using Rebus.Routing.TypeBased;
using Rebus.ServiceProvider;
using Rebus.Transport.InMem;
using System;
using System.Threading.Tasks;

class Program
{
    static void Main(string[] args)
    {
        var services = new ServiceCollection();
        services.AutoRegisterHandlersFromAssemblyOf<Handler1>();
        services.AddRebus(configure => configure
            .Transport(t => t.UseInMemoryTransport(new InMemNetwork(), "Messages"))
            .Routing(r => r.TypeBased().MapAssemblyOf<Message1>("Messages")));

        var provider = services.BuildServiceProvider();
        provider.UseRebus();

        IBus bus = provider.GetRequiredService<IBus>();
        bus.Send(new Message1()).Wait();

        Task.Delay(1000).Wait();
    }
}

public class Handler1 : IHandleMessages<Message1>
{
    public async Task Handle(Message1 message)
    {
        Console.WriteLine("Handler1 invoked");
        await Task.Delay(10);
        throw new Exception("My Custom Exception");
        Console.WriteLine("Handler1 handled");
    }
}
public class Handler2 : IHandleMessages<Message1>
{
    public async Task Handle(Message1 message)
    {
        Console.WriteLine("Handler2 invoked");
        await Task.Delay(10);
        Console.WriteLine("Handler2 handled");
    }
}
```

**Comment by mookid8000** [comment]
> (...) I guess that handlers should be independent by default.

Not within a single endpoint they shouldn't 🙂 since there's no way to partially consume a message and thus be able to retry delivery to the failing handler, message delivery is implemented as an "all-or-nothing"-operation.

This also means that a failure in one handler means that the rest of [the handler pipeline](https://github.com/rebus-org/Rebus/wiki/Handler-pipeline) will not be invoked.

Also, this – the fact that handlers are invoked one at a time, as an ordered sequence – is what makes it possible to "filter" incoming messages, e.g. by providing a special handler that implements `IHandleMessages<object>`, say something like `CheckDepartmentHeaders`:

```csharp
Configure.With(...)
    .Options(o => {
        o.SpecifyOrderOfHandlers(o => o.First<CheckDepartmentHeaders>());
    })
    .Start();
```

which could then look somewhat like this:

```csharp
public class CheckDepartmentHeaders : IHandleMessages<object>
{
	readonly IMessageContext messageContext;

	public CheckDepartmentHeaders(IMessageContext messageContext) 
	{
		this.messageContext = messageContext;
	}

	public async Task Handle(object _)
	{
		// if headers are good, let message through
		if (ValidateHeaders(messageContext.Headers)) return;

		// otherwise: tell Rebus not to dispatch message
		// to handlers following this one
		messageContext.AbortDispatch();
	}

	bool ValidateHeaders(Dictionary<string,string> headers)
	{
		// (...)
	}
}
```

I hope this makes it clear why it was decided to dispatch messages like that 😄 please let me know if this is a problem to you, and then I'll help you find another to do what you're trying to achieve.

**Comment by Liero** [comment]
The retry strategy attempts retries only failed handlers, or entire pipeline?

**Comment by mookid8000** [comment]
> The retry strategy attempts retries only failed handlers, or entire pipeline?

**Short answer**: The entire pipeline will be invoked – again and again 😄 

**Explanation**:

The retry strategy works by rolling back the message transaction, effectively putting the message back in the queue.

The next time the message is received, an in-mem counter will remember how many times message consumption has failed, and that's it.

You're encouraged to write your code such that all work done within a message handler pipeline is carried out in the same transaction or is idempotent, so that your system doesn't end up in an inconsistent state if a message gets re-delivered.

**Comment by Liero** [comment]
I understand. Where should I then place the BeginTransaction and CommitTrasnaction, or some UoW implementation?


Anyway, I have this idea: It would be nice to optionally "Continue on Error" in some particular handler, while moving the message to error queue. (I see analogy in TFS build steps, where you can set step to "Continue on Error" but when any build step fails, the entire build pipeline still fails.

I guess that Retry per handler is  possible to implement by customizing HandlerInvoker, right?

**Comment by mookid8000** [comment]
Rebus has a [unit of work package](https://www.nuget.org/packages/Rebus.UnitOfWork/) that helps you hook into the right places.

You can read more about it [here on the wiki](https://github.com/rebus-org/Rebus/wiki/Unit-of-work#hooking-into-rebus-in-the-right-places).

If you want to "continue on error", it suggests to me that you have parts of your work that can fail, and other parts that must be executed anyway. My suggestion to you is to consider whether you would be better off using several messages to model the steps in your pipeline.

Even though Rebus has a "message handler pipeline", it's not necessarily the pipeline you're looking for 😄 although, I don't know enough of your problem to be able to give exact advice, please just consider this as inspiration.

**Comment by mookid8000** [comment]
> I think rebus (and probably message bus in general) is not suitable choice.

I think so too.

A service bus could easily find a place in an event sourced architecture, but I would not use it to do the actual event projection.

In event processing, you usually want deterministic dispatch and replay of events, so you can be sure your projections consistently end up in the same state. This puts a requirement on being able to correctly process events in order within a partition of some kind. 

Message queues are pretty bad at delivering things in order. While most queues are of the FIFO kind, processing messages from a queue is usually done in parallel (either by multiple processes, or by means of enabling some level of parallelism within a consumer), which makes it very susceptible to a slight re-ordering of the messages. And even if you reduce the parallelism to 1, most buses will move failed messages to an error queue, which would mess up the ordering at a grander scale 😁 

So, to correctly process events in order in a consistent manner, your best best is probably to read them directly from the event store.

In conjunction with CQRS and event sourcing, I could see myself use a service bus to reliably and asynchronously deliver commands. A bus could also be used as a process manager, subscribing to events, correlating them, and then issuing new commands. Or if you wanted to distribute the processing of individual events within a project to multiple workers, because they're computationally intensive and independent of eachother.
