### ISSUE TITLE
Question about Routes vs Transport

### ISSUE THREAD

**Issue by dicko2** [rebus-org/Rebus#747]
I'm working on a Kafka transport, and i need to subscribe to all the topics on startup.

as far as i can see the TypeBasedRouter does not expose the full list of topics in anyway, so i think that this will require a new method to return the full list from _messageTypeAddresses.

Is that right or am I missing something?

I am thinking I'll need something like the below in the configuration

```csharp

        public static void UseKafka(this StandardConfigurer<ITransport> configurer,
            string brokerList, string groupId)
        {
            
            configurer.Register(c =>
            {
                var router = c.Get<IRouter>();
                var rebusLoggerFactory = c.Get<IRebusLoggerFactory>();
                var asyncTaskFactory = c.Get<IAsyncTaskFactory>();
                var listOfTopics = router.GetListOfTopics();
                return new KafkaTransport(rebusLoggerFactory, asyncTaskFactory, listOfTopics, brokerList, groupId);
            });
        }
```

**Comment by mookid8000** [comment]
> (...) and i need to subscribe to all the topics on startup

Why? 😄 I'm not an expert on Kafka, but to me it would seem like all endpoints would need to subscribe to these topics:
- a topic for the input queue
- a topic for each topic explicitly subscribed to via `await bus.Subscribe<T>(...)` (which in turn translates into `await bus.Advanced.Topics.Subscribe(someString)`)

This way, `await bus.Send(...)` (which always sends to 1 recipient) would append to some particular endpoint's input queue topic, and `await bus.Publish(...)` would append to the event's topic.

As far as I can tell, there's no need to subscribe to ALL topics for anyone..... or am I missing something here?

**Comment by dicko2** [comment]
Perhaps I'm miss understanding the use. I've just been looking at the samples. 

I guess there is an architectural question as to if you use the topic mechanism of the underlying transport, or house this in the abstraction. I am trying to use the topic mechanism of the messaging platform. 

Following the example code, I pass a func to the handler for type X, but then do I also need to call subscribe for type X as well?

Also where does subscribe connect to the transport layer? As far as I can see the only connection is at instantiation. 

Methods are

Send
Receive 
Create queue 

And the error library is the only thing that calls create queue. So I think I am missing how the transport is told what topics to listen to. 

I've made public the code I'm working on if you want to have a look here:

Github.com/agoda-com/Rebus.kafka 

This is (a work in progress) using the version compiled from my Pr. 

The single test in the test project is me following the example code, and may explain where I am coming from better

**Comment by dicko2** [comment]
Please bare with me, I'm not very smart.. But I can fix tractors :)

**Comment by mookid8000** [comment]
> But I can fix tractors :)

Damn! That's pretty cool and tangible 😁 the best thing I can do in the real world is I can brew beer.

**Comment by mookid8000** [comment]
I can certainly understand why it might be a little bit hard to understand, especially if you haven't really worked with messaging models like Rebus (and NServiceBus and MassTransit etc.) before.

WIth Rebus, everything is received from a "queue" (in quotes, because it might not be an actual queue, but conceptually it is – it's a queue of messages to be delivered to one particular message consumer).

The "queue" concept is easily filled in when using MSMQ, RabbitMQ, Azure Service Bus, Amazon SQS, etc., because they all have actual queues. It's slightly more tricky when using Kafka, because all it has is topics. So I imagine a special category of topics, where each topic would only be used by one specific subscriber, which would then function as the "input queue" of the Rebus endpoint.

Queues are great for point-to-point messaging where one sender sends a message to one particular recipient, because then the message simply goes into the recipient's input queue. It's slightly more involved, when we want to do publish/subscribe messaging.

When we do pub/sub, the actual mechanics of it are pretty much determined by the underlying transport mechanism. E.g. with RabbitMQ, Rebus simply translates a call to `await bus.Subscribe<SomeType>()` into a BINDING from the topic "SomeNamespace.SomeType, SomeAssembly" to the caller's input queue. With MSMQ, the call to `Subscribe` would register the subscriber in a database somewhere, which the publisher would then query whenever it publishes something.

# Two ways of sending messages

I've hinted at it already, but just to be entirely clear about it: Rebus has two basic ways of sending outbound messages:
1. Sending them: `await bus.Send(someMessage)`
1. Publishing them: `await bus.Publish(someEvent)`

1) Is meant for scenarios where you want EXACTLY one recipient to get the message. Rebus uses "endpoint mappings" to look up a queue name from the message type, and then the message is sent directly to that queue.

2) Is meant for scenarios where you basically don't want to know or care whether 0 or 100 queues get the message. Rebus uses the "subscription storage" (or the transport's built-in pub/sub capabilities) to distribute a copy of the message to each subscriber.

Let's take a look at how I imagine these two scenarios translate to the Kafka world:

# 1. Send scenario

Consider a scenario where I have implemented an EmailSender (responsible for sending all outbound emails). The EmailSender would NOT subscribe to any topics besides its own "input queue" topic, e.g. "queue.EmailSender" (adopting the convention that Kafka topics are named either "queue.<name-of-queue>" or "topic.<name-of-topic>".

When I want to send an email, I would then send a `SendEmailCommand` by calling Rebus' `await bus.Send(new SendEmailCommand(..))`. Rebus would then look through its endpoint mappings, and I would then have configured an endpoint mapping like this:
```csharp
Configure.With(...)
	.Transport(t => t.UseKafka(...))
	.Routing(r => {
		t.TypeBased()
			.Map<SendEmailCommand>("EmailSender");
			//                       /\
			//   corresponds to queue.EmailSender
	})
	.Start();
```
which would make Rebus route all SENT (not published) messages of type `SendEmailCommand` to the "queue" "EmailSender", which would be translated into the topic "queue.EmailSender" by the transport.

# 2. Publish scenario

Consider a scenario where an order processor of some kind is kind enough to let the world know, when it has processed an order. Pub/sub messaging is great for these things. The order processor would simply `await bus.Publish(new OrderProcessed(...))` after having processed each order.

In Kafka, this would translate into publishing the `OrderProcessed` event to a topic called "topic.OrderProcessed" (following the convention from before). Done deal 😁 

At the subscriber's end, I would `await bus.Subscribe<OrderProcessed>()` as part of my startup routing, and I would probably never unsubscribe again – the rule in Rebus is that subscriptions are PERSISTENT, so when you subscribe, it means you get all messages of that type forever (or until you unsubscribe).

With Kafka, I guess `await bus.Subscribe<OrderProcessed>()` would simply start subscribing to the "topic.OrderProcessed" topic, but _a very import thing to observe here_ is the fact that the subscription must resume from where it last left off!

This is actual a general thing: Some kind of (maybe local?) storage would be required to store the positions where the endpoint last came within each topic.

That was a pretty long text, I hope I could make myself understandable. I think introducing a Kafka-based transport would be extremely interesting, but as you can probably see by now, it's not a clear-cut candidate, as some of the concepts need a little b it of shoehorning 😁

**Comment by dicko2** [comment]
ok so i think i see where I missed it, there is the subscription storage i need to implement as well. I was looking at the AWS SQS transport as an example is why :(

I'll take another look at that, this may explain what I've been missing.

Either way though you do need to know the Handler needs to know about the queues, but i guess you can do a listen to a queue (or topic in Kafka) based on wild card e.g. "queue.*"

But yes i can see with the ISubscriptionStorage the methods on there can be used to handle the subscriptions to topics.

Let me get back to you.

Also there's a few other options in Kafka, I'm talking to our data guys at Agoda about how the best way is to handle the serialization of the message, it's worth putting some effort into as the reason people usually use Kafka is performance related,what I've done so far is a bit hacky.

But i'll try not to do something that brings in dependencies, or do it in a way that they are optional to keep with your mission statement :)

**Comment by mookid8000** [comment]
> Either way though you do need to know the Handler needs to know about the queues, but i guess you can do a listen to a queue (or topic in Kafka) based on wild card e.g. "queue.*"

not entirely sure I understand what you mean there, but sure – you need to declare somehow which topics to subscribe to in Kafka, but I think that gets solved nice and easy, simply by
1. Rebus automatically subscribing to the input queue topic, and
1. Rebus subscribing to each topic subscribed to via the `await bus.Subscribe<T>()`/`await bus.Topics.Subscribe("some-topic")` operations

Since the Kafka transport will natively support pub/sub, the transport should implement and register itself as `ISubscriptionStorage` in addition to `ITransport`. You might want to check out [the Azure Service Bus transport](https://github.com/rebus-org/Rebus.AzureServiceBus/) for an example on how a transport can fill the two roles as transport and subscription storage simultaneously.

**Comment by glazkovalex** [comment]
dicko2, I'm glad your initiative implement support Kafka's transport!
For example, the NServiceBus supports Kafka's transport. Here is the source package for this transport:
https://github.com/pablocastilla/NServiceBus.Kafka
Maybe this will help you.

**Comment by mookid8000** [comment]
so @dicko2 , have you had time to process all of this information? 😁

**Comment by mookid8000** [comment]
As this was mostly a question, and I think it has pretty much been answered, I'm closing this issue for now. Feel free to come back, if you feel it has not been resolved.

**Comment by glazkovalex** [comment]
> Pub/sub does not work in @dicko2 [implementation](https://github.com/agoda-com/Rebus.Kafka).
> There's been no progress for four months. I decided to write my own implementation that will work both in Send/Receive and in Pub/Sub. Thanks to @dicko2's [project](https://github.com/agoda-com/Rebus.Kafka) and @mookid8000's [comments](https://github.com/rebus-org/Rebus/issues/747), Rebus turned [Rebus.Kafka](https://www.nuget.org/packages/Rebus.Kafka). Works faster than Rebus.RabbitMQ 🙂
> If you have any recommendations or comments, I will be glad to hear.
