### ISSUE TITLE
Autofac resolution failes for message handlers implementing IFailed<> of base classes

### ISSUE THREAD

**Issue by oliverhanappi** [rebus-org/Rebus#753]
Given a message `DerivedMessage`, which derives from `BaseMessage`. When a message handler implements `IHandleMessages<IFailed<BaseMessage>>`, the Autofac handler activator does not resolve the handler for `IFailed<DerivedMessage>`. Tested with Rebus.Autofac 5.2.0.

The following test fails with the message "resolving handlers for failed **derived** messages failed":

````
[TestFixture]
public class FailedResolutionTests
{
    private abstract class BaseMessage { }
    private class DerivedMessage : BaseMessage { }

    private class TestHandler : IHandleMessages<BaseMessage>, IHandleMessages<IFailed<BaseMessage>>
    {
        public async Task Handle(BaseMessage message) { }
        public async Task Handle(IFailed<BaseMessage> message) { }
    }
    
    [Test]
    public async Task ResolvesFailedOfBaseClass()
    {
        var builder = new ContainerBuilder();
        builder.RegisterHandler<TestHandler>();

        var activator = new AutofacHandlerActivator(builder, (_, __) => { }, startBus: false);
        using (var container = builder.Build())
        using (var scope = new RebusTransactionScope())
        {
            var handlers = await activator.GetHandlers<DerivedMessage>(null, scope.TransactionContext);
            Assert.That(handlers, Is.Not.Empty, "resolving handlers for derived messages failed");

            var handlersFailed = await activator.GetHandlers<IFailed<DerivedMessage>>(null, scope.TransactionContext);
            Assert.That(handlersFailed, Is.Not.Empty, "resolving handlers for failed derived messages failed");
        }
    }
}
````

**Comment by mookid8000** [comment]
I've investigated this now, and I remember now what happened: Since Autofac is capable of doing contravariant lookup (i.e. find polymophically compatible handlers e.g. for the concrete lookup `IEnumerable<IHandleMessages<FailedMessageWrapper<DerivedMessage>>>`, which should yield handlers implementing `IHandleMessages<IFailed<DerivedMessage>>`), this responsibility was moved to the container.

However, since Rebus does not mess with your container builder without telling you about it, you must manually enable this capability on the `ContainerBuilder`:
```csharp
builder.RegisterSource(new ContravariantRegistrationSource());
```

Could you maybe update to Rebus.Autofac 6.0.0-b02 and see if it solves your problem?

**Comment by oliverhanappi** [comment]
Hi @mookid8000,

unfortunately it does not work. The ContravariantRegistrationSource indeed enables resolving `TestHandler` when requesting `IHandleMessages<DerivedMessage>` (a case of contravariance), however it does not address the `IFailed<>` issue, which is a form of covariance and not contravariance.

I am interested in solving this issue and would like to contribute a bugfix if you like.

I have two possible solutions in mind:

1. Create a custom Autofac registration source which addresses the covariance issue. This is probably the more "elegant" way to handle it, however also the more risky way because it impacts the whole container. I wonder if something like that should be contributed directly to Autofac.
2. Add special handling for IFailed<> to AutofacHandlerActivator. This option is less risky because it does not impact the whole container, however probably not as elegant as a custom registration source. It is probably the more feasible thing to do.

What do you think?

**Comment by mookid8000** [comment]
> (...) which is a form of covariance and not contravariance (...)

It's quite complicated, but no 😁 since the interface is declared as `IFailed<out TMessage>`, Rebus' `FailedMessageWrapper<YourMessage>` is a compatible subclass of `IFailed<YourMessage>`, and thus a handler implementing `IHandleMessages<IFailed<YourMessage>>` is compatible by contravariance when looking for implementations of `IHandleMessages<FailedMessageWrapper<YourMessage>>` (C#'s generics rock!)

When I do this:
```csharp
builder.RegisterSource(new ContravariantRegistrationSource());
```
it works as it should.

Check out [this test](https://github.com/rebus-org/Rebus.Autofac/blob/master/Rebus.Autofac.Tests/Bugs/RegistersHandlerAsImplementationOfIFailedToo.cs#L22-L63) for a full example.

**Comment by oliverhanappi** [comment]
The test you reference uses `string` as message type, however the issue *only* occurs with derived messages when the message handler handles the base message. See my pull request rebus-org/Rebus.Autofac#12 which adds a test reproducing the issue.

**Comment by oliverhanappi** [comment]
As I said above:

> I have two possible solutions in mind:
> 
> 1. Create a custom Autofac registration source which addresses the covariance issue. This is probably the more "elegant" way to handle it, however also the more risky way because it impacts the whole container. I wonder if something like that should be contributed directly to Autofac.
> 2. Add special handling for IFailed<> to AutofacHandlerActivator. This option is less risky because it does not impact the whole container, however probably not as elegant as a custom registration source. It is probably the more feasible thing to do.

I think option 2 is the more feasible way to go. I would add some special logic for IFailed<> which iterates base types as it was in Rebus.Autofac <= 5.x. Something like this (in pseudo code):

````
IEnumerable<IHandleMessages<T>> AutofacHandlerActivator.GetHandlers<T>()
{
   if (T is IFailed<X> && X.BaseType != null) {
      yield return GetHandlers<IFailed<X.BaseType>>();
   }
}
````

If that option sounds good for you I could create a bugfix for that.

**Comment by mookid8000** [comment]
It's nice of you to offer fixing this issue 👍 I spent my lunch break playing around though, and I've release Rebus.Autofac 6.0.0-b03 to NuGet.org now with a fix.

I did pretty much what you describe as options (2), although in a way that caches a "resolver" for each dispatched message type, so that the necessary reflection is only carried out once per dispatched type.

It would be great if you could try it out and see if it fixes your issues.

**Comment by oliverhanappi** [comment]
It works now, thanks for the quick fix 👏 

Albeit not that relevant for the real usage in Rebus I want to point out that the fixed code has some flaws regarding the reflection being used. For instance, `handlerActivator.GetHandlers<IFailed<DerivedMessage>>()` does not work as well as `handlerActivator.GetHandlers<SpecialFailed>()` with `class SpecialFailed : IFailed<DerivedMessage>`. 

One flaw is for instance [here](https://github.com/rebus-org/Rebus.Autofac/commit/40949ff33fd1466b0b8850398f49fd644ecca25d#diff-777b5c5b7d2f9fb3638460e998836795R119): the check `messageType == typeof(IFailed<>)` should be `messageType.GetGenericTypeDefinition() == typeof(IFailed<>)`.

I have written some extension methods for handling generic type parameters for some other project and I am pretty sure that these handle more edge cased. I created the pull request rebus-org/Rebus.Autofac#13 to incorporate them.
