### ISSUE TITLE
Upgrade options for SqlServer transport

### ISSUE THREAD

**Issue by oliverhanappi** [rebus-org/Rebus#755]
Rebus 5 introduces a breaking change in the SqlServer transport by moving from a single table to a table per queue layout. Furthermore, date times are now stored using the datetimeoffset rather than the datetime2 data type.

Is there any guidance on how to perform an upgrade to the new table layout without having to upgrade and deploy all affected services at once? Our system consists of many independently deployed services, a coordinated deployment is not really an option for us.

It would be nice to have an optional fallback strategy to the single table layout implemented in the SqlServer transport to enable a zero downtime migration process. We have the following idea in mind:

The SqlServer transport offers two options:

1. an option to receive messages from the common table in addition to the per queue table
2. an option to send messages to the common table instead of the per queue table

The migration process would then be carried out as follows:

Phase 1

* All services are on Rebus 4 and receive messages from and send messages to the common table.
* Services gradually upgrade to Rebus 5 and configure the SqlServer transport to receive messages first from the per queue table and then as fallback from the common table. Sent messages are configured to be stored in the common table such that services still running on Rebus 4 are able to receive them.

Phase 2

* All services are now on Rebus 5 and are able to receive messages from the per queue table, even though all messages are still sent to the common table.
* Services gradually reconfigure the SqlServer transport to send messages to the per queue table. Receiving messages remains configured to both tables, the per queue as well as the common table bcecause some services are still sending to the common table.

Phase 3

* All services are now sending messages to the per queue table.
* Services gradually reconfigure the SqlServer transport to receive messages only from the per queue table.
* All services are now using the new table per queue layout

**Comment by mookid8000** [comment]
Hi @oliverhanappi , sorry for taking so long to answer your question. I think the reason it took me so long, is because I was wondering why you say

> The SqlServer transport offers two options:
>
> 1. an option to receive messages from the common table in addition to the per queue table
> 2. an option to send messages to the common table instead of the per queue table

because I don't think that's true... from version 5, it's true that Rebus' SQL transport offers two major modes of operation, but they're

1. ordinary `;WITH-crazy-SQL-stuff-DELETE-row-SELECT-data-from-deleted-row-out-here` type of receive (i.e. a `DELETE` that in one single operation deletes the row, keeping a lock on it, returning the data of the deleted row)
1. lease-based `;WITH-crazy-SQL-syntax-UPDATE-row-and-select-it-out-here` type of receive (i.e. an `UPDATE` that in one single operation updates a timestamp on the message row, effectively grabbing a lease on it)

I don't think there's any real good way to transition (that) slowly to version 5 of the transport.

Unless you have a crazy number of endpoints, I suggest you simply coordinate the update and make the downtime as short as possible. If you plan the order in which you update the endpoints carefully, you should be able to update one endpoint at a time.

Keep an eye out for non-existent queues, though, because with the new model (where queues are actually tables in the database), you will suddenly get an error if you

```csharp
await bus.Advanced.Routing.Send("non-existent-queue", someMessage);
```
which aligns well with the behavior of all other transports, but might not be beneficial in your scenario.

So what you could do is this: Let Rebus create the first queue table, and then figure out the names of all the other necessary queue table, and manually execute creation scripts for all queue tables. After this is done, you should be able to update one endpoint at a time.

If you're worried that you're going to run into trouble, you should probably prepare a branch in your source control, so you can switch each code repository more quickly.

I hope that gives you some inspiration. Feel free to come back if there's something you're in doubt about 😄

**Comment by oliverhanappi** [comment]
I know that the transport does not offer the outlined options at the moment. It is just an idea on how a migration without downtimes could work :-)

We are still discussing this on our team, but would you accept a pull request introducing such options for migration purposes?

We have about 10 components from different systems communicating over a bus which makes a coordinated deployment somewhat of a hassle.

**Comment by mookid8000** [comment]
> would you accept a pull request introducing such options for migration purposes?

I'd rather not, actually. I'm worried about the complexity of it. 😳

I suggest you update your code to version 5 of the transport, and then copy/paste the source code of the old transport in, and make it configurable from the outside whether to use the old or the new transport when the program starts.

This way, you can prepare all endpoints for the upgrade, almost like you initially suggested – just with a small window where you go in, and – in the correct order – reconfigure each endpoint to start working with the real v5 transport.

The trick is, of course, to upgrade the endpoints in an order that does not break something (because a destination queue suddenly doesn't exist) while leaving the old messages table empty after finishing.

If you do end up with messages in your old messages table, it shouldn't take too much T-SQL to select them into their respective queue tables though.

**Comment by oliverhanappi** [comment]
Thank you for your feedback. We will probably go for something like what you outlined 😃
