### ISSUE TITLE
Easy way to standardize header names?

### ISSUE THREAD

**Issue by ctcoulter** [rebus-org/Rebus#757]
Is there a preferred / easy way to modify the default header names for Rebus? For example: `rbs2-corr-id`.

In my current project, a good amount of our services are written in Java and are using their own custom messaging library with more standard headers, e.g. `CorrelationId`. Obviously it wouldn't make sense to modify our custom messaging implementation to match the Rebus convention.

It looks like the headers are hard-coded as constants by default in the `Headers` class. I'm thinking I'd need to add some pipelines to outgoing and incoming messages to convert these headers, but that seems jenky. Any ideas or something I'm missing?

**Comment by mookid8000** [comment]
When people ask me about integrating Rebus tightly this way with other messaging systems, I generally advise them to avoid doing it like that, and treat it as an integration point, instead of pretending that the Rebus endpoint and the other things are part of the same bus.

It _could_ be a fun experiment though to try it, and if the things outside of Rebus don't behave very differently, it might also work 😄 

If I were you, I would probably see if I could decorate Rebus' [`ITransport`](https://github.com/rebus-org/Rebus/blob/master/Rebus/Transport/ITransport.cs) interface and then change the headers as the very last thing before the message hits the actual transport.

You can install a transport decorator like this (pretending you're using RabbitMQ):

```csharp
.Transport(t => {
	t.UseRabbitMq(...);

	t.Decorate(c => {
		var transport = c.Get<ITransport>();
		return new CustomHeadersTransportDecorator(transport);
	});
})
```
