### ISSUE TITLE
Support for Serverless Architecture

### ISSUE THREAD

**Issue by robvanpamel** [rebus-org/Rebus#760]
Hi @mookid8000 

At this moment we have integrated Rebus in our projects by making use of the AmazonSQS client which is working fine. As we are evolving our architecture to work more and more serverless, we would like to proceed further with Rebus as well. 

When proceeding to the serverless architecture, the service which is hosted will not poll the queue anymore like this is done at this moment, simply cause there is no service running anymore. However whenever a message is pushed on the SQS queue, a lambda function will be executed to process the message. Are there already some projects which are making use of this approach? Are can you guide us into the correct direction.

The AmazonSQS client which exists at this moment, is making use of the Transport interface which is used for polling the AmazonClient for messages on the Queue. We were looking at creating another implementation of the ITransport interface, but since this is also responsible for creating and sending message to the queue, this doesn't felt 'correct'. 

Kind regards
  Rob

**Comment by mookid8000** [comment]
Interesting question 🙂 

One of the first things that worry me when thinking about Rebus in a serverless architecture, is that for stuff to make sense in a serverless context, it has to start up really quickly.

Moreover, something in Rebus would have to be turned upside-down, because – as you correctly pointed out – Rebus is pretty much built under the assumption that it has to poll something to get a message, and that does not resonate very well with the callback-oriented nature of FaaS.

Having said that, there's nothing wrong with dreaming a little bit 😁 do you know which APIs exist for having code executed when a message is received in an SQS queue?

**Comment by robvanpamel** [comment]
I created a small gist file where you can see the code which is executed. 
Please find it on:
https://gist.github.com/robvanpamel/68c22928c02f18d2e871c8c161a1e194 

As you can see the SQS message is already there, so there is no need to poll for it. 
However it is possible that the event contains multiple messages as well.

**Comment by robvanpamel** [comment]
In the documentation it is mentioned likes this

For each batch of messages processed if the function returns successfully then those messages will be removed from the queue. If the function errors out or times out then the messages will return to the queue after the visibility timeout set on the queue. Just as a quick note here, our Lambda function timeout has to be lower than the queue’s visibility timeout in order to create the event mapping from SQS to Lambda.

However it is possible to set the batchsize to 1. So if this is the issue I would accept that an exception is thrown if multiple messages are returned.

**Comment by mookid8000** [comment]
Hi @robvanpamel , I don't have time to help you investigate this, sorry. But if this is something you are interested in pursuing, I'll be happy to assist you 😄 I'm closing this issue for now, but feel free to continue posting in here if you have comments or questions.
