### ISSUE TITLE
Problem to inject service into a message handler with simple injector

### ISSUE THREAD

**Issue by danilosingh** [rebus-org/Rebus#764]
I'm starting with Rebus.
We are implementing an Event Bus, using Rebus.
The project is a Web API. In one of the services an event is added to perform an asynchronous workload.
We intend to handle the event in the same API project, because the goal is just not to let the user wait for this processing during the request and the volume of requests is small.
Now comes the questions:
We are having trouble injecting a service into the event handler.
We configured the Simple Injector with Hybrid Lifestyle, because we used the same dependency configuration for an integration and unit testing project.
When we try to instantiate the IHandleMessages injecting the service we have the error:
The InvoiceAppService is registered as 'Hybrid Async Scoped / Thread Scoped' lifestyle, but the instance is requested outside the context of an active.

I saw this issue
https://github.com/simpleinjector/SimpleInjector/issues/253

But in our context, we wanted to have all event handlers in the same scope.

This is because we have a UnitOfWork class that is injected into the services, which controls the data transaction.

Could someone help us?

**Comment by mookid8000** [comment]
I generally recommend that people stay away from "hybrid lifestyles" in their IoC containers, because it's often a sign that you're actually trying to host two applications in the same container.

Containers (at least in my mind) are meant to hold one single application, and then you can tweak stuff to match the needs of that particular application, which often involves binding components' lifestyles to e.g. HTTP requests or Rebus message contexts (or WCF operation contexts, or whatever it is that serves the purpose of a "request").

This implies that you need two container instances: One for your Web API, and one for your Rebus backend.

If you do that, everything suddenly becomes simple – most container registrations can stay the same (singletons and transients), and some of them will then have their lifestyle adapted, so they're bound to an HTTP request or a Rebus message context.

If you want to see a simple example on how that can be achieved, check out [this blog post](https://mookid.dk/2015/08/21/how-to-use-rebus-in-a-web-application/) – it handles all the basics of hosting a Rebus endpoint in a web app.

Regarding unit of work: Rebus has a [unit of work plugin](https://github.com/rebus-org/Rebus.UnitOfWork) that makes it pretty easy to handle a custom unit of work – you should check it out 😄 

I hope that solves your problems. If not, please let me know 👍
