### ISSUE TITLE
Feature Request - Defer Publish

### ISSUE THREAD

**Issue by thecontrarycat** [rebus-org/Rebus#777]
Azure Service Bus allows you to defer delivery of all types of messages, but `IBus.Defer()` only works for point-to-point messages.

It appears that you _can_ make deferred publish work by doing something like this:
```
            await _bus.Publish(new OrderPlaced(message.OrderId),
                               new Dictionary<string, string>
                               {
                                   { Headers.DeferredUntil, DateTimeOffset.UtcNow.AddMinutes(1).ToString("O", CultureInfo.InvariantCulture) },
                                   { Headers.DeferredRecipient, "null" }
                               });
```

It would be nice to have a `IBus.DeferPublish<TMessage>(TimeSpan delay, TMessage message)` method, though.

**Comment by thecontrarycat** [comment]
This seems to work (for Azure Service Bus, anyway):

```
    public static class BusExtensions
    {
        public static async Task DeferPublish(this IBus bus, TimeSpan delay, object message)
        {
            Dictionary<string, string> optionalHeaders = BusExtensions.GenerateOptionalHeaders(delay);

            await bus.Publish(message, optionalHeaders);
        }

        public static void DeferPublish(this ISyncBus bus, TimeSpan delay, object message)
        {
            Dictionary<string, string> optionalHeaders = BusExtensions.GenerateOptionalHeaders(delay);

            bus.Publish(message, optionalHeaders);
        }

        private static Dictionary<string, string> GenerateOptionalHeaders(TimeSpan delay)
        {
            DateTimeOffset deferUntil = RebusTime.Now + delay;

            return new Dictionary<string, string>
                   {
                       { Headers.DeferredUntil, deferUntil.ToString("O", CultureInfo.InvariantCulture) },
                       { Headers.DeferredRecipient, "null" }
                   };
        }
    }
```

**Comment by mookid8000** [comment]
I'm curious – what could a possible usage scenario be for deferred publishing of events?

In my mind, you want to publish events whenever something has happened, and you actually pretty much want to tell the world as fast as possible, so subscribers can react accordingly.

I might be missing something here, so I'm curious to know what it could be used for?

**Comment by thecontrarycat** [comment]
So the first thing is that I want the architecture of my system to be purely event-based - no request/response anywhere.

Secondly, I want all messaging to be through a topic, so that there is no future pain if (when) we want to add additional subscribers for any particular message.

The particular scenario I had in mind for this is the case of a saga timeout.  For example, when an Order is placed, the payment and fulfillment services will respond to the event and start processing their parts.  However, if they are unable to complete in a set amount of time, I want to be able to trigger an OrderProcessingTimedOut event that will initiate compensation to cancel the order.  A delayed publish event sounds much easier for this than a service that polls the database or saga (is it even possible to get an instance of SagaData without being in a message handler?).

**Comment by mookid8000** [comment]
Hi @thecontrarycat , have you thought some more about whether you need this?

There's a thing about your previous comment that just made me wonder, whether publishing all events is really the best thing to do?

Rebus (on purpose!) supports two basic ways of sending messages: 1) Sending, and 2) Publishing.

They have slightly different modes of operation, and they are intended for different scenarios.

_Sending_ is usually what you do, when you want to tell someone to do something. You _can_ also use it in request/reply scenarios, but that is generally not recommended, as the reply part tends to increase the level of coupling between the sender and the receiver.

When you _send_ a message with Rebus, there will always be one single destination queue, and you get an error immediately if that queue does not exist (if the transport supports it).

This way, _sending_ is for _when you care that someone handles your message_, and it lends itself well to [command messages](https://www.enterpriseintegrationpatterns.com/patterns/messaging/CommandMessage.html).

Being a command, you would usually name these in the imperative mood: "ProcessOrder", "RecordTransaction", "BlockAccount", etc.

_Publishing_, on the other hand, is usually what you do when you have already done something, and then you want to _provide a hook_ as a service to anyone, who might be interested in hearing about it. As a publisher, you generally shouldn't care whether someone is listening, as it is the subscribers' responsibility to register themselves as subscribers.

Therefore, when you publish, there will be from 0 to many subscribers, and the publisher will never know (at least in the general case – some transports _could_ probably find out if a subscriber was there, but many can't).

In a way, _publishing_ is the smallest degree of coupling you can have, and I definitely understand your sentiment to prefer _publishing_ over _sending_. In fact, I think you _should_ prefer _publishing_ over _sending_ – except when you shouldn't 😄 

Publishing happens to work extremely well with [event messages](https://www.enterpriseintegrationpatterns.com/patterns/messaging/EventMessage.html). Because of this, you will usually name your events in the past tense, e.g. "OrderProcessed", "TransactionRecorded", "AccountBlocked", etc.

So, my point is this: I would not recommend that you require ALL messages to be published. I would recommend that you, in each situation where you feel the need to send messages, ponder whether it's a command or an event, whether you care about someone handling it or not, and – and this is the important part – _in which direction you want to introduce the dependency_!

You see – the INITIATOR when you _send_ is the SENDER, and in that situation the SENDER must know whereto the command must go. Therefore, the SENDER in this situation is "the client" and the RECEIVER is "the server". The server would then be the stable part of the system, the one that can no longer come and go as it wishes.

Contrary to this, when you _publish_, the INITATOR is in fact the subscriber, because it registers itself as such. So, even though the _publisher_ will afterwards publish events to the subscriber, it will simply not know where the events go. Therefore, in this scenario the SUBSCRIBER is "the client", and the PUBLISHER is "the server", also making it the more stable part of the system.

I'm tired now, and I might be rambling a little bit – I hope it makes a little bit of sense 😁 otherwise, please let me know.

**Comment by mookid8000** [comment]
Oh, and also: I have a feeling that being able to defer the publishing of an event into the future is an artificial requirement introduced as a consequence of the desire to _publish_ everything.

If the publisher is truly unaware and uninterested in who subscribed, and who might get the events, then it probably also shouldn't care WHEN the events are received, no?

At least that's my opinion. If you disagree, feel free to convince me that I'm wrong. 😄 

The last line of text I'm typing today is this: Thanks for suggesting this 🙂 It's always great to question one's beliefs, and you pushed me a little bit with this one, which is great. I'm closing the issue for now, but please feel free to try to convince me, if you still thing that it should be possible to publish events into the future.
