### ISSUE TITLE
Potential problems with parallelism and publishing

### ISSUE THREAD

**Issue by ronnyek** [rebus-org/Rebus#779]
Greetings, I'm using the latest version of rebus backed by rabbitmq implementation. This is more of a question about design and whether this is expected behavior, or if this could be because of IOC Activation and stuff.

I've got a service that has one area of it publishing some messages in rapid succession, basically reporting progress of completion for a given process. Sometimes it will step from 0-100 granularly but very fast (which I'm using rx to debounce).

What I've noticed is that something about how i'm publishing or subscribing... its like I log out the percentages and ultimately thats probably no more frequent than a message publish every second or so (sometimes not even that quick)... but seems like the whole process has to complete before I see message handlers picking up on the other side. 

1) Theoretically within reason, I should see the message get published, and given the messages take say 20 seconds to go through the full 100%, I should probably see some of the percentages being picked up on the other side, right?

2) I'm also curious about what the default recommended activation looks like for handlers. Seems like if it was any form of singleton or scoped, that could inhibit how fast messages could be ingested.

3) Finally, are there arguments for or against having handlers that ONLY Handle messages for a specific type? Because some of these messages are dealing with similar functionality, I just made the same class implement handlers for multiple message types. (which does make me wonder if something about how rebus gets an instance of the class, or is creating instances is problematic.

**Comment by mookid8000** [comment]
1. Well .... if you send/publish from within a Rebus handler, all of the outgoing messages will not be committed to the transport until AFTER your code has finished running (but BEFORE acknowledging to RabbitMQ on the received message).

Rebus does this to ensure that your work has finished executing without errors, before the effect of that work can be seen in recipients.

If you want to publish "progress reports" while your handler is executing, you can do so by "escaping" Rebus' transaction context like so:
```
try
{
    AmbientTransactionContext.SetCurrent(null);

    // bus operations are not enlisted in tx context here
    await bus.Publish(...);
}
finally
{
    AmbientTransactionContext.SetCurrent(previousTransactionContext);
}
```

**Comment by mookid8000** [comment]
2: The default recommended lifestyle for Rebus handlers is "transient" (or "instance-per-activation", or whatever your IoC container calls it).

This is generally fast enough, as it's unlikely that this particular `new` will become a bottleneck in your system.

Also, it's a good default, because you then avoid accidentally "trapping" other injected dependencies with other lifestyles.

For SAGA HANDLERS, it's not recommended, it's MANDATORY, because the handler has a `Data` property which gets populated with the saga data currently being handled.

Rebus will throw a nice (but hard) error if it detects an existing value on the `Data` property, so you will know it if you've accidentally configured a saga handler with a singleton lifestyle when the 2nd message hits the saga.... 😁

**Comment by mookid8000** [comment]
3: You are free to implement as many `IHandleMessages<TMessage>` as you like.

I generally prefer to let handlers handle multiple message types when the logic is somehow related, and when the injected dependencies are pretty much the same.

If either the logic is somehow unrelated, OR if the injected dependencies vary, then I prefer a separate handler. This is because it can quickly get confusing if 5 dependencies are injected, but 2 of them are used when handling one message type, and 3 of them are used in handling another message type, thus making it unclear what the handler's responsibilities are.

Also, it can get quite annoying when testing, because it maybe then forces you to inject stuff that is completely unrelated to the test.

**Comment by ronnyek** [comment]
I appreciate this very informative response... I have a much better idea how to handle some of these things now =)
