### ISSUE TITLE
Configuring reconnect wait interval when connection to the bus is lost

### ISSUE THREAD

**Issue by mindisk** [rebus-org/Rebus#785]
I have trouble finding (if it even exist) how to reconfigure the reconnect strategy. From what I witnessed, Rebus will try to reconnect to the bus if the connection is lost. At the moment it seems that Rebus tries to reconnect every 2 seconds and for each failed attempt, it will produce a log message. Thus, over long periods of Rebus being disconnected from a bus, an enormous number of log entries will be produced which will at the end spam the log. 
Perhaps there is some sort of configuration where I could specify the delay between each retry (ideally, it would be a function that I could provide that would produce a new wait interval for each retry)?

**Comment by mookid8000** [comment]
Sorry for taking so long to reply – your question actually made me wonder how Rebus handled errors in the transport during receive, because I thought I had added some kind of chill-down strategy, which would prevent Rebus from littering too much all over the logs in cases where the broker could not be reached.

I'm afraid that's not the case anymore, so I'll add this issue to the backlog for version 6, and then I'll make sure to handle this in an elegant way.

Thanks for raising this issue 👍

**Comment by mindisk** [comment]
Thank yo for responding. Will be waiting for an update.

**Comment by mookid8000** [comment]
A recent contribution actually made it possible to increase the cooldown time _a lot_, without affecting the time it takes for the bus to shut down.

If you try Rebus 6.0.0-b04 I believe this particular thing will be fixed, as it will pause for 30 s by default on every transport error.

**Comment by mookid8000** [comment]
I'll close this one as I believe this is no longer an issue.

**Comment by mindisk** [comment]
I would appreciate if you could give more details on how to adjust the cooldown time. Thank you.

**Comment by mookid8000** [comment]
oh yeah sorry, you're right – I didn't add a friendly API to do it! 😐 

For now, you can edit it by hooking into the resolution of Rebus' `Options` like this:
```csharp
Configure.With(...)
	.(...)
	.Options(o => {
		o.Decorate<Options>(c => {
			var options = c.Get<Options>();

			options.TransportReceiveErrorCooldownTime = TimeSpan.FromMinutes(1);

			return options;
		})
	})
	.Start();
```

**Comment by mindisk** [comment]
Thank you for the help!
