### ISSUE TITLE
Sns and sqs transport

### ISSUE THREAD

**Issue by P47Phoenix** [rebus-org/Rebus#786]
We have made a fork of the SQS transport to support SNS. We would like to look at moving this into the rebus org. Just wondering how this should be handled. Would you like a new repo or a pull the the existing SQS repo?

**Comment by mookid8000** [comment]
Cool! 😎My understanding of SNS is very limited – does it work _together_ with SQS, so that SNS is responsible for fan-out, but messages are still received from SQS queues?

Does it require additional NuGet references in addition to those already referenced from Rebus.AmazonSqs?

**Comment by P47Phoenix** [comment]
It still uses sqs receive messages.
You can now publish to sns or send a message via sqs.

It does require an additional package for AWSSDK.SimpleNotificationService.

**Comment by P47Phoenix** [comment]
I moved the source so you can take a look.
https://github.com/P47Phoenix/Rebus.AwsSnsAndSqs

**Comment by mookid8000** [comment]
Hi @P47Phoenix , I finally got around to looking at your work – it looks really good! 🙂

I just noticed one little thing: You're using C# string interpolation `$""`  pretty consistently throughout together with numbered placeholders, which will not actually work as numbered placeholders, it will just output the number 😅

![image](https://user-images.githubusercontent.com/32968/62006531-d66d7900-b141-11e9-9d07-4c17b1d6eeb1.png)

(in this case, it will always log the string `Updating existing policy on sqs queue 0 for topic 1`)

Also, Rebus has support for named placeholders, so the correct way to log things would be like this (taking the example from above):

```csharp
logger.Debug("Updating existing policy on sqs queue {queueUrl} for topic {topic}", sqsInformation.Url, topicArn);
```

Rebus will then either do the interpolation (if you're using any of the built-in loggers, or a logging library that does not support it), or let the logging library do the interpolation (e.g. with Serilog, which will also deliver the passed-in values in object form `{queueUrl: "whatever", topic: "the-topic"}` allowing you to e.g. query by it, if you're storing your logs in a database).

Regarding this repository, I would like to list it as a community-maintained library on [this page on the wiki](https://github.com/rebus-org/Rebus/wiki/3rd-party-extensions) for now, if that's alright with you? There aren't that many on the list yet, but it's something I would like to do more for extensions like this. The reason I want to wait with adopting it into rebus-org, is because we cannot take responsibility for maintaining it right now, because we don't have any paying customers that rely on AWS + SQS. This will hopefully change some time in the future, so let's keep in touch. 🙂
