### ISSUE TITLE
Multiple buses best practice?

### ISSUE THREAD

**Issue by davidtabatadze** [rebus-org/Rebus#791]
Hey there.

I am using latest version of `Rebus (5.3.0)` on .`net core web application`.
In case when i have one instance of bus, injection works fine:
`IServiceCollection services;`
`services.AddRebus(cfg => cfg.Transport(t => t.UseSqlServer("...", "queue")).Routing(r => r.TypeBased().Map<MyClass>("queue")));`

I have dedicated handler on my `MyClass` like
`MyHandler : IHandleMessages<MyClass>`

So everything looks nice and clean.

My question relates situation, when i need two or more buses (because one bus works on one queue table, since it's forbidden to create multiple `cfg.Transport` under bus configuration).
Adding another instance of bus to services is forbidden: `"Rebus has already been configured"`

I have tried `Rebus.Config.Configure.With(new BuiltinHandlerActivator()).Start()`
This gives me opportunity to create several bus instances, but code is a bit ugly, injection is off and have to create dependency classes artificially.

What is best practice?
Or is "my way" the "optimal solution" for this moment?

Thanks

**Comment by mookid8000** [comment]
The recommended way is to register one single bus instance per container.

This means that if you need to process messages from multiple queues, then you need to new up additional containers.

It's as simple as that 😄 

Just remember to use whatever mechanism your hosting environment provides, to ensure proper disposal of the containers, when the app shuts down.

**Comment by sfmskywalker** [comment]
@mookid8000 I have followed your advice and instantiating separate containers to build new bus instances works great. However, there seems to be a downside to this when using e.g. Postgres as the message broker: for each bus, a connection per worker is used. 

I have an application with 7 bus instances (7 queues to work from). This means that for each node in the cluster, 7 connections are used.

Perhaps this is all fine, but I was wondering if there might be some option to reuse existing connections to the underlying message broker? Or isn't that how it works?

Any insight would be much appreciated!

**Comment by mookid8000** [comment]
@sfmskywalker If you have that many bus instances, I think you would have the same number of connections, regardless of how many container instances they were hosted in.

Although, maybe you should look into hosting the bus instances in different apps? Then you can scale them individually and have fewer instances of the apps that do not require redundancy (which is actually often a totally OK thing to do... when you're using messaging, often there's no need for redundancy, because the system itself can easily tolerate container instances being torn down and brought back up)

If it's a problem because of the polling, I suggest you maybe [tweak the back-off strategy](https://github.com/rebus-org/Rebus/wiki/Back-off-strategy). 

If it's still a problem, maybe it's time to look into using a real message broker?

**Comment by sfmskywalker** [comment]
> If it's still a problem, maybe it's time to look into using a real message broker?

Interesting. So if I were to use e.g. RabbitMQ, then the connection count wouldn't be an issue?

Some more background: I'm using Rebus as part of a workflow library. This library publishes a number of events like "workflow published" and "workflow updated". The same library listens for these messages on all nodes it is hosted on in order to evict cache entries that store these workflow definitions. Using the pub/sub model for a total of 7 or so events. 

For this reason each node will have 7 or so bus instances, since each bus is dedicated to work off a queue (1 queue per message type).

This library allows the developer to configure Rebus in detail, so it's really up to the developer to configure the transport. I will take your response as input to offer guidance via documentation when configuring Rebus.

Thanks for your response and for this great library!

**Comment by mookid8000** [comment]
> (...) 1 queue per message type (..)

You do know that there's nothing that prevents you from having one single queue subscribe to all of your event types?

The reason why you mostly want to have multiple queues in the same process, is in cases where you want different SLAs for individual message types. E.g. if one message type tends to arrive in big bursts, it might be beneficial to direct it to its own queue to avoid affecting the time-to-be-received of other messages.

In your case though, it sounds like you would be happy with having one single queue subscribing to all of the relevant event types. 🙂

**Comment by sfmskywalker** [comment]
Ah! Well, I sort of thought I remembered this was possible, but eventually forgot about it. I always assumed that it was considered mal practice to use the same queue for different types of messages. But your point about different SLAs per message type makes sense. 

Indeed, in my case it would be perfectly OK for a single queue to receive all of the relevant event types.

Thanks for your pointers, it's much appreciated!
