### ISSUE TITLE
Completing Unit of Work after each call to Handler.Handle

### ISSUE THREAD

**Issue by kewinbrand** [rebus-org/Rebus#796]
Hi,

Currently I don't see a way to commit after each call to a handler (when a message is implemented by two or more handlers). Of course this behavior is what I want for my application and Rebus has nothing to do with it. What I have so far is:

This action:

```() => handler.Handle(message)```

from ActivateHandlersStep

```
protected virtual HandlerInvoker CreateHandlerInvoker<TMessage>(IHandleMessages<TMessage> handler, TMessage message, ITransactionContext transactionContext, Message logicalMessage)
{
    return new HandlerInvoker<TMessage>(() => handler.Handle(message), handler, transactionContext);
}
```
 is called in a loop in ```DispatchIncomingMessageStep```.

I could inherit from ActivateHandlersStep and override ```CreateHandlerInvoker``` to customize this action and swap ActivateHandlersStep with my custom step in DefaultPipeline.

What do you think?

Thank you so far.

**Comment by mookid8000** [comment]
Hmm, I would be cautious with that 😄 it raises all sorts of questions, e.g. like "what happens if the first handler fails? what if the second handler fails?" and stuff like that.

Sometimes a nice solution can be to have multiple bus instances, each with its own input queue, and then your can even have the processing parallelized and have them complete/fail independently of each other.

Could that maybe be a better solution?

**Comment by kewinbrand** [comment]
Huumm, ok. That actually looks better. The only thing that makes me apprehensive is the *maybe* fact of overhead that this can cause. 

Thank you
