### ISSUE TITLE
Help on how to approach rapidly requests invoking a saga 

### ISSUE THREAD

**Issue by EduSikora** [rebus-org/Rebus#802]
Hi, 

We need some help on how to approach a scenario where the user does an action that invoke a saga, but the user could invoke multiple times in a short period of time..

A real scenario:

1. The user is creating a order.
2. The user adds and removes items from the order.
3. Every item change invoke a real-time Tax calculation on the total cost of the order.
4. The tax calculation has many steps, which we control by using a Saga.
5. The user adds and removes items from the order very rapidly.

- If the saga is invoked, like 10 times in 2 or 3 seconds, the only request that is really needed is the last one..

Any ideas on how to handle this situation?

**Comment by EduSikora** [comment]
@mookid8000  ?

**Comment by EduSikora** [comment]
Hi @mookid8000,

This is our first very simple saga implementation.. (correct us if there is something weird about it)

![image](https://user-images.githubusercontent.com/21113262/58122221-7f967100-7bdf-11e9-97b9-02835a5d5c38.png)

The example above would only apply to the same CteId..

Any ideas on how to proceed?

**Comment by mookid8000** [comment]
Hi @EduSikora , it's a little bit hard to give you such specific advice, because I don't know anything about your domain.

What I can say is this: Messaging with durable message queues is generally best suited for problems, where each message is important, and you care about having it processed.

Similarly, sagas (at least the implementation that exists in Rebus) are really good for scenarios, where you care about having equally durable orchestration of messaging conversations.

You _could_ definitely solve your tax calculation problem with a saga, and it should be fairly easy to ensure that only one calculation was carried out at any point in time, and ensure that subsequent requests for calculation replace queued-up requests while a calculation is ongoing.

The code in your screenshot looks fine to me 😄
