### ISSUE TITLE
How to deal with messages DTOs in different assemblies

### ISSUE THREAD

**Issue by Klainer** [rebus-org/Rebus#806]
Hello. 

I want to use your Rebus for my project. I have plan to have project separed to multiple Modules. Each assembly / modules represents custom Bounded Context from DDD point of view eg.
Each module will have some events / handlers and will be completly separated. Only possible comunication is by EbventBus / Rebus. I do not have plan to have shared Assembly / modules for messages so each project will be have copy of event with the same name (OrderStartedIntegrationEvent)

IE:
Solution
**- Eshop.Basket**
   - Events
       - OrderStartedIntegrationEvent.cs
  - Handlers
      - OrderStartedIntegrationEventHandler  -- Will delete basket in DB

**- Eshop.Order** _-- Will publish OrderStartedIntegrationEvent_  
   - Events
       - OrderStartedIntegrationEvent.cs

Question is. Is possible to setup Rebus for pub/sub messaging based on Name of type : `OrderStartedIntegrationEvent ` rather then full name of type: `Eshop.Order.Events.OrderStartedIntegrationEvent ` but still have type safe handlers in Basket module namespace.

So I need to have an ability to PublishEvent of diferent type and cosume it in another module with another type but which the same Name of class and the same properties.

Notice:
I have plan use this application on shared hosting (.NET CORE) with MS SQL database. It is possible use pub / sub with Rebus on this hosting (inProcess) ? Thanks again ! :)

Thanks for help!

**Comment by mookid8000** [comment]
It's definitely possible 😄 

You need to be sure that two things support treating `SomeEvent` in different namespaces/assemblies as the same event:

1. Your topic name convention
1. Your serializer

## Topic names

Rebus maps types to topic names via its [`ITopicNameConvention`](https://github.com/rebus-org/Rebus/blob/master/Rebus/Topic/ITopicNameConvention.cs), which by default looks like this 👉 https://github.com/rebus-org/Rebus/blob/master/Rebus/Topic/DefaultTopicNameConvention.cs 

The line that would cause trouble in your scenario is this:
```csharp
return eventType.GetSimpleAssemblyQualifiedName();
```
because it includes assembly name and namespace as part of the type name, so e.g. `SomeEvent` residing in the `SomeCompany.SomeContext.Messages` namespace in the assembly `SomeCompany.SomeContext` would result in a topic named
```
SomeCompany.SomeContext.Messages.SomeEvent, SomeCompany.SomeContext
```
What you want, is to register your own topic name convention like this:
```csharp
Configure.With(activator)
    .(...)
    .Options(o =>
    {
        o.Register<ITopicNameConvention>(c => new SimpleTopicNameConvention());
    })
    .Start();
```
preferable wrapping it in a nice extension method:
```csharp
public static class RebusConfigurationExtensions
{
	public static void UseSimpleTopicNames(this OptionsConfigurer configurer)
	{
		o.Register<ITopicNameConvention>(c => new SimpleTopicNameConvention());
	}
}
```
which would make your Rebus configurations look like this:
```csharp
Configure.With(activator)
 	.(...)
    .Options(o =>
    {
        o.UseSimpleTopicNames();
    })
    .Start();
```

## Serializer

You do not mention which serializer you are using. For this to work, you need to enable deserialization of `SomeEvent` from another namespace/assembly to the receiver's definition of that class.

You can see in [the "Shared Nothing" demo](https://github.com/rebus-org/RebusSamples/tree/master/SharedNothing) how that can be achieved.

**Comment by mookid8000** [comment]
> I have plan use this application on shared hosting (.NET CORE) with MS SQL database. It is possible use pub / sub with Rebus on this hosting (inProcess) ? Thanks again ! :)

Rebus does not have any shared state or static things lying around, so the bus instances will never know that they might be running in the same process 😄 so no problems there.

**Comment by Klainer** [comment]
Thank you for clarifying.
I implemented working solution but I have one problem.

When I Use simple type names (class - names), deserializer must to know concete type.
So If I Have these Modules:
- Eshop.Web.Core - Implements Rebus and Basket / Order Module
- Eshop.Basket
  **Events**
   OrderStartedIntegrationEvent.cs
   **Handlers**
   OrderStartedIntegrationEventHandler<OrderStartedIntegrationEvent> -- Will delete basket in DB

- Eshop.Order -- Will publish OrderStartedIntegrationEvent
   **Events**
   OrderStartedIntegrationEvent.cs
   **Handlers**
   OrderStartedIntegrationEventHandler<OrderStartedIntegrationEvent>

It is possible to setup deseliazer to deserialize event to generic type argument of eventHandlers ?
IE: Two handlers for one event in different assembly but in one process.

Eshop.Basket.OrderStartedIntegrationEventHandler**<OrderStartedIntegrationEvent>**
Eshop.Order.OrderStartedIntegrationEventHandler**<OrderStartedIntegrationEvent>**

Thanks for advice!

**Comment by mookid8000** [comment]
In the SharedNothing demo I linked to above, the custom serializer implementation in the subscriber works by bootstrapping a dictionary of known types: [Dictionary with known types](https://github.com/rebus-org/RebusSamples/blob/master/SharedNothing/Subscriber/CustomMessageDeserializer.cs#L16-L23)

It would probably not take that much work to create a more generic serializer (e.g. by using [the existing JSON serializer](https://github.com/rebus-org/Rebus/blob/master/Rebus/Serialization/Json/JsonSerializer.cs) as inspiration), and then make it 

* use simple class names in the `rbs2-msg-type` header, and
* configurable "from the outside"

so that the configuration API could look like this:

```csharp
Configure.With(...)
	.(...)
	.Serializer(t => {
		var knownTypes = typeof(SomeMessage).Assembly.GetTypes();

		t.UseCustomJsonSerializer(knownTypes);
	})
	.Start();
```

**Comment by Klainer** [comment]
Yes, but there is problem with fact that during deserealization I know simple type name and I can hame maybe 2 assemblies / modules  (inProcess so 1 instace of rebus) which match with this simple name and have the same massage.  I need to deliver 1 message to X eventhandlers in Y assemblies only by simpleName. Seserialization suposse to have 1 x 1 mapping . So when i publish event with simple name, I need to desererialize message for each type of eventhandler in theese X modules. I think that this is only problem with 1 bus instance,. If I Have BUS instance per module I can configure every intance like you mention above so no problem with mapping.
