### ISSUE TITLE
Getting current worker name inside handler

### ISSUE THREAD

**Issue by tompazourek** [rebus-org/Rebus#815]
For logging purposes, I'd like to know which worker is currently processing the current message in my handler.

I couldn't find a way how to do this, but maybe I missed something.

Would something like this be reasonable? I can try to make a PR to see if I can get it working...

```csharp
public async Task Handle(MyMessage message)
{
    var worker = MessageContext.IncomingStepContext.Load<IWorker>();
    Log.Information("The worker processing this message is: {workerName}", worker.Name);

    // ...
}
```

Once the worker is available, I'd use it to build a decorator so that my Serilog log events will be automatically decorated with worker names.

**Comment by mookid8000** [comment]
That would definitely be possible, and I think your proposed solution is really good. 🙂 

There's a thing you need to be aware of, though: The "worker" (i.e. the worker's dedicated `Thread` instance) only executes the message dispatch until the first `await` that results in actual asynchronous work. After that, message dispatch executes on thread pool threads.

_If your chosen transport supports asynchronous receive_ (e.g. like Azure Service Bus, Amazon SQS, etc.), then the receive operation will be asynchronous, and therefore the entire message dispatch will be executed by thread pool threads.

_If your transport has synchronous receive_ (e.g. like MSMQ and RabbitMQ), then the first truly asynchronous operation can be a lot of things, e.g.

* when you're using sagas and Rebus queries for an existing saga instance
* when you're publishing a message in a Rebus handler, and you're using a subscription storage that supports asynchronous queries
* when you're doing something asynchronous yourself

or any time before that, depending on your configuration: Any step in the incoming messages pipeline, and several of Rebus' services open for decoration have asynchronous APIs and thus have the potential to cause the rest of the dispatch to execute on the thread pool.

So.... I guess this is just a really long and convoluted way of asking why you would like to include the worker name in your log output? 😆

**Comment by mookid8000** [comment]
Btw. instead of accessing `IMessageContext` via the static `MessageContext.Current` inside your message handler, I recommend you take advantage of the fact that all Rebus' IoC container adapters have proper injection set up for `IMessageContext`, so you can do this instead:
```csharp
public class MyMessageHandler : IHandleMessages<MyMessage>
{
	readonly IMessageContext _messageContext;

	public MyMessageHandler(IMessageContext messageContext) => _messageContext = messageContext;

	public async Task Handle(MyMessage message)
	{
	    var worker = _messageContext.IncomingStepContext.Load<IWorker>();
	    Log.Information("The worker processing this message is: {workerName}", worker.Name);

	    // ...
	}	
}
```
This is easier to unit test. 👍

**Comment by tompazourek** [comment]
@mookid8000 Thanks for your response. You make a good point about the work not actually being done on the worker, but rather by the thread pool, I did not realize this. My original idea was to have more insight into how the workers are utilized and how busy they are, to see which worker is doing what at each time.

If the entire message dispatch is executed by the thread pool, when would it make sense to increase the number of workers? Is it just to scale out the pipeline work happening before the message dispatch? Can you elaborate what sort of work is the worker doing and when it's utilized?

In the current beta (`6.0.0-b08`), there's also `UseTplToReceiveMessages`. Does the alternative TPL worker factory work differently?

**Comment by mookid8000** [comment]
> If the entire message dispatch is executed by the thread pool, when would it make sense to increase the number of workers? 

If the transport is synchronous (e.g. like MSMQ), then it may make sense to use truly parallel workers. If it's asynchronous (e.g. like Azure Service Bus), then it will often be enough to simply increase the "max parallelism" setting.

> Is it just to scale out the pipeline work happening before the message dispatch? 

That would be one way of putting it, yes 😄 and "work happening before the message dispatch" is the actual receive operation.

> Can you elaborate what sort of work is the worker doing and when it's utilized?

Actually only the receive operation, and then all the work until the first truly asynchronous `await`.

This particular design is mostly a leftover from early Rebus 1 (versions <= 0.84.0), where everything was synchronous, because it targeted .NET 4.0. 

The issue #809 is about revisiting this design – @bbgone has made a fork of Rebus that makes some pretty radical changes, which I need to go over when I have the time.

**Comment by tompazourek** [comment]
@mookid8000 Thanks for the information. I'm closing this issue now, as my original idea with the worker name doesn't really make that much sense.
