### ISSUE TITLE
 .Net 4.5 How To Use RabbitMq Transport

### ISSUE THREAD

**Issue by xiaguoli** [rebus-org/Rebus#818]
Hi,
I want to use rebus rabbitmq transport ,target framework is 4.5, but i don't know which versions i can use.

**Comment by mookid8000** [comment]
Sorry, but the RabbitMQ driver has targeted .NET 4.5.1 for a while now – and for some reason, Rebus' RabbitMQ transport targets .NET 4.5.2, so that's the lowest version of the full .NET framework you can use.

**Comment by xiaguoli** [comment]
Thank you for the quick response.

I need provide an Sdk  for old systems. the old system must use .NET 4.5.

**Comment by mookid8000** [comment]
> Is there any problem if I lower the RabbitMQ.Net version to 3.6.9?

Yes, I don't think it will work. Also, I think NuGet will do everything it can to prevent you from doing that.

.NET 4.5 is no longer supported by Microsoft – it hasn't been since January 2016. I strongly encourage you to somehow upgrade to at least .NET 4.5.2, which is the oldest supported version (check out [this list](https://github.com/Microsoft/dotnet/blob/master/releases/README.md))

**Comment by xiaguoli** [comment]
Thanks again! 
Rebus is great! Continue!

**Comment by mookid8000** [comment]
Thanks! 🙂 and I will! 🤠

Sendt fra min iPhone

–
Mogens Heller Grabe
Torsmark 4
8700 Horsens
Danmark

+45 29367077
mookid8000@gmail.com
