### ISSUE TITLE
Get Queue name from a Handle method

### ISSUE THREAD

**Issue by tresoldigiorgio** [rebus-org/Rebus#833]
I've implemented a resend function for all messages that was redirected to a IHandleMessages<IFailed<Message>>. For messages that was sent using "Publish" method i also send with "Publish" but all messages sent with "Send" method i need to send with "Send" but i need to save the name of the queue that have received the message. How can i extract the queue name from context or ibus in Handle method?
Thanks
Giorgio

**Comment by mookid8000** [comment]
If you're receiving the failed message in a "2nd level error handler", i.e. a handler that implements `IHandleMessages<IFailed<YourMessage>>`, then the queue name is not readily available. But the handler must have been called by a bus instance that you started with some queue name, so you must have the queue name somewhere.

If you want to create some kind of generic error handling mechanism, I suggest you start a bus instance that consumes messages from the `error` queue – if you do that, then Rebus will have attached a `rbs2-source-queue` header to the failed message, containing the name of the queue where the message could not be consumed.

Regarding events: I don't know everything about your setup, but re-publishing an event sounds wrong to me, because it might not have failed with all consumers. If you build the aforementioned consumer on the `error` queue, then failures in all subscribers will also be handled by that.

I hope that made sense 😁 if not, please ask some more 🙂

**Comment by tresoldigiorgio** [comment]
You are right. Resend messages with publish method is dangerous. But...How can i consume error queue with a bus instance? I don't find any sample code to do that! I have to handle messages by type or i can handle all messages in one point and then decide what can i do? I have to use another app or i can use an existing app that have his bus instance registered in service provider (.net core)?

**Comment by mookid8000** [comment]
Try Bingleing a bit for Rebus transport message forwarder – you need one of those 🙂

Sendt fra min iPhone

–
Mogens Heller Grabe
Torsmark 4
8700 Horsens
Danmark

+45 29367077
mookid8000@gmail.com
