### ISSUE TITLE
[Question] What is that I am doing wrong here?

### ISSUE THREAD

**Issue by kuskmen** [rebus-org/Rebus#835]
We decided to give a try to Rebus in a small console application (will be windows service) that consumes AMQP messages from our third party. The half part is done since they provided us with an SDK that generally serializes that AMQP messages into domain entities. What we need and want to do is decouple processing of the messages and saving them into the database and we sort of chose Rebus for that. We do not want any other infrastructure in between (for now) hence we stopped on using in-memory option as network and transport with the neat ability to switch to RabbitMQ/Azure/MsMQ and so on whenever we really see the need, but enough with the talk.

I am trying to configure Rebus to do simple fire and forget command using in-memory predefined network and transport as well as using typed mapping. However, the latter turned out to be not so easy, but maybe I am doing something wrong, hence asking this question here.

this is how I configured my bus using Autofac

```
var network = new InMemNetwork();
network.CreateQueue(QueueName);       -- don't mind me, I am new to the project not sure if this is needed and I am using mainly your unit tests as examples (since no real example for in-memory transport) I hope this doesn't backfire

builder.RegisterHandlersFromAssemblyOf<OddsChangeEventHandler>();
builder.RegisterRebus((configurer, context) =>
       configurer
            .Logging(l => l.Log4Net())
            .Transport(t => t.UseInMemoryTransport(network, QueueName))
            .Routing(r => r.TypeBased()
                                    .Map<IOddsChange<ISportEvent>>(QueueName))
            );
```
This is how my declaration of my handler looks like

```
public class OddsChangeEventHandler : IHandleMessages<IOddsChange<ISportEvent>>
    {
        public Task Handle(IOddsChange<ISportEvent> message)
        {
            throw new NotImplementedException();
        }
    }
```
Then I send my message like so
```
await _bus.Send(oddsChange);
```

Also, I think it can be helpful to know how `IOddsChange<ISportEvent>>` is declared:

```
public interface IOddsChange<out T> : IMarketMessage<IMarketWithOdds, T>, IEventMessage<T>, IMessageV1, IMessage where T : ISportEvent
                              ^ notice the covariance
```

Okay so, here's the deal, whenever I try to send a message Rebus throws 

> System.ArgumentException: 'Cannot get destination for message of type Sportradar.OddsFeed.SDK.Entities.Internal.EntitiesImpl.OddsChange`1[Sportradar.OddsFeed.SDK.Entities.REST.IMatch] because it has not been mapped! 

> You need to ensure that all message types that you intend to bus.Send or bus.Subscribe to are mapped to an endpoint - it can be done by calling .Map<SomeMessage>(someEndpoint) or .MapAssemblyOf<SomeMessage>(someEndpoint) in the routing configuration.'

 There is a blunder tho, the message I try to send is of type `IOddsChange<IMatch>` (`IMatch` has following declaration `public interface IMatch : ICompetition, ISportEvent`) and now I am stuck trying to find out what can the problem be... Could it be a problem of the covariance and `RegisterHandlersFromAssemblyOf` extension? (I really doubt but still)

What I did so far:
1. If you are wondering if I did something wrong in between configuration and sending I simply changed handler to handle string messages, mapped the string to that endpoint and then sent simple dummy string and everything worked as expected.
2. I tried mapping both `IOddsChange<ISportEvent>` and `IOddsCange<IMatch>` to the same endpoint along with different handlers as well again with no success.
3. Created dummy msg type and dummy interface for it and it raised the same exception. Does typed routing works for abstract message types at all?

Now I am in dead-end, what should I try next or what I am doing wrong?

**Comment by kuskmen** [comment]
@mookid8000  mind if you give us a few words, so I know if we can continue trying or implement something on our own? :)

**Comment by mookid8000** [comment]
When Rebus throw with

> System.ArgumentException: 'Cannot get destination for message of type Sportradar.OddsFeed.SDK.Entities.Internal.EntitiesImpl.OddsChange`1[Sportradar.OddsFeed.SDK.Entities.REST.IMatch] because it has not been mapped!

it means that the router does not know which destination queue it should use. Since the router (by default) uses simple `Type messageType` => `string queueName` mappings, you would need to configure a mapping for each concrete type that you end up sending.

I suggest you either (a) explicitly specify the destination queue name, or (b) customize the router to work the way you want it.

Without know a lot about your problem, I would go for (a) in your case, because it seems you just want to offload work to a background process, so the destination queue name will always be the same.

You can achieve (a) by sending like this:
```csharp
await bus.Advanced.Routing.Send(queueName, message);
```

If you want to do (b), you must implement Rebus' [`IRouter`](https://github.com/rebus-org/Rebus/blob/master/Rebus/Routing/IRouter.cs) service, and then you will have pretty fine-grained control with which destination queue names are used when sending.

A custom router can then be installed like this:
```csharp
Configure.With(...)
	.(...)
	.Routing(r => r.Register(c => new MyCustomRouter()))
	.Start();
```
where I suggest you hide the `r.Register(c => new MyCustomRouter())` part in an extension method, so that your configuration code will read
```csharp
Configure.With(...)
	.(...)
	.Routing(r => r.UseMyCustomRouter())
	.Start();
```

I hope that makes sense 😄 

PS: Sorry for being so slow to reply – I've been buried in work for a while now, so even though I noticed your question a couple of days ago, I never got around to answer it.

**Comment by labeled** [comment]
We are also running into this same issue, which is difficult to handle correctly

We have this contract
```
DomainEvent<T> where T : ICommand
```

And tried setting it up like this
```
.Map<DomainEvent<ICommand>>(settings.CommandBusQueue)
```

And get the same error you were seeing. 

We solved it by adding

```
.MapFallback(settings.CommandBusQueue)
```

But now the problem is we cannot setup a handler to handle anytime any event fails

```
public class ErrorHandler : IHandleMessages<IFailed<DomainEvent<ICommand>>>
```

The only way we've gotten it to work is by using object
```
public class ErrorHandler : IHandleMessages<IFailed<DomainEvent<object>>>
```
