### ISSUE TITLE
Customize Message routing key

### ISSUE THREAD

**Issue by dekim** [rebus-org/Rebus#863]
We are currently using Rebus along with Rebus.RabbitMQ.

Currently, routing_key in RabbitMQ is the message's qualified name (ex: Assembly.Namespace.Messages.MyEvent). Is there any way to change that using Rebus? (ideally an attribute on the POCO message class itself).

We have this requirement as our .NET Core 3.1 worker listens to a routing_key generated by a Python app.

Thanks :)

**Comment by mookid8000** [comment]
There's a chance that you can simply
```csharp
await bus.Advanced.Topics.Subscribe("your_topic");
```
because this will bind the `your_topic` topic from the `RebusTopics` exchange to the bus' input queue.

If you do want to control how type names are mapped to topic names, Rebus has the [`ITopicNameConvention`](https://github.com/rebus-org/Rebus/blob/master/Rebus/Topic/ITopicNameConvention.cs) interface, which you can implement and then have Rebus use it like this:
```csharp
Configure.With(...)
	.(...)
	.Options(o => o.Register<ITopicNameConvention>(c => new CustomTopicNameConvention()))
	.Start();
``` 
possibly wrapper the `o.Register(...)` stuff in an extension method of `OptionsConfigurer`, making it look pretty like this:
```csharp
Configure.With(...)
	.(...)
	.Options(o => o.UseCustomTopicNameConvention()))
	.Start();
```

Let me know if it works 🙂

**Comment by dekim** [comment]
Thanks a lot :) It works :)

We used an Attribute to decorate the Message to be able to extract a routing_key for RabbitMQ.

One last question : (please tell me if you prefer that I open another issue)

Our team is having trouble matching Rebus's terms with RabbitMQ's terms.

**Scenario**

Here's a concrete example of our requirements

- Service 1 emits an event called `lunch.ready` in an exchange called `restaurant-operation`
- Service 2 must created a queue called `restaurant.notification.email` in an exchange called `restaurant-operation` to send an email to the manager on every order
- Service 3 must created a queue called `restaurant.notification.ios` in an exchange called `restaurant-operation` to send a notification to the waiter that he must pickup the order
- Service 4 must created a queue called `restaurant.export.ais` in an exchange called `restaurant-operation` to write a transaction row in the restaurant's AIS (ex Quickbook Online)

**Classes**

- `LunchReadyIntegrationEvent`, attributed with `[MessageName("lunch.ready")]`
- Service 1 is a .NET Core API
- Service 2, 3, 4 is a .NET Core Worker

**Questions**

_1 - What's the proper way of creating a **Publisher** in this case «Service 1» to emit a LunchReady_

In the following code, if we do not add Routing in Rebus Config, it throws an Exception

```
services.AddRebus(configure => configure
                .Logging(l => l.Serilog())
                .Options(o => o.Register<ITopicNameConvention>(c => new AttributeTopicNameConvention()))
                .Transport(t => t
                    .UseRabbitMqAsOneWayClient(connectionString)
                    .ExchangeNames(EventBusConstants.PublisherExchangeName)
                )
                .Routing(r => r.TypeBased().MapAssemblyOf<LunchReadyIntegrationEvent>("routing-destination"))
            );
```

_2 - What's the proper way of creating a **Subscriber** in this case «Service 2,3,4» to handle a LunchReady in their own queue_

Looking back at question number 1, we should use `restaurant.notification.email` as topic name, over  `routing-destination`, right?

**Comment by dekim** [comment]
Thanks a lot :) It works :)

We used an Attribute to decorate the Message to be able to extract a routing_key for RabbitMQ.

One last question.

- Service 1  publish the event
- Service 2 throw an exception because it cannot find the exact class name (it try to instanciate the FullName from Service), because in Service 2, the class does not have have the same name.

```
 1 unhandled exceptions (Message with ID 0456d648-d844-47e7-b45b-23b22ff032af and type A.B.C.Context.IntegrationEvents.FormSignedIntegrationEvent, A.B.C could not be dispatched to any handlers (and will not be retried under the default fail-fast settings)) ---> Rebus.Exceptions.MessageCouldNotBeDispatchedToAnyHandlersException: Message with ID 0456d648-d844-47e7-b45b-23b22ff032af and type A.B.C.IntegrationEvents.FormSignedIntegrationEvent, A.B.C could not be dispatched to any handlers 
```

We tried disabling the JsonType from Newton 

```
.Serialization(s => s.UseNewtonsoftJson(new JsonSerializerSettings
                {
                    TypeNameHandling = TypeNameHandling.None
                }))
```

How can we disable this behavior, to strictly rely on our `AttributeTopicNameConvention` ?

**Comment by dekim** [comment]
Update - looks like message use a header `rbs2-msg-type` which contain the Assembly Name.

Can we disable this validation?

**Comment by mookid8000** [comment]
There's two things at play here: 1) message routing (i.e. how does a message end up in a Rebus instance's input queue), and 2) message handling (i.e. what to do with the message when it is received).

It sounds to me like you got the routing part working. You can completely bypass Rebus' type-based topics by subscribing to a topic like this:
```csharp
var topics = bus.Advanced.Topics;

await topics.Subscribe("this_is_the_topic");
```
and then that particular subscriber will receive ANYTHING published to `this_is_the_topic`:
```csharp
var topics = bus.Advanced.Topics;

await topics.Publish("this_is_the_topic", "this can be serializable object");
```

Now, when Rebus receives a message, the default serializer needs to know which type to try to deserialize the received payload into – that's why it insists on looking up a .NET type from the `rbs2-msg-type` header. There's no way to ignore this header, as that would make it impossible for Rebus to decide which .NET type to use.

For this reason, Rebus 6.1.0 has the built-in ability to completely customize the type name used when serializing messages, thus requiring the types to be known up-front. It can be enabled by doing something like this (combined with interoperable JSON serialization mode):
```csharp
Configure.With(...)
	.(...)
	.Serialization(s => {
		s.UseNewtonsoftJson(JsonInteroperabilityMode.PureJson);
		s.UseCustomMessageTypeNames()
			.AddWithShortName<SomeMessage>()
			.AddWithShortName<AnotherMessage()

			.AddWithShortNames(new [] { typeof(ThirdMessage), typeof(FourthMessage) })

			.AddWithCustomName<FifthMessage>("🙂");
	})
	.Start();
```

**Comment by dekim** [comment]
Thanks @mookid8000.

I will try that out as soon as possible in the days and come back to you :)

**Comment by dekim** [comment]
Thanks a lot @mookid8000.

I've tried your code, and made some progress :)

**Publisher**

- It creates the RabbitMQ exchanges as intended
- It serializes and publishes my message as intended, with the right topic name

**Subscriber**

It creates the correct binding with the topic name,  as I subscribed 

```
services.AutoRegisterHandlersFromAssemblyOf<SubscriberLunchReadyHandler>();

app.ApplicationServices.UseRebus(async r =>
            {
                await r.Subscribe<SubscriberMessageLunchReady>();
            });
```

However, when a message is received, I still had the type error ` Cannot get type corresponding to the name 'Publisher.Message.LunchReady, Publisher.Message'` I've used`.AddWithCustomName<SubscriberMessageLunchReady>("🙂");`. I tried to change the Smile to `lunch.ready` which is my routing_key, did not work.

It seems,  `🙂` must equal to the Type name from the Publisher right? That's the only way I got it to work. Would it be possible to map the MessageType to the RabbitMQ routing_key? I tried to get it from `TransportMessage` without any success. If I could, that could let me deserialize in the proper type.

Is this something possible with Rebus?

**Comment by mookid8000** [comment]
Did you call
```csharp
s.UseCustomMessageTypeNames()
    .AddWithCustomName<SubscriberMessageLunchReady>("lunch.ready");
```
on both the publisher and the subscriber?

They need to agree on what to call the types for this to work. 🙂

**Comment by dekim** [comment]
Awesome, it works :) Forgot this important part!

One last question, does Rebus play nice with multiple exchanges in RabbitMQ?

Example:

Service A should be able to send message to exchange `restaurant.lunchs` and `restaurant.audit`
Service B will bind to message in `restaurant.lunchs`
Service C will bind to messages in `restaurant.audit`

If so, is there any wiki article?

Thanks!

**Comment by mookid8000** [comment]
> does Rebus play nice with multiple exchanges in RabbitMQ?

It does, to some degree. It's been a long time since I used the RabbitMQ transport myself, so my memory might be a little off here... but I seem to recall functionality that allows for explicitly specifying the exchange to publish to by using a `topic@exchange` syntax, e.g.
```csharp
var evt = new LunchReady("woohoo! 🕺");

await bus.Advanced.Topics.Publish("lunch.ready@restaurant.lunchs", evt);
```

When configuring Rebus with RabbitMQ, you can specify which exchanges are default for direct messaging (i.e. sending to specific queues – should be one specific exchange in your case) and multicast messages (i.e. pub/sub, basically namespaces for topics).

It's done with the `ExchangeNames` method on the builder returned from `UseRabbitMq`, so in your case it could look somewhat like this:

IIRC it's done like this:
```csharp
Configure.With(...)
	.Transport(t => t.UseRabbitMq(...)
		.ExchangeNames(topicExchangeName: "restaurant.lunchs"))
	.Start();
```

I hope that brings you a step closer to the perfect solution. 🙂

**Comment by dekim** [comment]
Thanks @mookid8000  :)

I've got all these point perfectly now. The only thing remaining is that i need to support 2+ exchanges. Can Rebus do that? Looking at `.UseRabbitMq(...).ExchangeNames(topicExchangeName: "restaurant.lunchs"))` it does not seems like?

I need to be able to send a message in both `restaurant.lunchs` and `restaurant.audit` (both two different types, so I need to route them to the proper exchange).

**Comment by mookid8000** [comment]
When you do this `.UseRabbitMq(...).ExchangeNames(topicExchangeName: "restaurant.lunchs"))` thing, it's just configuring the default exchange to be `restaurant.lunchs`.

Any bus instance can
```csharp
await bus.Advanced.Topics.Publish("topic-name@exchange-name", myEvent);
```
and have `myEvent` published to the `topic-name` topic via the `exchange-name` exchange. When you specify the exchange name as part of the topic, it's like a globally addressable form of the topic, and therefore it doesn't matter which exchange was configured to be the default.

**Comment by dekim** [comment]
Awesome, thanks! @mookid8000  :)

As last question, can we subscribe to two different topic in two exchanges?

I tried subscribing to `"topic-name@exchange-name"` but that just created a binding with `"topic-name@exchange-name"` as routing-key

**Comment by mookid8000** [comment]
> (..) can we subscribe to two different topic in two exchanges?

Looks like that is not possible with the way it works now. But it definitely _would_ be nice and consistent with how topics are treated in other places if it was possible.

**Comment by dekim** [comment]
That would be awesome, is it on your roadmap?

**Comment by mookid8000** [comment]
Created an issue for the feature here: https://github.com/rebus-org/Rebus.RabbitMq/issues/65
