### ISSUE TITLE
redis transport

### ISSUE THREAD

**Issue by hiwjcn** [rebus-org/Rebus#874]
any plan to provide redis transport?

**Comment by mookid8000** [comment]
Not offhand, no. Is it something you would be interested in?

And if so: Why would you use Redis as a queue instead of other queueing systems?

**Comment by hiwjcn** [comment]
maybe redis performs much better than relational database like mysql sqlserver.

queue system is good,but in small project queue system is't always available,right?

**Comment by mookid8000** [comment]
Sure 🙂 do you have any experience with using Redis as message queues yourself?

**Comment by hiwjcn** [comment]
yes im currently using redis to queue message when rabbitmq is not available.
just use lpush and rpop api to implement that.

but still lots of work to be done to provide a rebus transport provider.

**Comment by hiwjcn** [comment]
i know nothing about the rebus internal api.
im still in the stage helloworld

**Comment by mookid8000** [comment]
To Rebus, a transport is something that implements [`ITransport`](https://github.com/rebus-org/Rebus/blob/master/Rebus/Transport/ITransport.cs) , so it's not a big interface to satisfy.

There's a few caveats around how transactions are handled though, but Rebus has a fairly comprehensive suite of contract tests that can be leveraged to help implement the correct behavior.

If you're interested in contributing a Redis transport, I'd be happy to guide you 🙂

**Comment by mookid8000** [comment]
Hi @hiwjcn , let me know if this is something we should look at 🙂

**Comment by jonmat** [comment]
Blending ideas here, what about working Rebus into this redis and k8s stack? 

https://kubernetes.io/docs/tasks/job/fine-parallel-processing-work-queue/

thoughts?

**Comment by zejji** [comment]
I would definitely be interested in Rebus using Redis (and/or [Redis Streams](https://stackoverflow.com/questions/63206036/is-there-a-way-to-subscribe-to-redis-streams-similar-to-redis-pub-sub#63209734)) as a transport. Like @hiwjcn, I don't have a dedicated message bus available, but I'm currently using PostgreSQL as the database and Redis as a cache, so it would extremely convenient to be able to make use of the latter.

I note that there is an implementation on GitHub [here](https://github.com/tozevv/Rebus.Transports.Redis), but it's been 6 years since it was modified and I don't know what the quality of implementation is like.
