### ISSUE TITLE
Rebus not throw an exception if try to Defer a message without having configured a timeout manager if transport SQL Server

### ISSUE THREAD

**Issue by evgenykorobets** [rebus-org/Rebus#875]
Rebus **not** throw an exception if try to Defer a message without having configured a timeout manager if transport SQL Server.
It's correct?
Nothing is written about this in the documentation.
Rebus version:  5.4.0

**Comment by mookid8000** [comment]
This is because the SQL Server transport does not require a timeout manager to work 🙂 it has got a built-in ability to defer messages into the future.

It works by setting a `datetimeoffset` in the `[visible]` column, thereby setting the time of when each message should become visible to consumers.

**Comment by rickberkers** [comment]
What if I want to use this built in functionality using `Publish()` and passing the `rbs2-deferred-until` header along. I'm getting the exception that i should also pass `rbs2-defer-recipient`. 
So i'm passing a random string for `rbs2-defer-recipient` and it goes into my queue with the correct `visibile` value, exactly how I want it.
Is this acceptable or is there a proper way to achieve this?

Rebus 6.3.1

**Comment by mookid8000** [comment]
Rebus does not really provide a way to publish deferred events. In your case, you've found a way to circumvent that limitation, which seems to work as the SQL Server transport does not use the `rbs2-defer-recipient` header for anything.

The `rbs2-defer-recipient` header is relevant when you're using a specific Rebus instance as an [external timeout manager](https://github.com/rebus-org/Rebus/wiki/Timeout-Manager#external-timeout-manager), because the timeout manager will then use the header to determine which queue to deliver the message to when it is due. 

I cannot say that it's working as intended for you – I would rather say something like "you're lucky that it works for you" or something like that 😅 and you should probably ensure that the behavior of your desired functionality is verified with a couple of integration tests, so you will know it if your loophole works differently some time in the future.

Also, you cannot expect this to work with other transports, so your code will not be portable.

If you are interested in an alternative solution, I can recommend a two-step process where you

```csharp
await bus.DeferLocal(delay, theEvent);
```

and then, when the local handler receives `theEvent` it'll simply

```csharp
await bus.Publish(theEvent);
```
