### ISSUE TITLE
.net Core Pub/Sub unexpected behavior 

### ISSUE THREAD

**Issue by Ghyath-Serhal** [rebus-org/Rebus#885]
I am using the pub/sub in a .net core project.

I have the below code in the subscriber.
```
 using (var activator = new BuiltinHandlerActivator())
            {
                activator.Register(() => new PersonHandler());

                Configure.With(activator)
                    .Logging(l => l.ColoredConsole(LogLevel.Warn))
                    .Transport(t => t.UseSqlServer(new SqlServerTransportOptions("connection string", false), "subscriber1"))
                    .Routing(r => r.TypeBased().MapAssemblyOf<Person>("publisher"))
                    .Start();

                activator.Bus.Subscribe<Person>().Wait();

                Console.WriteLine("Consumer for person is listening - press ENTER to quit");
                Console.ReadLine();
            }
```
And the below code in the publisher 
```
using (var handler = new BuiltinHandlerActivator())
            {
                Configure.With(handler)
                    .Logging(l => l.ColoredConsole(minLevel: LogLevel.Warn))
                    .Transport(t => t.UseSqlServer(new SqlServerTransportOptions("connectionstring", false), "publisher"))
                    .Subscriptions(s => s.UseJsonFile(JsonFilePath))
                    .Start();

    handler.Bus.Publish(new Person { Name = "test" }).Wait();
}
```

If I run the publisher, the following error appear
**Unhandled exception. System.AggregateException: One or more errors occurred. (Unable to send to destination [dbo].[person])**

I do not know why it is looking for the table person, and it is not created automatically. The tables, publisher and subsciber1 are automatically created.
When the table person is created, everything works fine.

**Comment by mookid8000** [comment]
You also posted the question [here](https://stackoverflow.com/questions/62275680/rebus-pub-sub-using-sql-server-in-net-core).

**Comment by mookid8000** [comment]
I just tried to reproduce your problem, but it seems you've mixed some things around somehow.

When I use the code, exactly as you've posted it, I get this in the subscriber:
![image](https://user-images.githubusercontent.com/32968/84128315-b6386700-aa40-11ea-9053-26e24be7549b.png)
which indicates that it has correctly sent a `SubscribeRequest` to the publisher.

Inspecting the publisher's subscription storage JSON file, I have the following contents:
```json
{
  "Messages.Person, Messages": [
    "[dbo].[subscriber1]"
  ]
}
```
(because I put the `Person` message type in an assembly called `Messages`).

If you still have a problem, please don't hesitate to get back to me here. 🙂
