### ISSUE TITLE
"RebusApplicationException:  Cannot add OnCommitted action on a completed transaction context" when publishing many events

### ISSUE THREAD

**Issue by mindisk** [rebus-org/Rebus#895]
I was faced with a issue that is difficult to handle on my own. 

I have a service that need to publish user activity.  I run a timer where we collect user activity every minute and call based on user activity we might call `_bus.Publish(new Activity("some activity")).Wait()` multiple times in quick succession from separate tasks.  As a result, some messages would go through and would end up in RabbitMQ. Some messages would not (they just disappear within Rebus). On a rare occasion we would catch a Rebus exception. 
```
Rebus.Exceptions.RebusApplicationException: Could not 'GetOrAdd' item with key 'rabbitmq-outgoing-messages' as type 
System.Collections.Concurrent.ConcurrentQueue`1[Rebus.RabbitMq.RabbitMqTransport+OutgoingMessage][nl] ---> 
System.InvalidOperationException: Cannot add OnCommitted action on a completed transaction context.[nl]  
```
_It is important to note, that it none of the code is running within the Rebus handler. The timer is started in a constructor and fired every minute or so._

I assumed that because there are **multiple threads calling publish for the same message type in quick succession**, Rebus tries to get a context that represents that message type and as a result it finds a transaction that is already completed. 

One of the solutions I had is to put all these `Activity` messages in a queue and delegate message publishing to a single thread.
Even though,  I do not see the exception some messages still do not go though Rebus into RabbitMQ.  This publisher thread still calls `_bus.Publish(new Activity("some activity")).Wait()` in quick succession if multiple activities exist. 

Is my assumption correct that calling `Publish` for the same message type in quick succession can mess up with Rebus transaction when publishing?

What would be the correct solution? Perhaps adding a delay before each `Publish` so that Rebus can properly conclude the transaction?

My other solution would be to manually maintain the transaction lifetime. Do you think solution is a correct one? 

```
using var transaction = new RebusTransactionScope();
try
{
     while (_messagesQueue.TryDequeue(out Activity? message))
     {
          try
          {
               _bus.Publish(message).Wait();
          }
          catch (Exception ex)
          {
               // Log error
          }
     }    
}
finally
{
     transaction.Complete();
}
```

**Comment by mookid8000** [comment]
> I assumed that because there are multiple threads calling publish for the same message type in quick succession, Rebus tries to get a context that represents that message type and as a result it finds a transaction that is already completed.

That is not really how it works. When Rebus is to send an outgoing message (regardless of whether you _send_ or _publish_ it), it will look at `AmbientTransactionContext.Current` to see if there is an active transaction context, which will be the case if a) you're in a Rebus handler, or b) you've created one manually using `RebusTransactionScope`.

If there isn't any ambient transaction context present, it will create one temporarily (i.e. without making it "ambient") and use that for that single operation. 

You can see the logic described [here](https://github.com/rebus-org/Rebus/blob/master/Rebus/Bus/RebusBus.cs#L404-L420).

> Is my assumption correct that calling Publish for the same message type in quick succession can mess up with Rebus transaction when publishing?

Absolutely not, no! 😅

---

OK, first off I would need to know a little bit more about exactly what you're doing to be able to diagnose your problem. It's pretty clear to me that something around the transaction scope lifetime is not being handled properly... e.g. one way I've seen this type of error surface before, was when someone did something like this

```csharp
using (var scope = new RebusTransactionScope())
{
	bus.Publish(someKindOfEvent); //< 💀⚠NO!

	scope.Complete();
}
```
which to the untrained eye might look fine, but it's NOT, because `Publish` above returns a `Task` that must be awaited... and so, this code contains a race condition between whatever goes on in side the `Publish` function and the completion of the transaction scope.

The correct way to do this, would be to take advantage of the fact that Rebus has a "synchronous bus" and do it like this:
```csharp
var syncBus = bus.Advanced.SyncBus;

using (var scope = new RebusTransactionScope())
{
	syncBus.Publish(someKindOfEvent);

	scope.Complete();
}
```

Regarding the posted code snippet, you should not complete the scope in the `finally` block, because that would be executed even if the publish operations failed, and so it might throw a weird exception OUTSIDE of any `try-catch` construct.

Also (although this might be more of a personal preference), I don't think it's so nice to have dequeueing logic and bus sending logic mingled together like that... I would suggest you change your code into something like this:
```csharp
const int batchSize = 10;

// local method could also be ordinary member method
List<Activity> DequeueNext(int count) {
     var results = new List<Activity>(count);

     // order of arguments is important here! 💀
     while (results.Count < count && _messagesQueue.TryDequeue(out var result)) {
          results.Add(result);
     }

     return results;
}

var activities = DequeueNext(count: batchSize);

if (!activities.Any()) return;

var syncBus = _bus.Advanced.SyncBus;

try
{
     using var scope = new RebusTransactionScope();

     foreach(var activity in activities)
     {
        syncBus.Publish(message);
     }

     scope.Complete();
}
catch(Exception exception)
{
     // log it or whatever... re-enqueue the activities, maybe?
}
```

**Comment by mindisk** [comment]
Thank you for a quick response.

I would like to try to use it the `ISyncBus` to make sure that the messages are indeed delivered. 
However, if I would wrap the publish of the event as such, will it be  able to handle calls from multiple threads? Won't the transaction scopes overlap within the Rebus if `syncBus.Publish(someKindOfEvent)` is called by multiple threads at the same time?
```
public void PublishEvent(SomeEvent someKindOfEvent)
{
     var syncBus = bus.Advanced.SyncBus;
     using (var scope = new RebusTransactionScope())
     {
         syncBus.Publish(someKindOfEvent);
          scope.Complete();
     }
}
```

Perhaps `ISyncBus` should only be managed by one thread at any point in time?

**Comment by mookid8000** [comment]
> However, if I would wrap the publish of the event as such, will it be able to handle calls from multiple threads?

Yes. All methods in the bus are fully re-entrant.

> Won't the transaction scopes overlap within the Rebus if syncBus.Publish(someKindOfEvent) is called by multiple threads at the same time?

No. The scopes are bound to the calling thread's execution context via `AsyncLocal<>`, and so it flows as an "ambient context" to everything asynchronous that the call gives rise to. But there's absolutely no overlap with other threads. 🙂

**Comment by mindisk** [comment]
Sounds cool. I will try to use it and I will post here if I will encounter the issue again.
Thanks.

**Comment by mindisk** [comment]
From what is seems, the `ISyncBus` does the trick. So far all events are being published with no issue. 
Thanks for the support.
