### ISSUE TITLE
NumberOfWorkers, MaxParallelism and RabbitMq Prefetch

### ISSUE THREAD

**Issue by tresoldigiorgio** [rebus-org/Rebus#900]
I've wrote this app
```
public class Program
    {
        static async Task Main(string[] args)
        {
            var services = new ServiceCollection();
            services.AutoRegisterHandlersFromAssemblyOf<Program>();
            
            services.AddRebus(configure => configure
                .Logging(l => l.ColoredConsole())
                .Routing(r => r.TypeBased())
                .Options(c => {
                    c.SetNumberOfWorkers(1);
                    c.SetMaxParallelism(2);
                })
                .Transport(t => t.UseRabbitMq("amqp://guest:guest@localhost:5672", "Messages")
                        .Prefetch(2)
                )
            );

            await using var provider = services.BuildServiceProvider();
            provider.UseRebus(async busAction =>
            {
                await busAction.Subscribe<Message1>();
                await busAction.Subscribe<Message2>();
            });

            var bus = provider.GetRequiredService<IBus>();
            await bus.Publish(new Message1());
            await bus.Publish(new Message2());
            Console.ReadLine();
        }

        public class Message1 { }

        public class Message2 { }

        public class Handler : IHandleMessages<Message1>, IHandleMessages<Message2>
        {
            public async Task Handle(Message1 message)
            {
                Console.WriteLine("Message1 START!");
                await Task.Delay(3000);
                Console.WriteLine("Message1 END!");
            }

            public Task Handle(Message2 message)
            {
                Console.WriteLine("Message2 END!");
                return Task.CompletedTask;
            }
        }
```
I don't understand why, with the configuration SetNumberOfWorkers set to 1, SetMaxParallelism set to 2 and RabbitMq Prefetch set to 2, the Hande of Message2 wait Handle of Message1 before starting. the "await" in Handle<Message1>  should release the worker for Handle<Message2>. 
With InMemory transport works well. 
I think that the MaxParallelism setting and Prefetch setting are in conflict, only with Prefetch set to 1 the MaxParallelism are considered.
How can i use few worker with high parallelism and a prefetch value higher than 1 with a "real" async/await?
Thanks,
Giorgio

**Comment by mookid8000** [comment]
I'm afraid this is a consequence of a limitation in the RabbitMQ driver's way of handling connections: The `IModel` (which represents a stateful connection with the server) is not thread safe, and so Rebus ensures that it is not used concurrently.

Rebus also ensures that the `IModel` associated with the RabbitMQ consumer receiving a message is used throughout the handling of that message.

To implement this, Rebus uses a "pool" of consumers, thus allocating a consumer instance to each logically separate thread of execution. But the RabbitMQ driver also happens to prefetch messages inside the consumer instance, so in this case there will only ever be 1 single consumer instance, which has prefetched both messages.

That was hard to explain... I'm not even sure it makes sense. I'm also all ears if Rebus' RabbitMQ transport could be designed better, because honestly I think it has become too complicated.
