### ISSUE TITLE
(New?) Rebus error queue functionality

### ISSUE THREAD

**Issue by KasperDamgaard** [rebus-org/Rebus#901]
Hey Mogens

This might be either a question or a new functionality request.
It all revolves around error messages.

We would like to provide information about the messages which end up on the error queue. These we can just fish out from the database, but is there a way to do so via Rebus instead of raw SQL?
we would also like to permanently delete error messages. Again, can be done via simple SQL, but is there way to do so in the Rebus API?
Finally we would like to give the option of rerunning a failed message, should the end user want to do so. Is this an existing feature? This one is not just simple SQL, but could be done a naïve way by getting the error message from the DB, then serialize it back to the original message, and resend it that way. 

I have not been able to find the answers, but maybe my google-foo is terrible. If so, I humbly ask to be pointed in the right direction :)

**Comment by mookid8000** [comment]
> We would like to provide information about the messages which end up on the error queue. These we can just fish out from the database, but is there a way to do so via Rebus instead of raw SQL?

When Rebus forwards a message to the dead-letter queue, it's doing it with its [`IErrorHandler`](https://github.com/rebus-org/Rebus/blob/master/Rebus/Retry/IErrorHandler.cs). By default, it's using [`PoisonQueueErrorHandler`](https://github.com/rebus-org/Rebus/blob/master/Rebus/Retry/PoisonQueues/PoisonQueueErrorHandler.cs), which is fairly straightforward.

If you want to e.g. add extra headers to the failed message, one way of doing so would be to decorate `IErrorHandler` and e.g. enrich with data from your database:
```csharp
Configure.With(...)
	.(...)
	.Options(o => {
		o.Decorate<IErrorHandler>(c => {
			var errorHandler = c.Get<IErrorHandler>();
			return new MyErrorHandlerDecorator(errorHandler);
		});
	})
	.Start();
```
Would that work for you?

> we would also like to permanently delete error messages. Again, can be done via simple SQL, but is there way to do so in the Rebus API?

Unfortunately, Rebus cannot help you do that.

> Finally we would like to give the option of rerunning a failed message, should the end user want to do so. Is this an existing feature? This one is not just simple SQL, but could be done a naïve way by getting the error message from the DB, then serialize it back to the original message, and resend it that way.

Again, Rebus cannot really help you do that. Since you're using SQL as the transport, it should be pretty easy to move the message from the dead-letter queue back to its source queue with some SQL scripting.

An alternative solution, which requires a little bit of 💸 though, is to become a [Rebus Pro](https://rebus.fm/rebus-pro/) subscriber – then you can use Fleet Manager

**Comment by KasperDamgaard** [comment]
As always a pleasure to work in software with support answering times of less than 24 hours :)
It did indeed answer my questions. We will ponder on this. 

Thanks a lot!
/Kasper
