### ISSUE TITLE
Exceeding maxDeliveryAttempts with Azure Bus

### ISSUE THREAD

**Issue by marmagni** [rebus-org/Rebus#913]
I'm testing the Rebus using Azure Service Bus with below options configuration:

```
c.SetNumberOfWorkers(2);
c.SetMaxParallelism(15);

c.SimpleRetryStrategy(
   maxDeliveryAttempts: 3,
   errorQueueAddress: "queue.error");
```

Setting max attemps to 3, I've observed retry is exceeding the configured limit of 3 attemps, looks like no limit.

![image](https://user-images.githubusercontent.com/13425338/100741228-adee3280-33b8-11eb-9a6b-c448efd4eaef.png)

And then, when the 100's limit is exceeded, the message is moved to Azure Bus Dead Leatter:

deadlettererrordescription: "Message could not be consumed after 100 delivery attempts."
deadletterreason: "MaxDeliveryCountExceeded"

What's wrong?

**Edit**: I've found an issue when the handle execution exceeds the limit of 5 minutes, when this happens the retry no respect the configured limit. I observed that execution isn't canceled when limit of 5 min is reached too.

Is It a bug?

**Comment by mookid8000** [comment]
> I've found an issue when the handle execution exceeds the limit of 5 minutes, when this happens the retry no respect the configured limit. I observed that execution isn't canceled when limit of 5 min is reached too.
> Is It a bug?

When your message processing takes longer than Azure Service Bus' maximum lease timeout of 5 minutes, you need to enable automatic peek lock renewal:
```csharp
Configure.With(...)
    .Transport(t => t.UseAzureServiceBus(connectionString, "queue")
                     .AutomaticallyRenewPeekLock())
    .(...)
```

Otherwise, the received message will become visible again in the queue for another consumer (or just another logical thread of execution in the same process) to receive and start processing.


You can read more here: https://github.com/rebus-org/Rebus/wiki/Azure-Service-Bus-transport#long-running-message-handlers

This is probably (if not the reason, then at least contributing to) your problem 🙂 

Let me know if it doesn't work 🙂
