### ISSUE TITLE
Replace of Newtonsoft.Json to System.Text.Json

### ISSUE THREAD

**Issue by danilobreda** [rebus-org/Rebus#919]
![image](https://user-images.githubusercontent.com/14843499/101497755-12c20380-394a-11eb-8c78-86ff4883d3ec.png)
All the packages I use have no reference to the newtonsoft nuget, only Rebus has this reference, allowing me to use the newtonsoft jsonserializer in other parts of the system that i dont want.
On the final build (publish) the newtonsoft is present too.

**Comment by mookid8000** [comment]
I think I understand where you are coming from, but there's a couple of reasons why Rebus is referencing Newtonsoft JSON.NET.

First off, Rebus is built for a bunch of targets, where .NET 4.5 is the oldest. System.Text.Json is not available anywhere besides .NET Core 3/3.1 and .NET 5.

Next, .NET's built-in JSON serializer is crippled, because it's unable to roundtrip immutable objects. E.g. the class
```csharp
public class MyMessage
{
    public MyMessage(string text) => Text = text;
    public string Text { get; }
}
```
is trivially serializable/deserializable by Newtonsoft JSON.NET, because it happily matches property getters (`get_Text`) with constructor parameters (`text`), meaning that immutable DTOs can be had.

Not being able to roundtrip objects of classes with get-only properties makes System.Text.Json a no-go for serializing messages, because you usually want to be able to model those to be immutable.(*)

Last, it would be a big breaking change to lose the Newtonsoft JSON.NET dependency. Rebus has used Newtonsoft since 2011, long before Microsoft learned that there was something called JSON. It's used for a couple of things internally, e.g. to serialize headers if you're using MSMQ (which doesn't support enclosing proper headers with messages), serialize saga data if you're using Rebus' SQL Server saga persister, etc etc. Some of these uses rely on being able to roundtrip rich objects with type information (i.e. via JSON.NET's `$type` field), and so it would most likely change the capabilities and the behavior a lot if it was changed.

So... while I would love being able to provide a Rebus core packages with no dependencies besides .NET 5, I don't think it's going to happen anytime soon. Later, when .NET 5 is more prevalent, we could consider it.

--
(*) Don't know if it's more capable in .NET 5 though 🙄

**Comment by danilobreda** [comment]
Thanks for your quick reply.
I understand the problem of breaking, especially from previous versions of .NET. I'm migrating multiple APIS and I'm having a lot of problems, but I'm getting somewhere.
I believe you are correct that it can break a lot of things :( ...in the future it may be possible to change the library.

Maybe leave newtonsoft and in .NET 5 just the system.text.json?
This would be nice for the library, for the performance and to be aligned with the new .NET and future.

[Immutable object are now possibles :D](https://docs.microsoft.com/pt-br/dotnet/standard/serialization/system-text-json-how-to?pivots=dotnet-5-0#deserialization-behavior)
