### ISSUE TITLE
[Question] [Feature] Are there any mechanisms to peek at a queue?

### ISSUE THREAD

**Issue by jfalameda** [rebus-org/Rebus#921]
Hi,

I am planning to use a queue as a way to schedule future notifications. My idea is to add a message in the queue and have the instances of the queue peeking through the queue and extracting the messages that meet certain criteria.

I have been reading through the documentation (and it might be because you don't use the term peek). Is there any way to read through the queue and dequeue in a selective fashion with Rebus?

Kind Regards,
José.

**Comment by mookid8000** [comment]
The functionality you require is not really queue-like (“queue” being the FIFO thing implemented by RabbitMQ, Azure Service Bus, etc etc) – it sounds much more like a database with a job queue model, where you can peek and filter however you like. 

While some queueing systems MIGHT offer some kind of peek functionality, and possibly also some kind of filtering, I would be very afraid to go down that route, because I would fear that the queue would quickly turn out to be lacking in general data access methods, and so I would end up fighting the technology. 

I hope that made sense 🙂 let me know if you have further questions.
