### ISSUE TITLE
Is it possible to use Subscription Filters through Rebus?

### ISSUE THREAD

**Issue by Efp95** [rebus-org/Rebus#922]
Hi,

Just want to know if it's possible to Subscribe to messages which has a custom header only and ignore the other messages which don't have it

**Comment by mookid8000** [comment]
It's not possible with Rebus... mostly because this is a rather unusual feature, which (to my knowledge) is only possible with Azure Service Bus.

I think it might be possible though to set this up manually by using [`ManagementClient`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.management.managementclient) and then avoid using Rebus to subscribe.

If you try this, it would be fun if you'd report about your experience here 🙂
