### ISSUE TITLE
Implementation of the PubSub with publisher and multiple instances of the same Subscriber.

### ISSUE THREAD

**Issue by ddydeveloper** [rebus-org/Rebus#930]
Good morning! Thank's a lot for the really cool tool you have provided.

I have a question regarding the PubSub pattern implementation. I am going to have a UI push notification system based on SignalR hub which is a queue subscriber. Let's say I have a number of pods inside my k8s for hub services. So many UI clients can cannect a particular instance and should receive updates.

To emulate this behavior I've tried [this sample](https://github.com/rebus-org/RebusSamples/tree/master/PubSubNative) with the `UseRabbitMq` transport. I've started `Publisher` and 2 instances of `Subscriber1`. I expected each Subscriber should get a message but it seems it works like Worker Queues: any message processed exactly once in a round-robin manner.

Whether it is possible to distribute the same message across multiple instances of the same subscriber and if yes could you provide a sample?

**Comment by mookid8000** [comment]
> (...) [is it] possible to distribute the same message across multiple instances of the same subscriber? (...)

No. 🙂 At least not with Rebus. Rebus is built around the idea that messages are received in queues, and queues (in general) work in a way where messages get removed, when they're read.

As you've found out, starting multiple instances of the same subscriber that all receive messages from the same queue will actually have the effect that received events are distributed fairly evenly between the subscriber instances. This is called [competing consumers](https://www.enterpriseintegrationpatterns.com/patterns/messaging/CompetingConsumers.html), and it's a good thing, because that's how you can scale your messaging-based system to handle more work.

If you want a copy of the same event distributed to multiple subscribers at the same time, you can simply give each subscriber its own input queue. This way, when they
```csharp
await bus.Subscribe<SomeEvent>();
```
each subscriber will bind a topic named something like `Messages.SomeEvent, Messages` to its input queue and thus end up receiving a copy of it when it's published.

I hope that makes sense 🙂

**Comment by ddydeveloper** [comment]
Thank you for reply. I was confused because of the name `PubSub` cause it seems refer to [Pubish/Subscribe pattern](https://www.rabbitmq.com/tutorials/tutorial-three-dotnet.html) e.g. But I suppose Rebus is not exchange based but queue based so that's the reason why it works in the described way.

BTW I am not completely understand the following idea: 

>If you want a copy of the same event distributed to multiple subscribers at the same time, you can simply give each subscriber its own input queue.

If I need to specify own queue per each subscriber I can't just use replica sets. Because each instance of the same subscriber use exactly the same configuration so the same queue. Am I correct?

**Comment by mookid8000** [comment]
Rebus does indeed implement the publish subscriber pattern. The thing is, when you look at [the way the pub/sub pattern is visualizer](https://www.enterpriseintegrationpatterns.com/patterns/messaging/PublishSubscribeChannel.html), it looks like there's a way for one single queue to distribute multiple copies of the same message to multiple consumers.

That's not the case, though. That's not how most brokers work. That's also not how RabbitMQ works. With RabbitMQ, messages are delivered to an exchange, and then the exchange's type, together with the bindings on that exchange determine how copies of the message get distributed. 

It's true then, that RabbitMQ's [fanout exchange](https://www.rabbitmq.com/tutorials/amqp-concepts.html#exchanges) will leave a copy of the message in each queue bound to the exchange, but consumers will still compete for the messages if two consumer instances share a queue.

> If I need to specify own queue per each subscriber I can't just use replica sets. Because each instance of the same subscriber use exactly the same configuration so the same queue. Am I correct?

And yes, you would need to run your subscriber instances each with its own input queue. 

It's possible though to configure Rebus to use RabbitMQ's [auto-delete queues](https://www.rabbitmq.com/queues.html#temporary-queues) and then simply give the queue a random name (e.g. `Guid.NewGuid()` or something like that 🙂 ):
```csharp
Configure.With(activator)
    .Transport(t => t.UseRabbitMq(connectionString, Guid.NewGuid().ToString())
        .InputQueueOptions(o => o.SetAutoDelete(autoDelete: true)))
    .Start();
```
which would make it possible for you to start multiple instances of the same subscriber without even changing the configuration.

**Comment by ddydeveloper** [comment]
Fanout exchange is exaclty that I meant. Sorry for beeing unclear. Now I see the option. Thank you so much.

**Comment by mookid8000** [comment]
No problem 🙂 feel free to come back here if you have other questions.
