### ISSUE TITLE
Can we get response from the message we sent?

### ISSUE THREAD

**Issue by bahtiyarozdere** [rebus-org/Rebus#931]
Rebus seems very clean and elegant thanks for amazing product.
I am wondering if is it possible to send message and recieve a typed response before moving on.

**Comment by mookid8000** [comment]
There is an experimental plugin called [Rebus.Async](https://github.com/rebus-org/Rebus.Async), which can do something like that:
```csharp
var reply = await _bus.SendRequest<SomeReply>(new SomeRequest());

// we have the reply here :)
```
but I wouldn't really recommend that you use it 😄 the thing is, request/reply is a pretty tight kind of couple between a client and a sender, and the SYNCHRONOUS kind of request/reply (i.e. where the client waits for the reply and thus is stateful in a transient way by way of not being able to be resume if it would crash while waiting) is the most brittle and tightly coupled way of doing request/reply – it almost obviates all of the cool stuff that asynchronous, durable message otherwise enables.

With that said, feel free to have fun with [Rebus.Async](https://github.com/rebus-org/Rebus.Async) 🙂

**Comment by bahtiyarozdere** [comment]
Thank you :)
