### ISSUE TITLE
How to get an ISagaStorage instance?

### ISSUE THREAD

**Issue by fpnewton** [rebus-org/Rebus#932]
I'm using Rebus with Simple Injector container and SQL Server for saga persistence.

Is it possible to get an instance of ISagaStorage? I would like to be able to read stored saga data classes from an API controller so that I can report of the status of long running sagas.

**Comment by asleire** [comment]
There's no clean way that I know of, but I found this code snippet some time back

```
ISagaStorage? sagaStorage = null;

services.AddRebus(configure  => configure
      .Sagas(...)
      .Options(
          o =>
          {
              o.Decorate(c => sagaStorage = c.Get<ISagaStorage>()); // when rebus is initialized, sagaStorage variable will be initialized
          }
      )
);

services.AddSingleton(sp =>
{
    sp.GetRequiredService<IBus>(); // ensure Rebus is initialized
    return sagaStorage;
});
```
This is for Microsoft's `Microsoft.Extensions.DependencyInjection`, but I imagine the concept transfers to most containers

**Comment by mookid8000** [comment]
@fpnewton as @asleire says, there's no clean way of doing that, and so the code he showed would be the least amount of evil required to get to the `ISagaStorage` 😈 

Sorry, but `ISagaStorage` is really an internal interface of Rebus, and so it is not really meant to be consumed from the outside. It doesn't mean that it cannot be done, or event that it would cause you trouble, it just means that there's no good help (as you've discovered by now) from Rebus to let you get to it.

**Comment by asleire** [comment]
I must say I do find it curious that you consider `ISagaStorage` to be an internal interface. In every service where I (and my company) use Rebus Sagas (quite a few) we also use `ISagaStorage` to view the current state of the saga. What is your go-to method for inspecting the saga? I guess you could have the saga push state to another store, but that would seem like duplication of code/state

**Comment by mookid8000** [comment]
> I must say I do find it curious that you consider ISagaStorage to be an internal interface (...)

I can definitely understand why you feel that way 🙂 it's just that `ISagaStorage`'s capabilities are only there to satisfy Rebus' needs, and so 3 out of the 4 methods (IIRC) would probably not make any sense to use to anyone besides Rebus. 

> What is your go-to method for inspecting the saga?

Well, in the past where I've used the MongoDB saga persister, I would simply load the documents as BSON documents to look at them that way. I guess that could also be done with the SQL Server persister and a JSON-capable version of SQL Server.

**Comment by asleire** [comment]
Probably going off topic now, but ...

> and so 3 out of the 4 methods (IIRC) would probably not make any sense to use to anyone besides Rebus.

I would love to use these! At least I would love to do what they do. 

For instance, our sagas are often initiated by an user-initiated HTTP Request to an API. Currently we validate the request, send a bus message then return 200 OK. If something goes wrong (the message is never received, something fails in the handle method) the user is unaware and there's no saga to deal with. It would be awesome if we could synchronously initiate the saga before responding to the HTTP request. 

Sometimes, Sagas take too long and users want to give them a little bump. For instance I am currently working on a Saga that requires someone to set up a DNS record. We check periodically whether the DNS record is set up, but we don't do it constantly, after all it may take days before the person sets it up. So in the case that a person has set up the DNS, and wants the process to swiftly proceed, we have a button they can press to trigger a DNS check. Now, since sagas are completely asynchronous, the best we can do is basically respond "Thanks! We'll check it eventually, assuming nothing fails" while what we would want to do is do the actual check, update the saga and send the saga message for the next step. 

And of course, sometimes the customer changes their mind and doesn't want a custom DNS. Abort saga. Again the best we can do is send a message and tell the customer the process may or may not be cancelled.

I guess `Rebus.Async` could solve this for us? But that would require sending a bus message over a transport which seems odd for a synchronous operation. Is there any way to invoke the Rebus pipeline without going through a transport?

**Comment by fpnewton** [comment]
> Well, in the past where I've used the MongoDB saga persister, I would simply load the documents as BSON documents to look at them that way. I guess that could also be done with the SQL Server persister and a JSON-capable version of SQL Server.
That's a neat benefit of using MongoDB.

We're also using EF Core in our applications so in order to use what we already have setup, I would have to create models for the 2 DB tables, add them to the DbContext and edit the migrations to EF doesn't try to manage the schema on top of Rebus and I would then have to make changes if the schema that Rebus is using ever changes. This breaks having to only configure Rebus in one place and be able to just use it everywhere else.

The saga data column is of type `varbinary(max)` so I would have to read it as a byte array into a string and manually deserialize    it or parse it into a JObject and look for the fields I need. I don't think this scales well trying to read the JSON contents directly from the saga data column because now I need to know the data structure in not only the ISagaData model, but also in the JSON parsing logic as well.

Having some method to get the typed object out would be most ideal so that the underlying storage is abstracted out of my applications and solely managed by Rebus.

Just as @asleire mentioned, I can also think of several corner cases where having access to the other methods in `ISagaStorage` would be beneficial.
