### ISSUE TITLE
Nested polymorphic dispatch 

### ISSUE THREAD

**Issue by TobiasNissen** [rebus-org/Rebus#934]
In the current version, polymorphic dispatch does not work for all nested types.
For instance, consider the following:
```c#
public class MyHandler : IHandleMessages<Interface1<Class1>> {...}

public interface Interface1 {...}

public class Class1 {...}

public class SubClass : Class1 {...}
```

I expect this handler to get messages for the type `Interface1<SubClass>`, but this is not the case in the current version (6.4.2-b1)

Until this gets fixed, does anyone have any suggestions on how to handle this?

**Comment by mookid8000** [comment]
Rebus' "polymorphic dispatch" feature is affected by the capabilities of the chosen IoC container.

It's because Rebus will look up handlers via its [`IHandlerActivator`](https://github.com/rebus-org/Rebus/wiki/IHandlerActivator), which is where you'll find an implementation that has been made for your container.

Some containers are capable of respecting C#'s variance (can never remember which one is _co-_, and which one is _contra-_ 😆 ) and will thus deliver all polymorphically compatible handlers from one single
```csharp
var handlers = container.GetAll<IHandleMessages<ConcreteMessage>>();
```
which is super neat.

Most containers though need Rebus to "polyfill" that functionality, which happens in the `IHandlerActivator` implementation for that container. In those cases, it will generate an inheritance hierarchy for the concrete type of the message, include all implemented interfaces, and then resolve `IHandleMessages<T>` for each of those types.

In your case, you seem to have two levels of variant generics at play, which is something I know none of the polyfills I have written take into account.

Which IoC container are you using?

**Comment by TobiasNissen** [comment]
Thanks for the quick reply!

That makes sense.

I am using `Rebus.ServiceProvider`, registering Rebus with `services.AddRebus(...)`.

**Comment by TobiasNissen** [comment]
I have created a PR in the appropriate project. Thus, I'm closing this.
