### ISSUE TITLE
Question: Best practices for dead transport?

### ISSUE THREAD

**Issue by kendallb** [rebus-org/Rebus#949]
What would be consider the best practice for error handling in the case where the transport goes down? Clearly the message handlers themselves will not be a problem as they would crash out and just keep coming back and trying again (while logging to the error logs), but in the case of message sending, if the transport is down the send will simply crash out after a timeout period.

Should we just handle that like any normal fatal error, or does it make sense to set up another message bus transport you could send to as a backup, say a local file system so the messages at least would end up in there for a post mortem analysis and possibly getting replayed when things have been fixed?

**Comment by mookid8000** [comment]
There's no "best practice" as such, it's all about what your availability requirements are.

Many times it makes a lot of sense to use a (real 🙂) queueing system as the transport, because then it's not subject to the same availability challenges as a centralized relational database with transactions, deadlocks, etc. 

So.... in your case I would probably try and go through the different places where messages are sent/published outside of message handlers (i.e. where message sequences are initiated) and think about whether retrying (e.g. with [Polly](https://github.com/App-vNext/Polly)) and/or using an intermediate store-and-forward mechanism would make sense.

**Comment by kendallb** [comment]
Yes, longer term I will probably write a Google Pub/Sub transport (already started on it, but don't have the time at the moment). Our message volume is quite low for now. But even then, there is no guarantee that Google Pub/Sub or Auzre or whatever does not have an outage?

One option I suppose we could implement would be to catch the exception when it occurs during sending, and public the message contents to our Raygun error logs so at least we can capture it. Or log it somewhere else with Nlog, such as a shared disk log or something.

**Comment by mookid8000** [comment]
> (..) But even then, there is no guarantee that Google Pub/Sub or Auzre or whatever does not have an outage?

That's true, but queueing systems are usually much less likely to be unavailable (generalizing a lot here, of course), because they're simpler and do not have to  a lot of complexity around concurrency.

> One option I suppose we could implement would be to catch the exception when it occurs during sending, and public the message contents to our Raygun error logs so at least we can capture it. Or log it somewhere else with Nlog, such as a shared disk log or something.

I would start out like that, and then – if it turns out to happen too often, so often that it becomes impractical to handle manually – I'd look into a more sophisticated solution.

**Comment by kendallb** [comment]
Yes, I think at the moment it won't happen too much. Rebus is stored in the same MySQL database cluster as the rest of our data, so if it has issues, the entire system has issues. If it crashes attempting to publish a message, it will likely crash on the next bit of MySQL code anyway so it would not be clear whether the message is something you would want to even republish anyway. So mostly at the moment trying to find somewhere else to stash it for post mortem analysis of whatever crash happened. They do not happen very often since MySQL is HA already and fault tolerant. But even Google has outages at times. Probably just will either NLog it or push to Raygun.
