### ISSUE TITLE
Saga is swallowing wrong messages without error

### ISSUE THREAD

**Issue by oocpawel** [rebus-org/Rebus#955]
I am using Rebus 3.1.5 and i have discovered a new issue that would be good to check in Rebus head if it still occur.

Description:
 - Saga messages are corelated by some property (in my situation this is string property, called id)
 - if in the middle of the Saga one message will have wrong value under this property (id) that not match with previous messages, a message will simply disapear, Rebus will get this message from a queue and do nothing, no error, message won't be redirected to error-queue, it will simply disapear

Expected behavior:
- Rebus should redirect message to error-queue with error: "No matching handler/saga" or something like that.
In the end i would like to be able to see this message under Rebus Snoop to easily find out a problem with wrong message id

**Comment by mookid8000** [comment]
I am not 100% sure I understand your question, but if this is about Rebus silently ignoring messages that 

* can potentially be handled by a saga
* but could not be correlated with an existing saga instance
* and are not allowed to initiate a new saga instance

then that behavior is by design.

Could you tell me more about why you have that problem?
