### ISSUE TITLE
Is there XML serialization mode of messages?

### ISSUE THREAD

**Issue by rafek1241** [rebus-org/Rebus#956]
Like in the topic - is there XML serialization mode of messages?

I want to make migration from pretty old NServiceBus to the ReBus.

**Comment by mookid8000** [comment]
Not out of the box, but it should be fairly easy to accomplish by providing a custom serializer.

You can read a little bit about serialization [here](https://github.com/rebus-org/Rebus/wiki/Serialization) and [here](https://github.com/rebus-org/Rebus/wiki/ISerializer) on the wiki.

To customize it, you would implement [`ISerializer`](https://github.com/rebus-org/Rebus/blob/master/Rebus/Serialization/ISerializer.cs) and then register it by going
```csharp
Configure.With(...)
	.(...)
	.Serialization(s => s.Register(c => new MyCustomSerializer()))
	.Start();
``` 
most likely wrapping the ugly bits in an extension method for `StandardConfigurer<ISerializer>` so it becomes
```csharp
Configure.With(...)
	.(...)
	.Serialization(s => s.UseMyCustomSerializer())
	.Start();
```

**Comment by rafek1241** [comment]
@mookid8000 
Thank you and sorry for not tagging that.

**Comment by rafek1241** [comment]
@mookid8000 
Is it possible to make different serialization for message headers as well?

**Comment by mookid8000** [comment]
> Thank you and sorry for not tagging that.

Oh, no problem 🙂

> Is it possible to make different serialization for message headers as well?

Rebus represents headers as a `Dictionary<string, string>`, and then it's up to the transport implementation to map it to whatever mechanism is offered by the actual transport... e.g. with MSMQ, the transport needs to serialize as UTF8-encoded JSON, because the transport is only capable of transferring a `byte[]` in its extension field, whereas Azure Service Bus and most other transports have a proper model for attaching headers to messages.
