### ISSUE TITLE
Lack of Handle method with Type parameter

### ISSUE THREAD

**Issue by janusznoszczynski** [rebus-org/Rebus#964]
Hi all,

I am new to the Rebus and maybe I am missing something, but I noticed that there is only generic Handle method that require knowing message type at compile time:
```csharp
public BuiltinHandlerActivator Handle<TMessage>(Func<TMessage, Task> handlerFunction);
```
It is nice since you can leverage strong typing, but it limits other possibilities of using Rebus when message type is resolved only in runtime. I think it would be nice to subscribe messages with method like:
```csharp
public BuiltinHandlerActivator Handle(Type messageType, Func<object, Task> handlerFunction);
```
In my case it is an issue as I have already abstraction of some Event Bus realized with IEventBus interface. It contains a method that let me subscribe topic by Type which is used across whole codebase:
```csharp
Task<string> SubscribeAsync(Type type, Func<IEvent, Task> handler);
```
I wanted to switch my implementation to Rebus as it has multiple transport options and features that I like. But it seems that lack of possibility to subscribe topic by string/Type is show stopper for me.

In terms of general developer experience I don't see any reason to prevent developers from subscribing topics with run time resolved messages' types. Especially when underlaying transport implementation will required to use topic names as string literals anyway (eg when storing in SQL db).

Maybe my case is supported, but I couldn't find anything like that in samples and documentation...

**Comment by mookid8000** [comment]
As you seem to have discovered already, Rebus' pub/sub implementation is string-based, and so the most "raw" way to subscribe to something would be to
```csharp
await bus.Advanced.Topics.Subscribe("some-topic");
```
to subscribe to the topic `some-topic`, and then have someone
```csharp
await bus.Advanced.Topics.Publish("some-topic", whatever);
```
to publish a message to that topic.

Once registered as a subscriber on a given topic, an endpoint will receive anything published to that topic. The most barebones way of handling received messages would be to use Rebus' [transport message forwarding API](https://github.com/rebus-org/Rebus/wiki/Transport-message-forwarding), which makes it possible for you to handle the incoming message any way you like – it's just a [`TransportMessage`](https://github.com/rebus-org/Rebus/blob/ed4051e3707a8c35e0449cc227f9ede6b8217bd6/Rebus/Messages/TransportMessage.cs).

Most of the time you'll let Rebus deserialize and dispatch the message, though. With the built-in handler activator, you can simply go
```csharp
activator.Handle<object>(async obj => {
    // handle message in here
});
```
to handle all messages, because they're all of type `object`. That's ["polymorphic dispatch"](https://github.com/rebus-org/Rebus/wiki/Polymorphic-message-dispatch) at your service. 🙂  It does require, though, that the incoming message can be properly deserialized.

I hope this has given you an overview of which mechanisms Rebus provides for you to use.
