### ISSUE TITLE
Correlate with collection

### ISSUE THREAD

**Issue by rosieks** [rebus-org/Rebus#968]
I can't find a way to correlate message with property in collection in saga. Something like that:

```csharp
class OrderSagaData
{
   public Guid OrderId { get; set; }
   public Guid[] ProductIds { get; set; } 
}
```

and latter something like this:
```csharp
{
    config.Correlate<ProductArrived>(msg => msg.ProductId, saga => saga.ProductIds);
}
```
If this is not supported it would be really great to have it. Right now it prevents more advanced scenarios or requires other event to be aware of not-related data just for correlation.

**Comment by mookid8000** [comment]
Unfortunately, this is not readily possible with Rebus' sagas.

The reason is mostly that it would add this particular requirement to all Rebus' saga persisters, which might not be possible (or would affect performance or other things negatively) with all supported data stores.

But, remember that a saga is just a piece of state that gets retrieved and updated by incoming messages - in most cases, it wouldn't require too much work to build that kind of functionality manually, e.g. using EF Core or whatever you're using.

Ok?

**Comment by rosieks** [comment]
That's a pity it's not supported. But anyway it would be nice to have more advanced way to search (more advanced queries) and store (storing plain data so I can query it for UI reason) sagas in the future.
