### ISSUE TITLE
Support for static subscriptions

### ISSUE THREAD

**Issue by SbiCA** [rebus-org/Rebus#979]
First of all thanks for this great piece of software ❤️

We're using simple transports `AWS.SQS` and `Azure.StorageQueues` and those work great for direct messaging e.g.

`Service A` => `Service B` or `Service A` => `Service C`

But as soon as you would like to send the same message from Service a to both you'll need start using `AWS.SNS` or `Azure.ServiceBus` 

`Service A` => `Service B`
`Service A` => `Service C`

The feature request on our end would be to allow a simple static configuration of outgoing and it would be overkill to go for a complex solution if you need only a "simple" fanout and in addition these routes don't change in our case so only configuring it on the sender side would be good enough
``` c#
services.AddRebus(configure =>
            {
                configure.Transport(t =>
                    t.UseAmazonSQS(
                        env.ResolveAwsCredentials(),
                        new AmazonSQSConfig {RegionEndpoint = RegionEndpoint.GetBySystemName(_queuesDirectory.Region)},
                       "Service A",
                        ...));

               // maybe allow mapping the same type more than once?
                configure.Routing(r => r.TypeBased()
                    .Map<MessageToBeSent>("Service B")
                    .Map<MessageToBeSent>("Service C")
                  
                    // or accepting more than one queue?
                  .Map<MessageToBeSent>("Service B","Service C")
                );

                return configure;
            });

```

What do you think feasible and reasonable?

**Comment by mookid8000** [comment]
Rebus has a pretty well-established model where you can be sure that
```csharp
await bus.Send(...);
```
always results in 1 message being sent to 1 destination queue exactly, and
```csharp
await bus.Publish(...);
```
results in 0..n message copies being distributed to anyone who subscribed.

So, in your case, I suggest you either:

a) have subscribers subscribe to the message types they're interested in – then a copy will be distributed to each of them, when a publisher published, or

b) send messages using an extension method that manually sends a copy to each destination queue

Since (a) requires a subscription storage of some kind (since you're using Amazon SQS that does not have native pub-sub),  I can definitely understand why you might want to go for (b).

(b) I'd probably implement somewhat like this:
```csharp
public static class CustomRebusRoutingExtensions
{
    static readonly ConcurrentDictionary<Type, IReadOnlyList<string>> _destinations = new() {
        [typeof(MessageToBeSent)] = new[] {"recipient-a", "recipient-b}
    };

    public static Task SendToPredefinedDestinations(this IBus bus, object message)
    {
        var type = object.GetType();
        var destinations = _destinations.TryGet(type, out var result) ? result : throw new ArgumentException($"Sorry, but no queue destinations are configured for messages of type {type}");

        return Task.WhenAll(destinations.Select(destination => bus.Advanced.Routing.Send(destination, message)));
    }
}
```

Do you think that would work for you?

**Comment by SbiCA** [comment]
Thx a lot ! I'll give it a try my only worry with option b) would be that you by accident you could end up in a split brain by not using the extension in some cases. An other thing I not so sure yet is how to understandable when to register the default type type-based-router vs the extension but I guess I'll be able to figure out a nice way an let you know ;)
