### ISSUE TITLE
Type based routing with rabbitmq

### ISSUE THREAD

**Issue by isakgjaerum** [rebus-org/Rebus#990]
Hi!

I am working on a project where we have several services that should communicate using Rebus with Rabbitmq.
I have been exploring the use of type-based routing to handle where the messages are sent.
To make configuration easier we would like to have each service in the cluster configure which types they handle and not have to worry about binding anything when sending types
For example:

![image](https://user-images.githubusercontent.com/35335656/133573518-34112cf6-5d63-4f3b-9298-8e03a2aa4d58.png)

Where Service A only maps Type A to a queue and Service B does the same for Type B.
And the result should be that when Service A sends a message of Type B, Service B should get the message.
Is that possible?
We have tried mapping types but it seems like both services would have to declare and map Type A and Type B, hence share a configuration which doesn’t scale very well.

**Comment by mookid8000** [comment]
With Rebus there's two ways of routing messages: 
1. sending
2. publishing

## Sending

When you SEND (`await bus.Send(...)`) the message goes directly to the recipient's queue(*), and in this case it's the SENDER that need to know where the message should go. You can configure the sender to know this for each message type like this:
```csharp
.Routing(r => r.TypeBased().Map<MyMessage>("recipient-queue"))
```

## Publishing

When you PUBLISH (`await bus.Publish(...)`) the message goes to anyone who subscribed. Subscribers subscribe by calling `await bus.Subscribe<EventType>()`. In this case, it's the RECEIVER that knows which messages it's interested in.

## Your example

In your example it seems you're mixing things together a little bit. 

When you talk about "sending", in your case Service A would need to map TypeB to Service B's input queue
```csharp
.Routing(r => r.TypeBased().Map<TypeB>("service-b"))
```
and Service B would need to map TypeA to Service A's input queue
```csharp
.Routing(r => r.TypeBased().Map<TypeA>("service-a"))
```

because that would make each of them route the two types to their respective destination.

Makes sense?

## Read more

on the wiki: https://github.com/rebus-org/Rebus/wiki/Routing

---
(*) although with RabbitMQ there's an exchange of type DIRECT and a binding that makes this happen

**Comment by isakgjaerum** [comment]
You are absolutely right, i did mix things up. Using `await bus.Publish(...)` instead of `await bus.Send(...)` was what i actually wanted to do. And i see that it makes sense to map the types to their respective destinations when using `await bus.Send(...)`.

One thing that put me off in the process though, does the "(*)" from the Wiki on Routing belong on the bullet point below?

> When you
>``` csharp
>await bus.Subscribe<EventMessage>();
>```
>Rebus will
>
> - generate a topic string out of the `EventMessage` type, e.g. something like `Messages.EventMessage, Messages`
> - look through its endpoint mappings to find the queue name of the owner of `Messages.EventMessage, Messages`, e.g. something like `event-publisher`(*)
> - send a `SubscribeRequest` to the `event-publisher` queue
> - (the Rebus endpoint behind `event-publisher` will intercept the message and store the sender's input queue name as a subscriber of the topic `Messages.EventMessage, Messages` in its subscription storage)

> (*) If you're using a transport with native support for publish/subscribe messaging (e.g. like Azure Service Bus or RabbitMQ), then Rebus will NOT send a `SubscribeRequest` – instead it will simply bind the relevant topic to the subscriber's input queue.



Anyway, thanks for the thorough reply!
