### ISSUE TITLE
Specific message in queue resulted in application not loading

### ISSUE THREAD

**Issue by mnabe** [rebus-org/Rebus#991]
I ran into an issue this morning, that I suspect is related to Rebus (but not sure).

When starting application through Visual Studio on localhost, the application was never loaded/the request for loading the site was eternally "pending" (no response).

When I changed my connection-string to an environment with significantly less rebus messages, my application loaded as per usual.

I am sorry that I couldn't supply more information, but wanted to share just in case that it is indeed a Rebus-related problem.

**Update:**
I tried to delete all rebus messages in my localdb manually one by one and see if it resolved the problem. It turned out, that it was one specific scheduled message, that caused the trouble, and my application starts as usual after removing it.

However, the message looks similar to other messages stored in my localdb, so what the reason could be is still unknown. It may be a flawed configuration on my part, rather than a Rebus-problem, but I am letting the issue remain open in case you find it interesting or have heard about something similar before. 

Otherwise, feel free to close it.

**Comment by mookid8000** [comment]
I haven't heard anything about anyone having any issues that resemble what you describe here.

Also, since Rebus doesn't have any way of looking at messages before receiving them, I find it very unlikely that some property of some specific message in the middle of the queue could have any effect on Rebus.

My guess is that something else has caused this, e.g. a misconfigured host or database name in the connection string, which will cause the initial connection attempt to pause for a relatively long time before failing.

So I am going to close this issue. I'd be happy if you would report back here if you discover what went wrong. Also, if you encounter any issue like this again, please do not hesitate to come back here and tell about it. 🙂

**Comment by mnabe** [comment]
Thanks for reporting back, it sounds likely that it stems from a misconfiguration on my part.
I will make sure to keep an eye out and report back on this issue/@ you, if it happens again or I am able to find out more about the cause in the future. 🙂
