### ISSUE TITLE
Garbage collection for databus storage

### ISSUE THREAD

**Issue by JanRou** [rebus-org/Rebus#999]
Idea
Is it possible for the databus storage to have a garbage collection, so storage clean up scritps or manually procedures are obsolete?
It should be possible to use reference counting and a configurable timer, so attachments are deleted when all messages have been handled or the timer runs out.

**Comment by mookid8000** [comment]
It's not readily supported by Rebus, mainly because it would raise a bunch of questions how it would be implemented.

I've used Azure blobs and the file system for attachments myself, and in both cases I've had automatic cleanup procedures in place. For Azure blobs it's pretty easy to configure a cleanup policy (under "Lifecycle Management") that simply removes blobs that haven't been modified for e.g. a month or two. For the file system, I've several times written jobs run by the Windows Scheduler which would read the metadata of the attachments and then delete them if they had not been read for a month or so.

It would definitely be interesting if it was possible to use reference counting to keep track of the relevance of each attachment, but I don't think that would be possible to implement in a general fashion, as transports with built-in multicast (e.g. RabbitMQ and Azure Service Bus) will not readily tell you how many queues get a copy of a each published event.

**Comment by mookid8000** [comment]
Which data bus storage are you using? Do you think one of the approaches mentioned above could work for you?

**Comment by JanRou** [comment]
> Which data bus storage are you using? Do you think one of the approaches mentioned above could work for you?

Please , close the issue!
I can't find any meaningful way to clean up storage no longer in use by the databus. A good way to clean up is by scripts or functions that are run periodically and have the proper credentials to delete or remove resources like blobs or files.

**Comment by mookid8000** [comment]
Sure thing 🙂 If you think of some brilliant way of providing a solution this this problem, please let me know!
